# Generated by Django 5.2 on 2026-06-02 09:14

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "billing",
            "0003_rename_billing_pix_status_expires_idx_billing_pix_status_0cbf64_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="tissbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Aberto"),
                    ("closed", "Fechado"),
                    ("submitted", "Enviado"),
                    ("processed", "Processado"),
                    ("cancelled", "Cancelado"),
                ],
                db_index=True,
                default="open",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="GlosaSafetyAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "check_code",
                    models.CharField(
                        choices=[
                            ("duplicate", "Procedimento duplicado"),
                            ("stale_price", "Valor diverge da tabela vigente"),
                            ("not_in_table", "Procedimento não tabelado"),
                            ("incomplete", "Dados incompletos"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("block", "Bloqueia"), ("advise", "Avisa")], max_length=10
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("engine", "Motor determinístico"), ("llm", "LLM (explicação)")],
                        default="engine",
                        help_text="Which checker produced this row: 'engine' verdict or (future) 'llm'.",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("flagged", "Alertado"),
                            ("acknowledged", "Reconhecido"),
                            ("resolved", "Resolvido"),
                        ],
                        default="flagged",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(verbose_name="Mensagem (pt-BR)")),
                (
                    "recommendation",
                    models.TextField(blank=True, verbose_name="Recomendação (pt-BR)"),
                ),
                (
                    "ans_glosa_code",
                    models.CharField(
                        blank=True,
                        help_text="Mapped ANS reason code (see GLOSA_REASON_CODES). Blank = unmapped.",
                        max_length=5,
                        verbose_name="Código de glosa ANS",
                    ),
                ),
                ("override_reason", models.TextField(blank=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("was_denied", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_glosa_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "guide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="glosa_safety_alerts",
                        to="billing.tissguide",
                    ),
                ),
                (
                    "guide_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for per-line checks; NULL for guide-level structural checks.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="glosa_safety_alerts",
                        to="billing.tissguideitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta de Glosa (motor)",
                "verbose_name_plural": "Alertas de Glosa (motor)",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["guide", "status", "severity"],
                        name="billing_glo_guide_i_3be5f4_idx",
                    )
                ],
                "unique_together": {("guide", "guide_item", "check_code", "source")},
            },
        ),
    ]
