# Generated by Django 5.2 on 2026-06-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0005_glosa_alert_nulls_distinct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="glosasafetyalert",
            name="check_code",
            field=models.CharField(
                choices=[
                    ("duplicate", "Procedimento duplicado"),
                    ("stale_price", "Valor diverge da tabela vigente"),
                    ("not_in_table", "Procedimento não tabelado"),
                    ("incomplete", "Dados incompletos"),
                    ("engine_error", "Verificação indisponível"),
                    ("table_unresolved", "Cobertura não verificada"),
                    ("clinical_incompat", "Incompatibilidade clínica"),
                ],
                max_length=20,
            ),
        ),
    ]
