# Generated by Django 5.2 on 2026-06-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0008_authorization_and_requires_authorization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="glosa",
            name="reason_code",
            field=models.CharField(
                choices=[
                    ("00", "Não informado"),
                    ("01", "Procedimento não coberto"),
                    ("02", "Incompatibilidade de sexo"),
                    ("03", "Incompatibilidade de idade"),
                    ("04", "Prazo de carência"),
                    ("05", "Inconsistência nos dados do beneficiário"),
                    ("1702", "Cobrança de procedimento em duplicidade"),
                    ("99", "Outro"),
                ],
                max_length=5,
                verbose_name="Código de motivo",
            ),
        ),
    ]
