# Generated by Django 5.2 on 2026-07-25 03:59

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0014_makerchecker_and_matched_tx_constraint"),
        ("core", "0026_tusscode_table_number_cbhpmitem"),
        ("emr", "0039_medicationreconciliation_and_more"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountsreceivable",
            name="cost_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receivables",
                to="organization.costcenter",
            ),
        ),
        migrations.AddField(
            model_name="accountsreceivable",
            name="origin",
            field=models.CharField(
                choices=[
                    ("tiss", "Guia TISS"),
                    ("private", "Particular"),
                    ("package", "Pacote"),
                    ("pix", "PIX"),
                    ("other", "Outro"),
                ],
                db_index=True,
                default="tiss",
                max_length=12,
                verbose_name="Origem",
            ),
        ),
        migrations.AddField(
            model_name="accountsreceivable",
            name="paid_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
        ),
        migrations.AddField(
            model_name="accountsreceivable",
            name="pix_charge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receivables",
                to="billing.pixcharge",
            ),
        ),
        migrations.AddField(
            model_name="tissguide",
            name="executor",
            field=models.ForeignKey(
                blank=True,
                help_text="Profissional executor (guia de honorários). Vazio nas demais guias.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="honorario_guides",
                to="emr.professional",
            ),
        ),
        migrations.AddField(
            model_name="tissguide",
            name="honorario_cbhpm",
            field=models.ForeignKey(
                blank=True,
                help_text="Procedimento CBHPM que valora o honorário (porte × valor-CH).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="honorario_guides",
                to="core.cbhpmitem",
            ),
        ),
        migrations.AddField(
            model_name="tissguide",
            name="honorario_value",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0"),
                max_digits=12,
                verbose_name="Valor do honorário (R$)",
            ),
        ),
        migrations.AlterField(
            model_name="accountsreceivable",
            name="guide",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receivable",
                to="billing.tissguide",
            ),
        ),
        migrations.AlterField(
            model_name="accountsreceivable",
            name="status",
            field=models.CharField(
                choices=[
                    ("expected", "Previsto"),
                    ("billed", "Faturado"),
                    ("partial", "Parcialmente recebido"),
                    ("received", "Recebido"),
                    ("overdue", "Vencido"),
                    ("contested", "Contestado"),
                ],
                db_index=True,
                default="expected",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="tissguide",
            name="guide_type",
            field=models.CharField(
                choices=[
                    ("sadt", "SP/SADT"),
                    ("consulta", "Consulta"),
                    ("honorarios", "Honorários"),
                ],
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "fixed_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Preço fechado do pacote. Vazio/0 = calcular pela soma dos itens + taxas.",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Preço fixo negociado (R$)",
                    ),
                ),
                (
                    "taxa_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Taxas (R$)",
                    ),
                ),
                (
                    "diaria_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Diárias (R$)",
                    ),
                ),
                (
                    "filme_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Filme (R$)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "price_table",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="packages",
                        to="billing.pricetable",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="packages",
                        to="billing.insuranceprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pacote",
                "verbose_name_plural": "Pacotes",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="accountsreceivable",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receivables",
                to="billing.package",
            ),
        ),
        migrations.CreateModel(
            name="PackageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, verbose_name="Descrição"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=1, max_digits=8, verbose_name="Quantidade"
                    ),
                ),
                (
                    "unit_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Override explícito. Vazio + CBHPM → valora por porte (CBHPMItem.valor()).",
                        max_digits=12,
                        null=True,
                        verbose_name="Valor unitário (R$)",
                    ),
                ),
                (
                    "cbhpm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="package_items",
                        to="core.cbhpmitem",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="billing.package",
                    ),
                ),
                (
                    "tuss_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="package_items",
                        to="core.tusscode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Pacote",
                "verbose_name_plural": "Itens de Pacote",
            },
        ),
    ]
