# Generated by Django 5.2 on 2026-07-25 04:32

import django.db.models.deletion
from django.db import migrations, models


def backfill_patient_from_guide(apps, schema_editor):
    """Existing receivables predate the untethering — all have a guia. Populate the
    new denormalized patient link from guide.patient so they stay patient-queryable."""
    AccountsReceivable = apps.get_model("billing", "AccountsReceivable")
    qs = AccountsReceivable.objects.filter(patient__isnull=True, guide__isnull=False)
    for receivable in qs.select_related("guide").iterator():
        receivable.patient_id = receivable.guide.patient_id
        receivable.save(update_fields=["patient"])


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0016_cost_center_fk_payable_accountingentry"),
        ("emr", "0039_medicationreconciliation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountsreceivable",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receivables",
                to="emr.patient",
            ),
        ),
        migrations.RunPython(backfill_patient_from_guide, migrations.RunPython.noop),
    ]
