# Generated by Django 5.2 on 2026-07-26 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0017_accountsreceivable_patient"),
        ("core", "0029_loinccode_ucumunit"),
        ("emr", "0041_labtest_delta_threshold_pct_labtest_loinc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tissguide",
            name="lab_order",
            field=models.ForeignKey(
                blank=True,
                help_text="Pedido de exames que originou esta guia (ponte LIS→faturamento).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tiss_guides",
                to="emr.laborder",
            ),
        ),
        migrations.AddConstraint(
            model_name="tissguide",
            constraint=models.UniqueConstraint(
                condition=models.Q(("lab_order__isnull", False)),
                fields=("lab_order",),
                name="uniq_tiss_guide_per_lab_order",
            ),
        ),
    ]
