# Generated by Django 5.2 on 2026-07-28 21:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_tissguide_lab_order_and_more'),
        ('core', '0033_sigtapprocedure'),
        ('emr', '0051_professional_cns'),
        ('organization', '0002_facility_cnes_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SusCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.CharField(help_text='Ex.: 2026-07', max_length=7, verbose_name='Competência (AAAA-MM)')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada'), ('exportada', 'Exportada')], db_index=True, default='aberta', max_length=12, verbose_name='Situação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sus_competencias_criadas', to=settings.AUTH_USER_MODEL)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sus_competencias', to='organization.facility', verbose_name='Estabelecimento (CNES)')),
            ],
            options={
                'verbose_name': 'Competência SUS',
                'verbose_name_plural': 'Competências SUS',
                'ordering': ['-competencia'],
            },
        ),
        migrations.CreateModel(
            name='BpaIndividualizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cns', models.CharField(blank=True, default='', max_length=15, verbose_name='CNS do paciente (snapshot)')),
                ('cid', models.CharField(blank=True, default='', max_length=10, verbose_name='CID-10')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='(sigtap.valor_sa + sigtap.valor_sp) × quantidade.', max_digits=12, verbose_name='Valor (R$)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cbo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.cbocode', verbose_name='Ocupação CBO')),
                ('encounter_procedure', models.ForeignKey(blank=True, help_text='Origem clínica (rastreabilidade). Usado para idempotência do bridge.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bpa_i_lines', to='emr.encounterprocedure', verbose_name='Procedimento clínico de origem')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bpa_i_lines', to='emr.patient', verbose_name='Paciente')),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bpa_i_lines', to='emr.professional', verbose_name='Executor')),
                ('sigtap', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.sigtapprocedure', verbose_name='Procedimento SIGTAP')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bpa_i', to='billing.suscompetencia')),
            ],
            options={
                'verbose_name': 'BPA Individualizado (BPA-I)',
                'verbose_name_plural': 'BPA Individualizados (BPA-I)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BpaConsolidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.PositiveIntegerField(verbose_name='Idade (faixa etária consolidada)')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='(sigtap.valor_sa + sigtap.valor_sp) × quantidade, no momento do registro.', max_digits=12, verbose_name='Valor (R$)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cbo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.cbocode', verbose_name='Ocupação CBO')),
                ('sigtap', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.sigtapprocedure', verbose_name='Procedimento SIGTAP')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bpa_c', to='billing.suscompetencia')),
            ],
            options={
                'verbose_name': 'BPA Consolidado (BPA-C)',
                'verbose_name_plural': 'BPA Consolidados (BPA-C)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='suscompetencia',
            constraint=models.UniqueConstraint(fields=('establishment', 'competencia'), name='uniq_sus_competencia_per_establishment'),
        ),
        migrations.AddConstraint(
            model_name='bpaindividualizado',
            constraint=models.UniqueConstraint(condition=models.Q(('encounter_procedure__isnull', False)), fields=('competencia', 'encounter_procedure'), name='uniq_bpa_i_per_competencia_encproc'),
        ),
    ]
