# Generated by Django 5.2 on 2026-07-28 21:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0019_suscompetencia_bpaindividualizado_bpaconsolidado_and_more"),
        ("core", "0033_sigtapprocedure"),
        ("emr", "0052_encounterprocedure_sigtap"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="suscompetencia",
            name="exportada_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp da exportação da remessa (transição fechada → exportada).",
                null=True,
                verbose_name="Exportada em",
            ),
        ),
        migrations.AddField(
            model_name="suscompetencia",
            name="remessa_apac",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Conteúdo .txt da remessa APAC gerado no momento da exportação (imutável).",
                verbose_name="Remessa APAC (texto posicional)",
            ),
        ),
        migrations.AddField(
            model_name="suscompetencia",
            name="remessa_bpa",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Conteúdo .txt da remessa BPA gerado no momento da exportação (imutável).",
                verbose_name="Remessa BPA-Magnético (texto posicional)",
            ),
        ),
        migrations.CreateModel(
            name="ApacAutorizacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "numero_apac",
                    models.CharField(
                        help_text="Número único da autorização APAC (emitido pelo gestor SUS).",
                        max_length=13,
                        unique=True,
                        verbose_name="Número da APAC",
                    ),
                ),
                ("validade_inicio", models.DateField(verbose_name="Início da validade")),
                ("validade_fim", models.DateField(verbose_name="Fim da validade")),
                (
                    "cid_principal",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="CID-10 principal"
                    ),
                ),
                (
                    "cns",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=15,
                        verbose_name="CNS do paciente (snapshot)",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Valor autorizado da APAC (procedimento principal + secundários).",
                        max_digits=12,
                        verbose_name="Valor autorizado (R$)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "competencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apacs",
                        to="billing.suscompetencia",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="apac_autorizacoes_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="apac_autorizacoes",
                        to="emr.patient",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "procedimento_principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.sigtapprocedure",
                        verbose_name="Procedimento principal (SIGTAP)",
                    ),
                ),
                (
                    "professional_executante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="apac_executadas",
                        to="emr.professional",
                        verbose_name="Profissional executante",
                    ),
                ),
                (
                    "professional_solicitante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="apac_solicitadas",
                        to="emr.professional",
                        verbose_name="Profissional solicitante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Autorização APAC",
                "verbose_name_plural": "Autorizações APAC",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApacProcedimentoSecundario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(default=1, verbose_name="Quantidade")),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="(sigtap.valor_sa + sigtap.valor_sp) × quantidade, no momento do registro.",
                        max_digits=12,
                        verbose_name="Valor (R$)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "apac",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedimentos_secundarios",
                        to="billing.apacautorizacao",
                    ),
                ),
                (
                    "sigtap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.sigtapprocedure",
                        verbose_name="Procedimento secundário (SIGTAP)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Procedimento secundário APAC",
                "verbose_name_plural": "Procedimentos secundários APAC",
                "ordering": ["created_at"],
            },
        ),
    ]
