# Generated by Django 5.2 on 2026-07-29 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0020_suscompetencia_exportada_at_and_more"),
        ("core", "0034_bloodcomponentcatalog"),
        ("emr", "0056_transfusionadministration_transfusionreaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tissguide",
            name="surgical_case",
            field=models.ForeignKey(
                blank=True,
                help_text="Caso cirúrgico que originou esta guia (ponte Centro Cirúrgico→faturamento).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tiss_guides",
                to="emr.surgicalcase",
            ),
        ),
        migrations.AddConstraint(
            model_name="tissguide",
            constraint=models.UniqueConstraint(
                condition=models.Q(("surgical_case__isnull", False)),
                fields=("surgical_case",),
                name="uniq_tiss_guide_per_surgical_case",
            ),
        ),
    ]
