# Generated by Django 5.2 on 2026-07-29 03:06

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0021_tissguide_surgical_case_and_more"),
        ("core", "0034_bloodcomponentcatalog"),
        ("emr", "0056_transfusionadministration_transfusionreaction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccommodationTuss",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "bed_type_code",
                    models.CharField(
                        help_text="Código do tipo de leito (core.BedType.code) a ser cobrado como diária.",
                        max_length=32,
                        verbose_name="Código do tipo de leito",
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tuss_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="accommodation_mappings",
                        to="core.tusscode",
                        verbose_name="TUSS da diária",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mapeamento de diária (tipo de leito → TUSS)",
                "verbose_name_plural": "Mapeamentos de diária (tipo de leito → TUSS)",
                "ordering": ["bed_type_code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("bed_type_code",), name="uniq_accommodation_tuss_per_bed_type"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyCharge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("service_date", models.DateField(db_index=True, verbose_name="Data da diária")),
                (
                    "bed_type_code",
                    models.CharField(
                        help_text="Snapshot do código do tipo de leito cobrado nesta diária.",
                        max_length=32,
                        verbose_name="Tipo de leito (snapshot)",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1, verbose_name="Quantidade")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_charges",
                        to="emr.admission",
                        verbose_name="Internação",
                    ),
                ),
                (
                    "tuss_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="daily_charges",
                        to="core.tusscode",
                        verbose_name="TUSS da diária",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diária de leito",
                "verbose_name_plural": "Diárias de leito",
                "ordering": ["admission", "service_date"],
                "indexes": [
                    models.Index(
                        fields=["admission", "service_date"], name="bill_dailych_adm_date_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("admission", "service_date"),
                        name="uniq_daily_charge_per_admission_day",
                    )
                ],
            },
        ),
    ]
