# Generated by Django 5.2 on 2026-07-29 04:16

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0023_tissguide_admission_and_more"),
        ("core", "0035_simpromaterial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialPriceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "negotiated_value",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Valor negociado do material com o convênio (tipicamente Simpro menos deflator).",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Valor negociado (R$)",
                    ),
                ),
                (
                    "simpro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_price_items",
                        to="core.simpromaterial",
                        verbose_name="Material Simpro",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_items",
                        to="billing.pricetable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Material (preço negociado)",
                "verbose_name_plural": "Itens de Material (preço negociado)",
                "unique_together": {("table", "simpro")},
            },
        ),
    ]
