# Generated by Django 5.2 on 2026-07-29 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0024_materialpriceitem"),
        ("emr", "0057_surgicalmaterial_simpro"),
    ]

    operations = [
        migrations.AddField(
            model_name="tissguideitem",
            name="surgical_material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="guide_items",
                to="emr.surgicalmaterial",
                verbose_name="Material cirúrgico de origem",
            ),
        ),
    ]
