# Generated by Django 5.2 on 2026-07-29 08:40

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0025_tissguideitem_surgical_material"),
        ("core", "0035_simpromaterial"),
        ("emr", "0057_surgicalmaterial_simpro"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AihAutorizacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "numero_aih",
                    models.CharField(
                        help_text="Número único da autorização AIH (emitido pelo gestor SUS).",
                        max_length=13,
                        unique=True,
                        verbose_name="Número da AIH",
                    ),
                ),
                (
                    "cid_principal",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="CID-10 principal"
                    ),
                ),
                (
                    "cns",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=15,
                        verbose_name="CNS do paciente (snapshot)",
                    ),
                ),
                ("data_internacao", models.DateField(verbose_name="Data da internação")),
                (
                    "data_saida",
                    models.DateField(blank=True, null=True, verbose_name="Data da saída"),
                ),
                (
                    "carater_internacao",
                    models.CharField(
                        choices=[("01", "Eletivo"), ("02", "Urgência")],
                        default="01",
                        max_length=2,
                        verbose_name="Caráter da internação",
                    ),
                ),
                (
                    "motivo_saida",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("alta_melhorado", "Alta por melhora"),
                            ("alta_curado", "Alta por cura"),
                            ("transferencia", "Transferência"),
                            ("obito", "Óbito"),
                            ("permanencia", "Permanência"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="Motivo de saída/permanência",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Valor autorizado da AIH (SH+SP: serviços hospitalares + profissionais).",
                        max_digits=12,
                        verbose_name="Valor autorizado (R$)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aihs",
                        to="emr.admission",
                        verbose_name="Internação",
                    ),
                ),
                (
                    "competencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aihs",
                        to="billing.suscompetencia",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aih_autorizacoes_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aih_autorizacoes",
                        to="emr.patient",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "procedimento_principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.sigtapprocedure",
                        verbose_name="Procedimento principal (SIGTAP)",
                    ),
                ),
                (
                    "professional_responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aih_responsaveis",
                        to="emr.professional",
                        verbose_name="Profissional responsável",
                    ),
                ),
                (
                    "professional_solicitante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aih_solicitadas",
                        to="emr.professional",
                        verbose_name="Profissional solicitante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Autorização AIH",
                "verbose_name_plural": "Autorizações AIH",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AihProcedimentoSecundario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(default=1, verbose_name="Quantidade")),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="(sigtap.valor_sh + sigtap.valor_sp) × quantidade, computado no save.",
                        max_digits=12,
                        verbose_name="Valor (R$)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "aih",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedimentos_secundarios",
                        to="billing.aihautorizacao",
                    ),
                ),
                (
                    "sigtap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.sigtapprocedure",
                        verbose_name="Procedimento secundário (SIGTAP)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Procedimento secundário AIH",
                "verbose_name_plural": "Procedimentos secundários AIH",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="aihautorizacao",
            constraint=models.UniqueConstraint(
                condition=models.Q(("admission__isnull", False)),
                fields=("admission",),
                name="uniq_aih_per_admission",
            ),
        ),
    ]
