# Generated by Django 5.2 on 2026-07-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0027_suscompetencia_remessa_aih"),
    ]

    operations = [
        migrations.AddField(
            model_name="aihautorizacao",
            name="data_autorizacao",
            field=models.DateField(
                blank=True,
                help_text="Data em que o gestor autorizou.",
                null=True,
                verbose_name="Data da autorização",
            ),
        ),
        migrations.AddField(
            model_name="aihautorizacao",
            name="motivo_rejeicao",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Motivo da rejeição"
            ),
        ),
        migrations.AddField(
            model_name="aihautorizacao",
            name="numero_provisorio",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Número provisório interno original, preservado na reconciliação para rastreabilidade quando numero_aih passa a ser o oficial.",
                max_length=13,
                verbose_name="Número provisório (histórico)",
            ),
        ),
        migrations.AddField(
            model_name="aihautorizacao",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("solicitada", "Solicitada"),
                    ("autorizada", "Autorizada"),
                    ("rejeitada", "Rejeitada"),
                ],
                db_index=True,
                default="solicitada",
                help_text="Ciclo perante o gestor: solicitada → autorizada/rejeitada.",
                max_length=12,
                verbose_name="Situação",
            ),
        ),
        migrations.AlterField(
            model_name="aihautorizacao",
            name="numero_aih",
            field=models.CharField(
                help_text="Número corrente da AIH: provisório interno até a reconciliação substituí-lo pelo número oficial de 13 dígitos emitido pelo gestor SUS.",
                max_length=13,
                unique=True,
                verbose_name="Número da AIH",
            ),
        ),
    ]
