# Generated by Django 5.2 on 2026-07-29 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0028_aih_reconciliation"),
        ("core", "0035_simpromaterial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aihautorizacao",
            name="cid10",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.cid10code",
                verbose_name="CID-10 principal (governado)",
            ),
        ),
        migrations.AddField(
            model_name="aihautorizacao",
            name="cid_unmatched",
            field=models.BooleanField(
                default=False,
                help_text="True quando cid_principal não corresponde a nenhum CID10Code governado.",
            ),
        ),
        migrations.AlterField(
            model_name="aihautorizacao",
            name="cid_principal",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Código CID-10 bruto quando não reconciliado com core.CID10Code.",
                max_length=10,
                verbose_name="CID-10 principal (texto)",
            ),
        ),
    ]
