# Generated by Django 5.2 on 2026-07-30 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0029_aih_cid_governed"),
        ("core", "0035_simpromaterial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apacautorizacao",
            name="cid10",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.cid10code",
                verbose_name="CID-10 principal (governado)",
            ),
        ),
        migrations.AddField(
            model_name="apacautorizacao",
            name="cid_unmatched",
            field=models.BooleanField(
                default=False,
                help_text="True quando cid_principal não corresponde a nenhum CID10Code governado.",
            ),
        ),
        migrations.AddField(
            model_name="apacautorizacao",
            name="data_autorizacao",
            field=models.DateField(
                blank=True,
                help_text="Data em que o gestor autorizou.",
                null=True,
                verbose_name="Data da autorização",
            ),
        ),
        migrations.AddField(
            model_name="apacautorizacao",
            name="motivo_rejeicao",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Motivo da rejeição"
            ),
        ),
        migrations.AddField(
            model_name="apacautorizacao",
            name="numero_provisorio",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Número original preservado na reconciliação para rastreabilidade.",
                max_length=13,
                verbose_name="Número provisório (histórico)",
            ),
        ),
        migrations.AddField(
            model_name="apacautorizacao",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("solicitada", "Solicitada"),
                    ("autorizada", "Autorizada"),
                    ("rejeitada", "Rejeitada"),
                ],
                db_index=True,
                default="solicitada",
                help_text="Ciclo perante o gestor: solicitada → autorizada/rejeitada.",
                max_length=12,
                verbose_name="Situação",
            ),
        ),
        migrations.AlterField(
            model_name="apacautorizacao",
            name="cid_principal",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Código CID-10 bruto quando não reconciliado com core.CID10Code.",
                max_length=10,
                verbose_name="CID-10 principal (texto)",
            ),
        ),
        migrations.AlterField(
            model_name="apacautorizacao",
            name="numero_apac",
            field=models.CharField(
                help_text="Número corrente da APAC: reconciliado com o número oficial de 13 dígitos emitido pelo gestor SUS.",
                max_length=13,
                unique=True,
                verbose_name="Número da APAC",
            ),
        ),
    ]
