# Generated by Django 5.2 on 2026-08-04 21:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0031_accrue_admissions_beat_schedule'),
        ('core', '0039_anvisa_presentation'),
        ('emr', '0066_pathology_cido_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InpatientFee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_date', models.DateField(db_index=True, verbose_name='Data do lançamento')),
                ('description', models.CharField(blank=True, default='', help_text='Texto do termo TUSS no momento do lançamento.', max_length=500, verbose_name='Descrição (snapshot)')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantidade na unidade declarada (ex.: 6,5 horas de oxigênio).', max_digits=10, verbose_name='Quantidade')),
                ('unit', models.CharField(choices=[('dia', 'Por dia'), ('hora', 'Por hora'), ('unidade', 'Por unidade')], default='unidade', help_text='Unidade de cobrança do termo TUSS (por dia / por hora / por unidade).', max_length=10, verbose_name='Unidade')),
                ('notes', models.CharField(blank=True, default='', max_length=500, verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inpatient_fees', to='emr.admission', verbose_name='Internação')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Lançado por')),
                ('tuss_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inpatient_fees', to='core.tusscode', verbose_name='TUSS da taxa')),
            ],
            options={
                'verbose_name': 'Taxa de internação',
                'verbose_name_plural': 'Taxas de internação',
                'ordering': ['admission', 'service_date'],
                'indexes': [models.Index(fields=['admission', 'service_date'], name='bill_inpfee_adm_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inpatient_fee_quantity_positive')],
            },
        ),
    ]
