# Generated by Django 5.2 on 2026-08-05 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0032_inpatient_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="tissguideitem",
            name="dispensation_source_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="UUID da pharmacy.Dispensation que gerou esta linha (sem FK: fronteira de domínio).",
                null=True,
                verbose_name="Dispensação de origem",
            ),
        ),
    ]
