# Generated by Django 5.2 on 2026-08-18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0033_guideitem_dispensation_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="tissguide",
            name="authorization_date",
            field=models.DateField(
                blank=True,
                help_text=(
                    "Data de autorização informada manualmente pelo faturista, "
                    "conforme recebida da operadora. Só é usada para preencher "
                    "dataAutorizacao da guia de resumo de internação QUANDO não "
                    "existe uma Authorization aprovada correspondente (paciente/"
                    "operadora/janela/TUSS) — o registro de autorização, quando "
                    "existe, sempre tem prioridade sobre esta digitação."
                ),
                null=True,
                verbose_name="Data da autorização (digitada)",
            ),
        ),
    ]
