# Generated by Django 5.2 on 2026-08-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0034_guide_authorization_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="tissguide",
            name="tipo_faturamento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Código 1 (rótulo a confirmar no manual ANS)"),
                    ("2", "Código 2 (rótulo a confirmar no manual ANS)"),
                    ("3", "Código 3 (rótulo a confirmar no manual ANS)"),
                    ("4", "Código 4 (rótulo a confirmar no manual ANS)"),
                ],
                default="",
                help_text="dm_tipoFaturamento — declara à operadora se esta guia de resumo de internação é o faturamento parcial ou o de encerramento da estada. Obrigatório no XML (ctm_internacaoDados); sem ele a guia de internação não gera XML.",
                max_length=1,
                verbose_name="Tipo de faturamento (TISS)",
            ),
        ),
    ]
