# Generated by Django 5.2 on 2026-08-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0036_guideitem_execucao_e_fator"),
    ]

    operations = [
        migrations.AddField(
            model_name="inpatientfee",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[("taxa", "Taxa / aluguel"), ("gas_medicinal", "Gás medicinal")],
                default="",
                help_text="Separa valorTaxasAlugueis de valorGasesMedicinais no breakdown de ct_guiaValorTotal. Vazio em lançamentos anteriores à Onda 4 — sem ele a guia sai só com valorTotalGeral, nunca com um breakdown que não fecha.",
                max_length=16,
                verbose_name="Categoria (TISS)",
            ),
        ),
        migrations.AddField(
            model_name="tissguideitem",
            name="billing_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("procedimentos", "Procedimentos"),
                    ("diarias", "Diárias"),
                    ("taxas_alugueis", "Taxas e aluguéis"),
                    ("materiais", "Materiais"),
                    ("medicamentos", "Medicamentos"),
                    ("opme", "OPME"),
                    ("gases_medicinais", "Gases medicinais"),
                ],
                db_index=True,
                default="",
                help_text="Campo de ct_guiaValorTotal em que esta linha entra. Gravado pela ponte que criou o item, nunca inferido do TUSS. Vazio = linha anterior à Onda 4; uma única assim faz a guia sair sem breakdown.",
                max_length=20,
                verbose_name="Categoria no valorTotal (TISS)",
            ),
        ),
    ]
