# Generated by Django 5.2 on 2026-08-18 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0037_guideitem_billing_category"),
        ("emr", "0068_admission_tiss_taxonomies"),
    ]

    operations = [
        migrations.AddField(
            model_name="tissguide",
            name="requesting_professional",
            field=models.ForeignKey(
                blank=True,
                help_text="profissionalSolicitante de dadosSolicitante (SP/SADT). Resolvido de LabOrder.requested_by quando a guia nasce de um pedido de exame; informado à mão nos demais casos.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_tiss_guides",
                to="emr.professional",
                verbose_name="Profissional solicitante",
            ),
        ),
    ]
