# Generated by Django 5.2 on 2026-08-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0038_guide_requesting_professional"),
    ]

    operations = [
        migrations.AddField(
            model_name="tissguide",
            name="regime_atendimento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("01", "Código 01 (rótulo a confirmar no manual ANS)"),
                    ("02", "Código 02 (rótulo a confirmar no manual ANS)"),
                    ("03", "Código 03 (rótulo a confirmar no manual ANS)"),
                    ("04", "Código 04 (rótulo a confirmar no manual ANS)"),
                    ("05", "Código 05 (rótulo a confirmar no manual ANS)"),
                ],
                default="",
                help_text="dm_regimeAtendimento (ctm_sp-sadtAtendimento). Sem ele a guia SP/SADT não gera XML.",
                max_length=2,
                verbose_name="Regime de atendimento (TISS)",
            ),
        ),
        migrations.AddField(
            model_name="tissguide",
            name="tipo_atendimento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("01", "Código 01 (rótulo a confirmar no manual ANS)"),
                    ("02", "Código 02 (rótulo a confirmar no manual ANS)"),
                    ("03", "Código 03 (rótulo a confirmar no manual ANS)"),
                    ("04", "Código 04 (rótulo a confirmar no manual ANS)"),
                    ("08", "Código 08 (rótulo a confirmar no manual ANS)"),
                    ("09", "Código 09 (rótulo a confirmar no manual ANS)"),
                    ("10", "Código 10 (rótulo a confirmar no manual ANS)"),
                    ("13", "Código 13 (rótulo a confirmar no manual ANS)"),
                    ("23", "Código 23 (rótulo a confirmar no manual ANS)"),
                ],
                default="",
                help_text="dm_tipoAtendimento (ctm_sp-sadtAtendimento). Sem ele a guia SP/SADT não gera XML.",
                max_length=2,
                verbose_name="Tipo de atendimento (TISS)",
            ),
        ),
    ]
