# Generated by Django 5.2 on 2026-06-21 02:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SmartClient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("client_id", models.CharField(db_index=True, max_length=128, unique=True)),
                ("client_name", models.CharField(max_length=200)),
                ("is_confidential", models.BooleanField(default=False)),
                ("client_secret", models.CharField(blank=True, max_length=255)),
                ("redirect_uris", models.TextField(help_text="One redirect URI per line.")),
                ("scopes", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "SMART Client",
                "verbose_name_plural": "SMART Clients",
                "ordering": ["client_name"],
            },
        ),
        migrations.CreateModel(
            name="SmartAuthorizationCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=255, unique=True)),
                ("redirect_uri", models.CharField(max_length=2000)),
                ("scope", models.TextField(blank=True, default="")),
                ("code_challenge", models.CharField(blank=True, max_length=255)),
                ("code_challenge_method", models.CharField(blank=True, max_length=10)),
                ("patient_id", models.CharField(blank=True, max_length=64)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="smart_authorization_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorization_codes",
                        to="fhir.smartclient",
                    ),
                ),
            ],
            options={
                "verbose_name": "SMART Authorization Code",
                "verbose_name_plural": "SMART Authorization Codes",
                "ordering": ["-created_at"],
            },
        ),
    ]
