# Generated by Django 5.2 on 2026-04-26 23:31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("hire_date", models.DateField()),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("active", "Ativo"),
                            ("leave", "Afastado"),
                            ("terminated", "Desligado"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("clt", "CLT"),
                            ("pj", "PJ"),
                            ("estagio", "Estágio"),
                            ("temporary", "Temporário"),
                        ],
                        max_length=20,
                    ),
                ),
                ("terminated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Funcionário",
                "verbose_name_plural": "Funcionários",
                "ordering": ["-created_at"],
            },
        ),
    ]
