# Generated by Django 5.2 on 2026-07-26 00:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0002_hr_operations"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="Título")),
                (
                    "cbo",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=16, verbose_name="CBO"
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cargo",
                "verbose_name_plural": "Cargos",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Dependent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("spouse", "Cônjuge/companheiro(a)"),
                            ("child", "Filho(a)"),
                            ("parent", "Pai/Mãe"),
                            ("other", "Outro"),
                        ],
                        max_length=16,
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("cpf", models.CharField(blank=True, default="", max_length=14)),
                ("is_income_tax_dependent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependents",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dependente",
                "verbose_name_plural": "Dependentes",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(blank=True, default="", max_length=160, verbose_name="Função"),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_assignments",
                        to="organization.costcenter",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="hr.employee",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_assignments",
                        to="organization.organizationalunit",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="hr.position",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lotação",
                "verbose_name_plural": "Lotações",
                "ordering": ["-start_date"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("active", True)),
                        fields=("employee",),
                        name="hr_one_active_assignment_per_employee",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("end_date__isnull", True),
                            ("end_date__gte", models.F("start_date")),
                            _connector="OR",
                        ),
                        name="hr_assignment_valid_vigency",
                    ),
                ],
            },
        ),
    ]
