# Generated by Django 5.2 on 2026-07-26 00:52

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0039_medicationreconciliation_and_more"),
        ("governance", "0002_integration_inbox"),
        ("hr", "0003_position_dependent_employeeassignment"),
        ("organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DutyRoster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="duty_rosters",
                        to="organization.facility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escala",
                "verbose_name_plural": "Escalas",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("vacation", "Férias"),
                            ("sick", "Afastamento médico"),
                            ("maternity", "Licença-maternidade"),
                            ("paternity", "Licença-paternidade"),
                            ("unpaid", "Licença não remunerada"),
                            ("other", "Outro"),
                        ],
                        max_length=16,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("approved", "Aprovada"),
                            ("rejected", "Rejeitada"),
                            ("cancelled", "Cancelada"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approval",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_leave_request",
                        to="governance.approvalrequest",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leave_requests",
                        to="hr.employee",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hr_leave_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação de afastamento",
                "verbose_name_plural": "Solicitações de afastamento",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="RosterSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("morning", "Manhã"),
                            ("afternoon", "Tarde"),
                            ("night", "Noite"),
                            ("full", "Integral"),
                        ],
                        default="full",
                        max_length=16,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_slots",
                        to="hr.employee",
                    ),
                ),
                (
                    "professional",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_slots",
                        to="emr.professional",
                    ),
                ),
                (
                    "roster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="hr.dutyroster",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roster_slots",
                        to="organization.organizationalunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantão",
                "verbose_name_plural": "Plantões",
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.AddConstraint(
            model_name="dutyroster",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="hr_roster_valid_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="leaverequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="hr_leave_valid_period",
            ),
        ),
        migrations.AddIndex(
            model_name="rosterslot",
            index=models.Index(fields=["unit", "date"], name="hr_rostersl_unit_id_6b48a9_idx"),
        ),
        migrations.AddIndex(
            model_name="rosterslot",
            index=models.Index(
                fields=["professional", "date"], name="hr_rostersl_profess_8ea068_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="rosterslot",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_time__gt", models.F("start_time"))),
                name="hr_rosterslot_valid_window",
            ),
        ),
    ]
