# Generated by Django 5.2 on 2026-07-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0041_labtest_delta_threshold_pct_labtest_loinc_and_more"),
        ("hr", "0004_dutyroster_leaverequest_rosterslot_and_more"),
        ("organization", "0002_facility_cnes_fk"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="rosterslot",
            name="hr_rosterslot_valid_window",
        ),
        migrations.AddConstraint(
            model_name="rosterslot",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_time", models.F("start_time")), _negated=True),
                name="hr_rosterslot_valid_window",
            ),
        ),
    ]
