# Generated by Django 5.2 on 2026-05-20 18:46

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("emr", "0015_encounter_signed_at_signed_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TriageSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("contact_phone", models.CharField(blank=True, db_index=True, max_length=20)),
                ("chief_complaint", models.TextField(blank=True)),
                ("answers", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Iniciada"),
                            ("answering", "Respondendo"),
                            ("evaluated", "Avaliada"),
                            ("escalated", "Escalonada"),
                            ("completed", "Concluída"),
                            ("cancelled", "Cancelada"),
                        ],
                        db_index=True,
                        default="started",
                        max_length=20,
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("routine", "Rotina"),
                            ("urgent", "Urgente"),
                            ("emergency", "Emergência"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("rationale", models.TextField(blank=True)),
                ("matched_keywords", models.JSONField(blank=True, default=list)),
                ("red_flags_positive", models.PositiveSmallIntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("evaluated_at", models.DateTimeField(blank=True, null=True)),
                ("escalated_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triage_sessions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional — anonymous WhatsApp triage may not have a patient match yet.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="triage_sessions",
                        to="emr.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(fields=["status", "-started_at"], name="triage_status_idx"),
                    models.Index(fields=["urgency", "-started_at"], name="triage_urgency_idx"),
                ],
            },
        ),
    ]
