# Generated by Django 5.2 on 2026-04-06 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0009_rename_emr_prescription_patient_status_emr_prescri_patient_d5a4e9_idx_and_more'),
        ('whatsapp', '0002_celery_beat_tasks'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scheduledreminder',
            name='unique_reminder_per_appointment_type',
        ),
        migrations.RenameIndex(
            model_name='conversationsession',
            new_name='whatsapp_co_expires_149b54_idx',
            old_name='whatsapp_co_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='messagelog',
            new_name='whatsapp_me_contact_fa45ff_idx',
            old_name='whatsapp_ml_contact_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduledreminder',
            new_name='whatsapp_sc_status_a4f53c_idx',
            old_name='whatsapp_sr_status_idx',
        ),
        migrations.AlterUniqueTogether(
            name='scheduledreminder',
            unique_together={('appointment', 'reminder_type')},
        ),
    ]
