# Generated by Django 5.2 on 2026-03-28 07:08

import uuid

import django.db.models.deletion
import django_tenants.postgresql_backend.base
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço base (R$)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Plano",
                "verbose_name_plural": "Planos",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="admin, medico, enfermeiro, recepcionista, farmaceutico",
                        max_length=50,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        default=list,
                        help_text='["emr.read", "emr.write", "billing.read", "pharmacy.dispense"]',
                        verbose_name="Permissões",
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="Roles de sistema não podem ser excluídas.",
                        verbose_name="Role de sistema",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[django_tenants.postgresql_backend.base._check_schema_name],
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome da clínica")),
                ("slug", models.SlugField(max_length=100, unique=True, verbose_name="Slug")),
                (
                    "cnpj",
                    models.CharField(
                        blank=True, max_length=18, null=True, unique=True, verbose_name="CNPJ"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("active", "Ativo"),
                            ("suspended", "Suspenso"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="trial",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "trial_ends_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Fim do trial"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="E-mail")),
                ("full_name", models.CharField(max_length=255, verbose_name="Nome completo")),
                (
                    "cpf",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True,
                        help_text="Armazenado criptografado (LGPD).",
                        null=True,
                        verbose_name="CPF",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("is_staff", models.BooleanField(default=False, verbose_name="Staff")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="Último acesso"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="core.role",
                        verbose_name="Role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "active_modules",
                    models.JSONField(
                        default=list,
                        help_text='["emr", "billing", "pharmacy", "ai_tuss", "whatsapp"]',
                        verbose_name="Módulos ativos",
                    ),
                ),
                (
                    "monthly_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Mensalidade (R$)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Ativo"),
                            ("past_due", "Em atraso"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("current_period_start", models.DateField(verbose_name="Início do período")),
                ("current_period_end", models.DateField(verbose_name="Fim do período")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="core.plan",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assinatura",
                "verbose_name_plural": "Assinaturas",
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("domain", models.CharField(db_index=True, max_length=253, unique=True)),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Domínio",
                "verbose_name_plural": "Domínios",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        help_text="create, update, delete, login, view_record",
                        max_length=50,
                        verbose_name="Ação",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        help_text="patient, prescription, encounter",
                        max_length=50,
                        verbose_name="Tipo de recurso",
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(blank=True, max_length=36, verbose_name="ID do recurso"),
                ),
                (
                    "old_data",
                    models.JSONField(blank=True, null=True, verbose_name="Dados anteriores"),
                ),
                ("new_data", models.JSONField(blank=True, null=True, verbose_name="Dados novos")),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True, verbose_name="IP"),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="core_auditl_resourc_a674ad_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"], name="core_auditl_user_id_413764_idx"
                    ),
                    models.Index(fields=["created_at"], name="core_auditl_created_dc23ea_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PlanModule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "module_key",
                    models.CharField(
                        help_text="emr, billing, pharmacy, ai_tuss, whatsapp",
                        max_length=50,
                        verbose_name="Módulo",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço adicional (R$)"
                    ),
                ),
                (
                    "is_included",
                    models.BooleanField(default=False, verbose_name="Incluso no plano base"),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="core.plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Módulo do Plano",
                "verbose_name_plural": "Módulos do Plano",
                "unique_together": {("plan", "module_key")},
            },
        ),
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "module_key",
                    models.CharField(
                        help_text="emr, billing, pharmacy, ai_tuss, whatsapp, ai_scribe",
                        max_length=50,
                        verbose_name="Módulo/Feature",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False, verbose_name="Habilitado")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_flags",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Flag",
                "verbose_name_plural": "Feature Flags",
                "unique_together": {("tenant", "module_key")},
            },
        ),
    ]
