# Generated by Django 5.2 on 2026-04-06

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_cid10code"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIDPAStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("dpa_signed_date", models.DateField(blank=True, null=True)),
                ("dpa_file_url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_dpa_status",
                        to="core.tenant",
                    ),
                ),
                (
                    "signed_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI DPA Status",
                "verbose_name_plural": "AI DPA Statuses",
                "app_label": "core",
            },
        ),
    ]
