# Generated by Django 5.2 on 2026-04-06

import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_aidpastatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOTPDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_secret', encrypted_model_fields.fields.EncryptedCharField(max_length=200)),
                ('encrypted_backup_codes', encrypted_model_fields.fields.EncryptedCharField(default='[]', max_length=2000)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='totp_device',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'verbose_name': 'TOTP Device',
                'verbose_name_plural': 'TOTP Devices',
                'app_label': 'core',
            },
        ),
    ]
