# Generated by Django 5.2 on 2026-04-26
#
# State-only fix: Django's auto-detector wanted to rename the GinIndex on
# CID10Code.search_vector from "core_cid10c_search__idx" to
# "core_cid10c_search__ae47b7_gin". Inspection of the live DB shows the index
# already has the target name (the original migration created it that way),
# so the SQL rename would error with "relation does not exist". This migration
# updates Django's migration state only — no DB-side operation. Concurrent-safe
# (no lock, no rewrite). Reversible (state_operations is symmetric).
# Kept in its own migration to preserve bisectability of the S-076-NEW
# auth changes that follow.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_totpdevice"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name="cid10code",
                    new_name="core_cid10c_search__ae47b7_gin",
                    old_name="core_cid10c_search__idx",
                ),
            ],
        ),
    ]
