# Generated by Django 5.2 on 2026-04-26
#
# S-076-NEW: User.must_change_password — gated by PasswordChangeRequiredMiddleware
# (T5). Default False so existing rows are unaffected — concurrent-safe (no
# NOT NULL violation, no table rewrite for boolean default).

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_rename_cid10code_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(
                default=False,
                verbose_name="Senha temporária — exige alteração no primeiro login",
            ),
        ),
    ]
