# Generated by Django 5.2 on 2026-04-26 23:34

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_add_user_must_change_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        db_index=True, max_length=64, unique=True, verbose_name="Hash do token"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expira em")),
                (
                    "consumed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Consumido em"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitations_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Convite de usuário",
                "verbose_name_plural": "Convites de usuário",
                "ordering": ["-created_at"],
            },
        ),
    ]
