# Generated by Django 5.2 on 2026-06-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_user_preferred_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="tusscode",
            name="age_max_days",
            field=models.IntegerField(
                blank=True,
                help_text="Idade máxima do paciente para o procedimento, em dias. Null = sem limite superior. Fonte: ANS.",
                null=True,
                verbose_name="Idade máxima (dias)",
            ),
        ),
        migrations.AddField(
            model_name="tusscode",
            name="age_min_days",
            field=models.IntegerField(
                blank=True,
                help_text="Idade mínima do paciente para o procedimento, em dias. Null = sem limite inferior. Fonte: ANS.",
                null=True,
                verbose_name="Idade mínima (dias)",
            ),
        ),
        migrations.AddField(
            model_name="tusscode",
            name="cid10_whitelist",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de códigos CID-10 compatíveis com o procedimento. Lista vazia = sem restrição de CID. Fonte: ANS.",
                verbose_name="CIDs compatíveis (whitelist)",
            ),
        ),
        migrations.AddField(
            model_name="tusscode",
            name="sex_allowed",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Feminino"), ("B", "Ambos/Qualquer")],
                default="B",
                help_text="Sexo do paciente compatível com o procedimento (B = ambos, sem restrição). Fonte: ANS.",
                max_length=1,
                verbose_name="Sexo permitido",
            ),
        ),
    ]
