# Generated by Django 5.2 on 2026-06-05 13:24

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_tusscode_age_max_days_tusscode_age_min_days_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTenantMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memberships",
                        to="core.role",
                        verbose_name="Role (reservado p/ M2)",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_memberships",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vínculo usuário-tenant",
                "verbose_name_plural": "Vínculos usuário-tenant",
                "indexes": [
                    models.Index(
                        fields=["user", "tenant", "is_active"],
                        name="core_userte_user_id_e2ea16_idx",
                    )
                ],
                "unique_together": {("user", "tenant")},
            },
        ),
    ]
