# Generated by Django 5.2 on 2026-06-06 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_usertenantmembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinvitation",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Clínica do convite; null = convite legado anterior ao Model B.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="core.tenant",
                verbose_name="Tenant",
            ),
        ),
    ]
