# Generated by Django 5.2 on 2026-06-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_userinvitation_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="schema_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Tenant que originou o evento; carimbado de connection no save. Vazio = linha anterior à coluna (não atribuível).",
                max_length=63,
                verbose_name="Schema do tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["schema_name", "created_at"], name="core_auditlog_schema_idx"
            ),
        ),
    ]
