# Generated by Django 5.2 on 2026-07-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_cid10_rich"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnvisaProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=32, verbose_name="Código")),
                ("display", models.CharField(max_length=500, verbose_name="Descrição")),
                (
                    "version",
                    models.CharField(blank=True, default="", max_length=32, verbose_name="Versão"),
                ),
                ("active", models.BooleanField(db_index=True, default=True, verbose_name="Ativo")),
                (
                    "normalized_display",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="display sem acentos e em minúsculas — mantido em sincronia no save().",
                        max_length=500,
                        verbose_name="Descrição normalizada",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        db_index=True,
                        default="anvisa",
                        help_text="Identificador do sistema de terminologia (sempre 'anvisa' aqui).",
                        max_length=32,
                        verbose_name="Sistema/terminologia",
                    ),
                ),
                (
                    "dcb",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Denominação Comum Brasileira do princípio ativo (ex.: 'Amoxicilina').",
                        max_length=200,
                        verbose_name="DCB",
                    ),
                ),
                (
                    "presentation",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Apresentação comercial (ex.: '500 MG COM REV CT BL AL PLAS INC X 21').",
                        max_length=500,
                        verbose_name="Apresentação",
                    ),
                ),
                (
                    "ean",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Código de barras GTIN/EAN — usado para casar linhas de NF-e ao produto.",
                        max_length=14,
                        verbose_name="EAN",
                    ),
                ),
                (
                    "therapeutic_class",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Classe terapêutica ANVISA (ex.: 'ANTIBACTERIANOS').",
                        max_length=200,
                        verbose_name="Classe terapêutica",
                    ),
                ),
                (
                    "controlled_class",
                    models.CharField(
                        choices=[
                            ("none", "Não controlado"),
                            ("A1", "Lista A1 — Entorpecentes"),
                            ("A2", "Lista A2 — Entorpecentes especiais"),
                            ("A3", "Lista A3 — Entorpecentes sujeitos a controle especial"),
                            ("B1", "Lista B1 — Psicotrópicos"),
                            ("B2", "Lista B2 — Psicotrópicos retinóides/anorexígenos"),
                            ("C1", "Lista C1 — Outras substâncias sujeitas a controle"),
                            ("C2", "Lista C2 — Retinóides de uso sistêmico"),
                            ("C3", "Lista C3 — Imunossupressores"),
                            ("C4", "Lista C4 — Antirretrovirais"),
                            ("C5", "Lista C5 — Anabolizantes"),
                        ],
                        db_index=True,
                        default="none",
                        help_text="Lista de controle da Portaria 344/98 ('none' = sem tarja).",
                        max_length=5,
                        verbose_name="Lista/tarja (Portaria 344)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto ANVISA",
                "verbose_name_plural": "Produtos ANVISA",
                "ordering": ["display"],
                "indexes": [
                    models.Index(fields=["ean"], name="anvisa_ean_idx"),
                    models.Index(fields=["dcb"], name="anvisa_dcb_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("system", "code", "version"), name="uniq_anvisa_product_natural_key"
                    )
                ],
            },
        ),
    ]
