# Generated by Django 5.2 on 2026-07-24 17:22

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_anvisaproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="tusscode",
            name="table_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Número da tabela TUSS de origem (ex.: '22'). Null = não informado.",
                max_length=8,
                null=True,
                verbose_name="Número da tabela TUSS",
            ),
        ),
        migrations.CreateModel(
            name="CBHPMItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=32, verbose_name="Código")),
                ("display", models.CharField(max_length=500, verbose_name="Descrição")),
                (
                    "version",
                    models.CharField(blank=True, default="", max_length=32, verbose_name="Versão"),
                ),
                ("active", models.BooleanField(db_index=True, default=True, verbose_name="Ativo")),
                (
                    "normalized_display",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="display sem acentos e em minúsculas — mantido em sincronia no save().",
                        max_length=500,
                        verbose_name="Descrição normalizada",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        db_index=True,
                        default="cbhpm",
                        help_text="Identificador do sistema de terminologia (sempre 'cbhpm' aqui).",
                        max_length=32,
                        verbose_name="Sistema/terminologia",
                    ),
                ),
                (
                    "porte",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="Valor numérico do porte (quantidade de CH) — multiplicador da valoração.",
                        max_digits=10,
                        verbose_name="Porte (valor numérico em CH)",
                    ),
                ),
                (
                    "valor_ch",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        help_text="Valor monetário do CH (coeficiente de honorários) / UCO.",
                        max_digits=12,
                        verbose_name="Valor CH/UCO",
                    ),
                ),
                (
                    "porte_anestesico",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Porte anestésico do procedimento (código, ex.: '3'). Vazio = não informado.",
                        max_length=8,
                        verbose_name="Porte anestésico",
                    ),
                ),
                (
                    "numero_filme",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="Quantidade de filme radiológico associada ao procedimento.",
                        max_digits=10,
                        verbose_name="Número de filme",
                    ),
                ),
                (
                    "numero_auxiliares",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Número de auxiliares previstos para o procedimento.",
                        verbose_name="Número de auxiliares",
                    ),
                ),
                (
                    "vigencia",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Rótulo da competência/vigência da tabela (ex.: '2024').",
                        max_length=32,
                        verbose_name="Vigência",
                    ),
                ),
                (
                    "tuss",
                    models.ForeignKey(
                        blank=True,
                        help_text="Procedimento TUSS correspondente a este porte CBHPM (opcional).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cbhpm_items",
                        to="core.tusscode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item CBHPM",
                "verbose_name_plural": "Itens CBHPM",
                "ordering": ["code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("system", "code", "version"), name="uniq_cbhpm_item_natural_key"
                    )
                ],
            },
        ),
    ]
