# Generated by Django 5.2 on 2026-07-26 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_tusscode_table_number_cbhpmitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBOCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, verbose_name='Código')),
                ('display', models.CharField(max_length=500, verbose_name='Descrição')),
                ('version', models.CharField(blank=True, default='', max_length=32, verbose_name='Versão')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('normalized_display', models.CharField(blank=True, db_index=True, default='', help_text='display sem acentos e em minúsculas — mantido em sincronia no save().', max_length=500, verbose_name='Descrição normalizada')),
                ('system', models.CharField(db_index=True, default='cbo', help_text="Identificador do sistema de terminologia (sempre 'cbo' aqui).", max_length=32, verbose_name='Sistema/terminologia')),
                ('family', models.CharField(blank=True, db_index=True, default='', help_text="Código da família ocupacional CBO (ex.: '2251' — Médicos clínicos).", max_length=16, verbose_name='Família ocupacional')),
            ],
            options={
                'verbose_name': 'Ocupação CBO',
                'verbose_name_plural': 'Ocupações CBO',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['family'], name='cbo_family_idx')],
                'constraints': [models.UniqueConstraint(fields=('system', 'code', 'version'), name='uniq_cbo_code_natural_key')],
            },
        ),
    ]
