# Generated by Django 5.2 on 2026-07-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_cbocode"),
    ]

    operations = [
        migrations.CreateModel(
            name="CNESEstablishment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=32, verbose_name="Código")),
                ("display", models.CharField(max_length=500, verbose_name="Descrição")),
                (
                    "version",
                    models.CharField(blank=True, default="", max_length=32, verbose_name="Versão"),
                ),
                ("active", models.BooleanField(db_index=True, default=True, verbose_name="Ativo")),
                (
                    "normalized_display",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="display sem acentos e em minúsculas — mantido em sincronia no save().",
                        max_length=500,
                        verbose_name="Descrição normalizada",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        db_index=True,
                        default="cnes",
                        help_text="Identificador do sistema de terminologia (sempre 'cnes' aqui).",
                        max_length=32,
                        verbose_name="Sistema/terminologia",
                    ),
                ),
                (
                    "establishment_type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Tipo/natureza do estabelecimento (ex.: 'HOSPITAL GERAL', 'CLINICA').",
                        max_length=120,
                        verbose_name="Tipo de estabelecimento",
                    ),
                ),
                (
                    "municipality_ibge",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Código IBGE (7 dígitos) do município do estabelecimento.",
                        max_length=7,
                        verbose_name="Município (IBGE)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estabelecimento CNES",
                "verbose_name_plural": "Estabelecimentos CNES",
                "ordering": ["code"],
                "indexes": [
                    models.Index(fields=["municipality_ibge"], name="cnes_municipality_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("system", "code", "version"),
                        name="uniq_cnes_establishment_natural_key",
                    )
                ],
            },
        ),
    ]
