# Generated by Django 5.2 on 2026-07-26 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_cnesestablishment"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoincCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=32, verbose_name="Código")),
                ("display", models.CharField(max_length=500, verbose_name="Descrição")),
                (
                    "version",
                    models.CharField(blank=True, default="", max_length=32, verbose_name="Versão"),
                ),
                ("active", models.BooleanField(db_index=True, default=True, verbose_name="Ativo")),
                (
                    "normalized_display",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="display sem acentos e em minúsculas — mantido em sincronia no save().",
                        max_length=500,
                        verbose_name="Descrição normalizada",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        db_index=True,
                        default="loinc",
                        help_text="Identificador do sistema de terminologia (sempre 'loinc' aqui).",
                        max_length=32,
                        verbose_name="Sistema/terminologia",
                    ),
                ),
                (
                    "component",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Eixo COMPONENT do LOINC — o que é medido (ex.: 'Hemoglobin').",
                        max_length=255,
                        verbose_name="Componente (LOINC)",
                    ),
                ),
                (
                    "property",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Eixo PROPERTY do LOINC — tipo de grandeza (ex.: 'MCnc', 'SCnc').",
                        max_length=64,
                        verbose_name="Propriedade (LOINC)",
                    ),
                ),
                (
                    "loinc_system",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Eixo SYSTEM do LOINC — espécime/sistema (ex.: 'Bld', 'Ser/Plas').",
                        max_length=128,
                        verbose_name="Sistema/espécime (LOINC)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Código LOINC",
                "verbose_name_plural": "Códigos LOINC",
                "ordering": ["code"],
                "indexes": [models.Index(fields=["component"], name="loinc_component_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("system", "code", "version"), name="uniq_loinc_code_natural_key"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UcumUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=32, verbose_name="Código")),
                ("display", models.CharField(max_length=500, verbose_name="Descrição")),
                (
                    "version",
                    models.CharField(blank=True, default="", max_length=32, verbose_name="Versão"),
                ),
                ("active", models.BooleanField(db_index=True, default=True, verbose_name="Ativo")),
                (
                    "normalized_display",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="display sem acentos e em minúsculas — mantido em sincronia no save().",
                        max_length=500,
                        verbose_name="Descrição normalizada",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        db_index=True,
                        default="ucum",
                        help_text="Identificador do sistema de terminologia (sempre 'ucum' aqui).",
                        max_length=32,
                        verbose_name="Sistema/terminologia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidade UCUM",
                "verbose_name_plural": "Unidades UCUM",
                "ordering": ["code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("system", "code", "version"), name="uniq_ucum_unit_natural_key"
                    )
                ],
            },
        ),
    ]
