# Generated by Django 5.2 on 2026-07-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_loinccode_ucumunit"),
    ]

    operations = [
        migrations.CreateModel(
            name="NandaDiagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=32, verbose_name="Código")),
                ("display", models.CharField(max_length=500, verbose_name="Descrição")),
                (
                    "version",
                    models.CharField(blank=True, default="", max_length=32, verbose_name="Versão"),
                ),
                ("active", models.BooleanField(db_index=True, default=True, verbose_name="Ativo")),
                (
                    "normalized_display",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="display sem acentos e em minúsculas — mantido em sincronia no save().",
                        max_length=500,
                        verbose_name="Descrição normalizada",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        db_index=True,
                        default="nanda",
                        help_text="Identificador do sistema de terminologia (sempre 'nanda' aqui).",
                        max_length=32,
                        verbose_name="Sistema/terminologia",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Domínio da Taxonomia II NANDA-I (ex.: '12 Conforto').",
                        max_length=120,
                        verbose_name="Domínio (NANDA-I)",
                    ),
                ),
                (
                    "nanda_class",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Classe da Taxonomia II NANDA-I (ex.: '1 Conforto físico').",
                        max_length=120,
                        verbose_name="Classe (NANDA-I)",
                    ),
                ),
                (
                    "definition",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Definição do diagnóstico de enfermagem.",
                        verbose_name="Definição",
                    ),
                ),
                (
                    "defining_characteristics",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Características definidoras (opcional; texto/lista da fonte).",
                        verbose_name="Características definidoras",
                    ),
                ),
                (
                    "related_factors",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Fatores relacionados / de risco (opcional; texto/lista da fonte).",
                        verbose_name="Fatores relacionados",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diagnóstico NANDA-I",
                "verbose_name_plural": "Diagnósticos NANDA-I",
                "ordering": ["code"],
                "indexes": [models.Index(fields=["domain"], name="nanda_domain_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("system", "code", "version"),
                        name="uniq_nanda_diagnosis_natural_key",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NicIntervention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=32, verbose_name="Código")),
                ("display", models.CharField(max_length=500, verbose_name="Descrição")),
                (
                    "version",
                    models.CharField(blank=True, default="", max_length=32, verbose_name="Versão"),
                ),
                ("active", models.BooleanField(db_index=True, default=True, verbose_name="Ativo")),
                (
                    "normalized_display",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="display sem acentos e em minúsculas — mantido em sincronia no save().",
                        max_length=500,
                        verbose_name="Descrição normalizada",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        db_index=True,
                        default="nic",
                        help_text="Identificador do sistema de terminologia (sempre 'nic' aqui).",
                        max_length=32,
                        verbose_name="Sistema/terminologia",
                    ),
                ),
                (
                    "definition",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Definição da intervenção de enfermagem.",
                        verbose_name="Definição",
                    ),
                ),
                (
                    "activities",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Atividades da intervenção (opcional; texto/lista da fonte).",
                        verbose_name="Atividades",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intervenção NIC",
                "verbose_name_plural": "Intervenções NIC",
                "ordering": ["code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("system", "code", "version"),
                        name="uniq_nic_intervention_natural_key",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NocOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=32, verbose_name="Código")),
                ("display", models.CharField(max_length=500, verbose_name="Descrição")),
                (
                    "version",
                    models.CharField(blank=True, default="", max_length=32, verbose_name="Versão"),
                ),
                ("active", models.BooleanField(db_index=True, default=True, verbose_name="Ativo")),
                (
                    "normalized_display",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="display sem acentos e em minúsculas — mantido em sincronia no save().",
                        max_length=500,
                        verbose_name="Descrição normalizada",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        db_index=True,
                        default="noc",
                        help_text="Identificador do sistema de terminologia (sempre 'noc' aqui).",
                        max_length=32,
                        verbose_name="Sistema/terminologia",
                    ),
                ),
                (
                    "definition",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Definição do resultado de enfermagem.",
                        verbose_name="Definição",
                    ),
                ),
                (
                    "indicators",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Indicadores do resultado (opcional; texto/lista da fonte).",
                        verbose_name="Indicadores",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado NOC",
                "verbose_name_plural": "Resultados NOC",
                "ordering": ["code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("system", "code", "version"), name="uniq_noc_outcome_natural_key"
                    )
                ],
            },
        ),
    ]
