# Generated by Django 5.2 on 2026-07-28 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_bedtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManchesterFlowchart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, verbose_name='Código')),
                ('display', models.CharField(max_length=500, verbose_name='Descrição')),
                ('version', models.CharField(blank=True, default='', max_length=32, verbose_name='Versão')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('normalized_display', models.CharField(blank=True, db_index=True, default='', help_text='display sem acentos e em minúsculas — mantido em sincronia no save().', max_length=500, verbose_name='Descrição normalizada')),
                ('system', models.CharField(db_index=True, default='manchester_flowchart', help_text="Identificador do sistema de terminologia (sempre 'manchester_flowchart' aqui).", max_length=32, verbose_name='Sistema/terminologia')),
            ],
            options={
                'verbose_name': 'Fluxograma Manchester',
                'verbose_name_plural': 'Fluxogramas Manchester',
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('system', 'code', 'version'), name='uniq_manchester_flowchart_natural_key')],
            },
        ),
        migrations.CreateModel(
            name='ManchesterDiscriminator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Código do discriminador (único dentro do fluxograma).', max_length=32, verbose_name='Código')),
                ('name', models.CharField(help_text="Texto do discriminador (ex.: 'Dor pré-cordial').", max_length=255, verbose_name='Discriminador')),
                ('description', models.TextField(blank=True, default='', help_text='Descrição / critério do discriminador (opcional).', verbose_name='Descrição')),
                ('acuity_level', models.CharField(choices=[('vermelho', 'Vermelho (emergência)'), ('laranja', 'Laranja (muito urgente)'), ('amarelo', 'Amarelo (urgente)'), ('verde', 'Verde (pouco urgente)'), ('azul', 'Azul (não urgente)')], db_index=True, help_text='Nível de prioridade Manchester que este discriminador dispara.', max_length=10, verbose_name='Nível de acuidade')),
                ('is_general', models.BooleanField(db_index=True, default=False, help_text='Discriminador geral (aplicável a vários fluxogramas) vs. específico.', verbose_name='Geral')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('flowchart', models.ForeignKey(help_text='Fluxograma de apresentação ao qual este discriminador pertence.', on_delete=django.db.models.deletion.PROTECT, related_name='discriminators', to='core.manchesterflowchart', verbose_name='Fluxograma')),
            ],
            options={
                'verbose_name': 'Discriminador Manchester',
                'verbose_name_plural': 'Discriminadores Manchester',
                'ordering': ['flowchart', 'code'],
                'indexes': [models.Index(fields=['acuity_level'], name='manchester_disc_acuity_idx')],
                'constraints': [models.UniqueConstraint(fields=('flowchart', 'code'), name='uniq_manchester_discriminator_flowchart_code')],
            },
        ),
    ]
