# Generated by Django 5.2 on 2026-07-28 21:00

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_manchesterflowchart_manchesterdiscriminator"),
    ]

    operations = [
        migrations.CreateModel(
            name="SIGTAPProcedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=32, verbose_name="Código")),
                ("display", models.CharField(max_length=500, verbose_name="Descrição")),
                (
                    "version",
                    models.CharField(blank=True, default="", max_length=32, verbose_name="Versão"),
                ),
                ("active", models.BooleanField(db_index=True, default=True, verbose_name="Ativo")),
                (
                    "normalized_display",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="display sem acentos e em minúsculas — mantido em sincronia no save().",
                        max_length=500,
                        verbose_name="Descrição normalizada",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        db_index=True,
                        default="sigtap",
                        help_text="Identificador do sistema de terminologia (sempre 'sigtap' aqui).",
                        max_length=32,
                        verbose_name="Sistema/terminologia",
                    ),
                ),
                (
                    "valor_sa",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Componente de valor do Serviço Ambulatorial (R$).",
                        max_digits=12,
                        verbose_name="Valor Serviço Ambulatorial (SA)",
                    ),
                ),
                (
                    "valor_sh",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Componente de valor do Serviço Hospitalar (R$).",
                        max_digits=12,
                        verbose_name="Valor Serviço Hospitalar (SH)",
                    ),
                ),
                (
                    "valor_sp",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Componente de valor do Serviço Profissional (R$).",
                        max_digits=12,
                        verbose_name="Valor Serviço Profissional (SP)",
                    ),
                ),
                (
                    "competencia_vigencia",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Competência de vigência da tabela SIGTAP no formato 'AAAA-MM'.",
                        max_length=7,
                        verbose_name="Competência de vigência",
                    ),
                ),
                (
                    "instrumento_registro",
                    models.CharField(
                        choices=[
                            ("bpa_c", "BPA Consolidado"),
                            ("bpa_i", "BPA Individualizado"),
                            ("apac", "APAC (Autorização de Procedimento de Alta Complexidade)"),
                            ("aih", "AIH (Autorização de Internação Hospitalar)"),
                            ("outros", "Outros"),
                        ],
                        db_index=True,
                        default="outros",
                        help_text="Instrumento de registro SIGTAP (BPA-C / BPA-I / APAC / AIH / outros).",
                        max_length=10,
                        verbose_name="Instrumento de registro",
                    ),
                ),
                (
                    "complexidade",
                    models.CharField(
                        choices=[
                            ("atencao_basica", "Atenção Básica"),
                            ("media", "Média Complexidade"),
                            ("alta", "Alta Complexidade"),
                            ("nao_se_aplica", "Não se aplica"),
                        ],
                        db_index=True,
                        default="nao_se_aplica",
                        help_text="Nível de complexidade do procedimento (atenção básica / média / alta).",
                        max_length=16,
                        verbose_name="Complexidade",
                    ),
                ),
                (
                    "financiamento",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Fonte de financiamento do procedimento (ex.: 'MAC', 'PAB', 'FAEC').",
                        max_length=120,
                        verbose_name="Fonte de financiamento",
                    ),
                ),
                (
                    "sexo_permitido",
                    models.CharField(
                        choices=[("ambos", "Ambos"), ("M", "Masculino"), ("F", "Feminino")],
                        default="ambos",
                        help_text="Sexo permitido para o procedimento (compat mínima S1).",
                        max_length=8,
                        verbose_name="Sexo permitido",
                    ),
                ),
                (
                    "idade_min_dias",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Idade mínima permitida em dias (nulo = sem restrição).",
                        null=True,
                        verbose_name="Idade mínima (dias)",
                    ),
                ),
                (
                    "idade_max_dias",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Idade máxima permitida em dias (nulo = sem restrição).",
                        null=True,
                        verbose_name="Idade máxima (dias)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Procedimento SIGTAP",
                "verbose_name_plural": "Procedimentos SIGTAP",
                "ordering": ["code"],
                "indexes": [
                    models.Index(fields=["instrumento_registro"], name="sigtap_instrumento_idx"),
                    models.Index(fields=["complexidade"], name="sigtap_complexidade_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("system", "code", "version"),
                        name="uniq_sigtap_procedure_natural_key",
                    )
                ],
            },
        ),
    ]
