# Generated by Django 5.2 on 2026-07-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_sigtapprocedure"),
    ]

    operations = [
        migrations.CreateModel(
            name="BloodComponentCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=32, verbose_name="Código")),
                ("display", models.CharField(max_length=500, verbose_name="Descrição")),
                (
                    "version",
                    models.CharField(blank=True, default="", max_length=32, verbose_name="Versão"),
                ),
                ("active", models.BooleanField(db_index=True, default=True, verbose_name="Ativo")),
                (
                    "normalized_display",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="display sem acentos e em minúsculas — mantido em sincronia no save().",
                        max_length=500,
                        verbose_name="Descrição normalizada",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        db_index=True,
                        default="blood_component",
                        help_text="Identificador do sistema de terminologia (sempre 'blood_component' aqui).",
                        max_length=32,
                        verbose_name="Sistema/terminologia",
                    ),
                ),
                (
                    "default_validade_dias",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Prazo de validade sugerido do hemocomponente em dias (nulo = sem sugestão).",
                        null=True,
                        verbose_name="Validade padrão (dias)",
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Agrupamento do hemocomponente (ex.: 'Hemácias', 'Plasma', 'Plaquetas').",
                        max_length=120,
                        verbose_name="Contexto/grupo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hemocomponente (catálogo)",
                "verbose_name_plural": "Hemocomponentes (catálogo)",
                "ordering": ["code"],
                "indexes": [models.Index(fields=["context"], name="blood_component_context_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("system", "code", "version"),
                        name="uniq_blood_component_natural_key",
                    )
                ],
            },
        ),
    ]
