# Generated by Django 5.2 on 2026-07-29 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_bloodcomponentcatalog"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimproMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=32, verbose_name="Código")),
                ("display", models.CharField(max_length=500, verbose_name="Descrição")),
                (
                    "version",
                    models.CharField(blank=True, default="", max_length=32, verbose_name="Versão"),
                ),
                ("active", models.BooleanField(db_index=True, default=True, verbose_name="Ativo")),
                (
                    "normalized_display",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="display sem acentos e em minúsculas — mantido em sincronia no save().",
                        max_length=500,
                        verbose_name="Descrição normalizada",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        db_index=True,
                        default="simpro",
                        help_text="Identificador do sistema de terminologia (sempre 'simpro' aqui).",
                        max_length=32,
                        verbose_name="Sistema/terminologia",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("material", "Material"),
                            ("opme", "OPME"),
                            ("medicamento", "Medicamento"),
                        ],
                        db_index=True,
                        default="material",
                        help_text="Classe do item Simpro: material, OPME ou medicamento.",
                        max_length=12,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "reference_price",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Preço de referência da edição Simpro para este item.",
                        max_digits=12,
                        verbose_name="Preço de referência (R$)",
                    ),
                ),
                (
                    "edition",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Edição/competência da tabela Simpro (ex.: '2026-07').",
                        max_length=16,
                        verbose_name="Edição/competência",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Unidade de comercialização (ex.: 'UN', 'FR').",
                        max_length=16,
                        verbose_name="Unidade",
                    ),
                ),
                (
                    "tuss_code",
                    models.ForeignKey(
                        blank=True,
                        help_text="Código TUSS TISS do material/medicamento (tabela 20/19). Vazio = sem correspondência.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="simpro_materials",
                        to="core.tusscode",
                        verbose_name="TUSS correspondente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material Simpro (catálogo)",
                "verbose_name_plural": "Materiais Simpro (catálogo)",
                "ordering": ["code"],
                "indexes": [models.Index(fields=["kind"], name="simpro_material_kind_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("system", "code", "version"),
                        name="uniq_simpro_material_natural_key",
                    )
                ],
            },
        ),
    ]
