# Generated by Django 5.2 on 2026-07-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_simpromaterial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CIDOMorphology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=32, verbose_name="Código")),
                ("display", models.CharField(max_length=500, verbose_name="Descrição")),
                (
                    "version",
                    models.CharField(blank=True, default="", max_length=32, verbose_name="Versão"),
                ),
                ("active", models.BooleanField(db_index=True, default=True, verbose_name="Ativo")),
                (
                    "normalized_display",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="display sem acentos e em minúsculas — mantido em sincronia no save().",
                        max_length=500,
                        verbose_name="Descrição normalizada",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        db_index=True,
                        default="cid_o",
                        help_text="Identificador do sistema de terminologia (sempre 'cid_o' aqui).",
                        max_length=32,
                        verbose_name="Sistema/terminologia",
                    ),
                ),
                (
                    "behaviour",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Dígito de comportamento do código CID-O (0 benigno … 3 maligno primário …).",
                        max_length=1,
                        verbose_name="Comportamento",
                    ),
                ),
                (
                    "cid10_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Código CID-10 de topografia correlato (coluna REFER do DATASUS), quando houver.",
                        max_length=10,
                        verbose_name="CID-10 correlato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Morfologia CID-O",
                "verbose_name_plural": "Morfologias CID-O",
                "ordering": ["code"],
                "indexes": [models.Index(fields=["behaviour"], name="cido_behaviour_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("system", "code", "version"),
                        name="uniq_cido_morphology_natural_key",
                    )
                ],
            },
        ),
    ]
