# Generated by Django 5.2 on 2026-07-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_cido_morphology"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cidomorphology",
            name="cid10_ref",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Código(s) CID-10 de topografia correlato(s) — coluna REFER do DATASUS; pode listar mais de um separado por vírgula (ex.: 'C40.-,C41.-').",
                max_length=60,
                verbose_name="CID-10 correlato",
            ),
        ),
    ]
