# Generated by Django 5.2 on 2026-08-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_cido_ref_len"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anvisaproduct",
            name="dcb",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Denominação Comum Brasileira do princípio ativo (ex.: 'Amoxicilina').",
                max_length=500,
                verbose_name="DCB",
            ),
        ),
    ]
