# Generated by Django 5.2 on 2026-08-04 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_anvisa_dcb_500"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnvisaPresentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Registro ANVISA de 13 dígitos (produto + apresentação), como publicado pela CMED.",
                        max_length=20,
                        unique=True,
                        verbose_name="Registro da apresentação",
                    ),
                ),
                (
                    "presentation",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Apresentação comercial (ex.: '500 MG COM REV CT BL AL PLAS INC X 21').",
                        max_length=500,
                        verbose_name="Apresentação",
                    ),
                ),
                (
                    "ean",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Código de barras GTIN/EAN da caixa — casa a linha da NF-e com o catálogo.",
                        max_length=14,
                        verbose_name="EAN",
                    ),
                ),
                (
                    "price_pf",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="PF sem impostos da lista CMED da competência importada. Null = não publicado.",
                        max_digits=12,
                        null=True,
                        verbose_name="Preço de fábrica (sem impostos)",
                    ),
                ),
                (
                    "price_pmc",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="PMC sem impostos da lista CMED da competência importada. Null = não publicado.",
                        max_digits=12,
                        null=True,
                        verbose_name="Preço máximo ao consumidor (sem impostos)",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Competência da lista CMED de origem (ex.: '2026-08').",
                        max_length=20,
                        verbose_name="Versão/competência",
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True, verbose_name="Ativo")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presentations",
                        to="core.anvisaproduct",
                        verbose_name="Produto ANVISA",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apresentação ANVISA",
                "verbose_name_plural": "Apresentações ANVISA",
                "ordering": ["code"],
                "indexes": [models.Index(fields=["ean"], name="anvisa_pres_ean_idx")],
            },
        ),
    ]
