# Generated by Django 5.2 on 2026-08-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_anvisa_presentation"),
    ]

    operations = [
        migrations.AddField(
            model_name="tusscode",
            name="anvisa_registro",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Registro ANVISA do medicamento (tabela TUSS 20). Null = não informado.",
                max_length=20,
                null=True,
                verbose_name="Registro ANVISA",
            ),
        ),
    ]
