# Generated by Django 5.2 on 2026-08-17 00:00
#
# Onda 0 / 0.5: add a nullable tenant discriminator to Role. Role stays in the
# PUBLIC schema (SHARED_APPS) — this is NOT a per-tenant split, just a
# discriminator column: tenant=None means a system role shared by every
# clinic (unchanged meaning of every pre-existing row); tenant=<X> means a
# role clinic X created for itself.
#
# NON-DESTRUCTIVE BY DESIGN: this migration does NOT backfill tenant on any
# existing row. Every Role created before this migration keeps tenant=None,
# i.e. keeps behaving exactly as before (visible/assignable everywhere via
# Role.for_current_tenant()'s `tenant__isnull=True` branch). Attributing
# existing custom (non-system) roles to the tenant that actually created them
# is a separate, deliberate operational backfill (there is no reliable
# "creator tenant" signal on the current Role rows to infer it from safely)
# — NOT part of this migration.
#
# Reversible: RemoveField drops the column; no data loss on rollback since the
# column carries no forward-only invariant (nullable, no unique/check
# constraint depending on it).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_tuss_anvisa_registro"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Clínica dona do papel; null = role de sistema, compartilhada entre clínicas.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="core.tenant",
                verbose_name="Tenant",
            ),
        ),
    ]
