"""
core_auditlog vira tabela particionada (ordem 020).

RANGE(created_at) mensal, sub-particionada LIST(schema_name), com DEFAULT nos
dois níveis — nenhuma linha de auditoria pode ser recusada por falta de
partição (ver apps/core/partitioning.py). A PK passa a ser composta
``(id, created_at, schema_name)``: Postgres exige a chave de partição na PK, e
o Imediato confirmou que nada no backend referencia AuditLog por FK/O2O/M2M
nem busca por ``pk``/``id`` bruto — isolamento por tenant vale mais que
unicidade de ``id`` garantida pelo banco (ver apps/core/models.py:AuditLog).

A tabela antiga vira ``core_auditlog_pre020`` — RENOMEADA, nunca DROPADA.
Fica de pé até o aceite explícito do Imediato; nenhuma etapa aqui a remove.

Plano SQL, nesta ordem (também documentado no relatório da ordem 020):
  1. ALTER TABLE core_auditlog RENAME TO core_auditlog_pre020.
  2. Renomear a PK, os 8 índices e a FK da tabela antiga com sufixo
     ``_pre020`` — liberando os nomes canônicos para a tabela nova (nomes de
     índice/constraint são únicos por schema, não por tabela).
  3. CREATE TABLE core_auditlog (mesmas colunas) PARTITION BY RANGE
     (created_at), PK composta, FK para core_user, os mesmos 8 índices
     (Postgres propaga índice de partitioned table para toda partição,
     presente e futura — não precisam ser recriados por partição).
  4. Partição DEFAULT de nível 1 (RANGE) + sua própria DEFAULT de nível 2
     (LIST) — o catch-all dos dois níveis.
  5. Os 3 triggers BEFORE UPDATE/DELETE/TRUNCATE + REVOKE (mesma função da
     migration 0019; Postgres clona trigger de partitioned table para toda
     partição automaticamente — REVOKE não propaga, por isso também roda
     nas duas DEFAULT e, via apps.core.partitioning, em toda partição criada
     depois).
  6. RunPython apps.core.migration_support.convert(): cria uma partição
     mensal por mês distinto já presente nos dados, copia toda linha
     (OVERRIDING SYSTEM VALUE — preserva o id), CONFERE contagem E conteúdo
     linha a linha (EXCEPT nas duas direções — não só contagem), e avança a
     sequência da IDENTITY para depois do maior id migrado. Levanta
     ConversionError (aborta a migration, nada é commitado) se algo não bater.

Irreversível de propósito: desfazer isto significa decidir o que fazer com
qualquer linha gravada DEPOIS da conversão (a tabela nova continua recebendo
escrita em produção) — não existe reversão automática segura para isso, e
inventar uma seria exatamente o tipo de "escape hatch perigoso" que a ordem
proíbe. Nenhuma operação abaixo tem reverse_sql/reverse_code; Django recusa
`migrate core 0042` a partir daqui com "Migration is not reversible".
"""

import logging

from django.db import migrations, models

from apps.core import migration_support, partitioning

logger = logging.getLogger(__name__)

OLD = migration_support.OLD_TABLE
NEW = migration_support.NEW_TABLE

_RENAME_OLD_TABLE_AWAY = f"""
ALTER TABLE {NEW} RENAME TO {OLD};
ALTER TABLE {OLD} RENAME CONSTRAINT core_auditlog_pkey TO core_auditlog_pre020_pkey;
ALTER INDEX core_auditl_created_dc23ea_idx RENAME TO core_auditl_created_dc23ea_idx_pre020;
ALTER INDEX core_auditl_resourc_a674ad_idx RENAME TO core_auditl_resourc_a674ad_idx_pre020;
ALTER INDEX core_auditl_user_id_413764_idx RENAME TO core_auditl_user_id_413764_idx_pre020;
ALTER INDEX core_auditlog_act_created_idx RENAME TO core_auditlog_act_created_idx_pre020;
ALTER INDEX core_auditlog_schema_idx RENAME TO core_auditlog_schema_idx_pre020;
ALTER INDEX core_auditlog_schema_name_a71333aa RENAME TO core_auditlog_schema_name_a71333aa_pre020;
ALTER INDEX core_auditlog_schema_name_a71333aa_like RENAME TO core_auditlog_schema_name_a71333aa_like_pre020;
ALTER INDEX core_auditlog_user_id_3797aaab RENAME TO core_auditlog_user_id_3797aaab_pre020;
ALTER TABLE {OLD} RENAME CONSTRAINT core_auditlog_user_id_3797aaab_fk_core_user_id
    TO core_auditlog_user_id_3797aaab_fk_core_user_id_pre020;
"""

_CREATE_NEW_PARTITIONED_TABLE = f"""
CREATE TABLE {NEW} (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    action varchar(50) NOT NULL,
    resource_type varchar(50) NOT NULL,
    resource_id varchar(36) NOT NULL DEFAULT '',
    old_data jsonb NULL,
    new_data jsonb NULL,
    ip_address inet NULL,
    user_agent text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL,
    user_id uuid NULL,
    schema_name varchar(63) NOT NULL DEFAULT '',
    CONSTRAINT core_auditlog_pkey PRIMARY KEY (id, created_at, schema_name)
) PARTITION BY RANGE (created_at);

ALTER TABLE {NEW}
    ADD CONSTRAINT core_auditlog_user_id_3797aaab_fk_core_user_id
    FOREIGN KEY (user_id) REFERENCES core_user(id) DEFERRABLE INITIALLY DEFERRED;

-- Propagates automatically to every partition, present and future.
CREATE INDEX core_auditl_created_dc23ea_idx ON {NEW} (created_at);
CREATE INDEX core_auditl_resourc_a674ad_idx ON {NEW} (resource_type, resource_id);
CREATE INDEX core_auditl_user_id_413764_idx ON {NEW} (user_id, created_at);
CREATE INDEX core_auditlog_act_created_idx ON {NEW} (action, created_at);
CREATE INDEX core_auditlog_schema_idx ON {NEW} (schema_name, created_at);
CREATE INDEX core_auditlog_schema_name_a71333aa ON {NEW} (schema_name);
CREATE INDEX core_auditlog_schema_name_a71333aa_like ON {NEW} (schema_name varchar_pattern_ops);
CREATE INDEX core_auditlog_user_id_3797aaab ON {NEW} (user_id);

CREATE TABLE {NEW}_default PARTITION OF {NEW} DEFAULT PARTITION BY LIST (schema_name);
CREATE TABLE {NEW}_default_default PARTITION OF {NEW}_default DEFAULT;

CREATE TRIGGER core_auditlog_no_update BEFORE UPDATE ON {NEW}
    FOR EACH ROW EXECUTE FUNCTION core_auditlog_block_mutation();
CREATE TRIGGER core_auditlog_no_delete BEFORE DELETE ON {NEW}
    FOR EACH ROW EXECUTE FUNCTION core_auditlog_block_mutation();
CREATE TRIGGER core_auditlog_no_truncate BEFORE TRUNCATE ON {NEW}
    FOR EACH STATEMENT EXECUTE FUNCTION core_auditlog_block_mutation();

-- Defense-in-depth (mirrors migration 0019); does not propagate to
-- partitions on its own (verified empirically — see order-020 report), so
-- the two DEFAULT partitions get it explicitly too. Every partition created
-- afterwards via apps.core.partitioning gets it from that module instead.
REVOKE UPDATE, DELETE, TRUNCATE ON {NEW} FROM PUBLIC;
REVOKE UPDATE, DELETE, TRUNCATE ON {NEW}_default FROM PUBLIC;
REVOKE UPDATE, DELETE, TRUNCATE ON {NEW}_default_default FROM PUBLIC;
"""


def _convert_data(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        report = migration_support.convert(cursor)
    logger.info(
        "0043_auditlog_partitioned: converted %s row(s); month partitions touched: %s",
        report["row_count"],
        report["months_created"],
    )


def _ensure_default_partitions_exist(apps, schema_editor):
    # Belt-and-suspenders: the SQL above already creates these. Routing
    # creation through the same idempotent helper the retention command uses
    # means there is exactly one code path that knows how to build a DEFAULT
    # partition pair, and running it twice is a no-op, not an error.
    with schema_editor.connection.cursor() as cursor:
        partitioning.ensure_default_partitions(cur=cursor)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_cbhpm_porte_codigo"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql=_RENAME_OLD_TABLE_AWAY),
                migrations.RunSQL(sql=_CREATE_NEW_PARTITIONED_TABLE),
                migrations.RunPython(_ensure_default_partitions_exist),
                migrations.RunPython(_convert_data),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="auditlog",
                    name="id",
                    field=models.BigIntegerField(
                        editable=False,
                        db_default=0,
                        verbose_name="ID",
                    ),
                ),
                migrations.AddField(
                    model_name="auditlog",
                    name="pk",
                    # serialize=False explicitly: Options.setup_pk() mutates
                    # this onto whatever field becomes _meta.pk when a model
                    # class is actually built (contribute_to_class), but a
                    # bare field instance sitting in migration state never
                    # goes through that — without it, `makemigrations --check`
                    # sees a spurious diff against apps/core/models.py forever.
                    # (ignore[attr-defined] below: django-stubs 5.1 predates
                    # Django 5.2's CompositePrimaryKey; see models.py:AuditLog.)
                    field=models.CompositePrimaryKey(  # type: ignore[attr-defined]
                        "id", "created_at", "schema_name", serialize=False
                    ),
                ),
            ],
        ),
    ]
