# Generated by Django 5.2 on 2026-09-22 09:03

"""
TenantAuditRetention (ordem 021).

Retenção de core_auditlog por tenant: ``retention_months`` (default 240 = 20
anos, decisão do Capitão de 22/09/2026 — docs/adr/ADR-0001-retencao-auditoria
-20-anos.md) e ``purge_enabled`` (default False). Mesmo padrão de
TenantAIConfig: OneToOne com core.Tenant, PUBLIC schema (SHARED_APPS).

Sem dado a migrar — o expurgo nunca rodou em ambiente nenhum. Um tenant sem
linha aqui é resolvido pelo próprio default destes campos (ver
apps.core.management.commands.purge_audit_logs._resolve_retention), nunca por
uma ausência tratada como "pode expurgar".
"""

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_auditlog_partitioned"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantAuditRetention",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "retention_months",
                    models.PositiveIntegerField(
                        default=240,
                        help_text=(
                            "240 meses (20 anos) é o piso legal (Res. CFM 1.821/2007 art. 8; "
                            "Lei 13.787/2018 art. 6). Reduzir exige justificativa fora desta "
                            "configuração — este campo não valida contra a lei."
                        ),
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Retenção (meses)",
                    ),
                ),
                (
                    "purge_enabled",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "Desligado de fábrica. Ligar é ato deliberado por tenant — o "
                            "expurgo real ainda exige recibo de exportação fria verificado "
                            "(apps.core.cold_storage) por partição; esta chave só autoriza a "
                            "tentativa."
                        ),
                        verbose_name="Expurgo ativado",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_retention",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Retenção de Auditoria por Tenant",
                "verbose_name_plural": "Retenções de Auditoria por Tenant",
            },
        ),
    ]
