'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import { PageShell, SectionState } from '@/components/shared'
import { apiFetch } from '@/lib/api'
import { apiErrorMessage, listResults } from '@/lib/admin'

type Entry = { id: string; kind?: 'revenue' | 'expense'; amount?: number | string; competency?: string; unit?: string; cost_center?: string; category_name?: string; description?: string; reconciled?: boolean }
const money = (v: number) => v.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })

export default function FinancialResultPage() {
  const now = new Date(); const [period, setPeriod] = useState(`${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`)
  const [unit, setUnit] = useState(''); const [costCenter, setCostCenter] = useState(''); const [entries, setEntries] = useState<Entry[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null)
  const load = useCallback(async () => { setLoading(true); setError(null); try { const qs = new URLSearchParams({ page_size: '500' }); if (period) { const [y, m] = period.split('-'); qs.set('start', `${y}-${m}-01`); qs.set('end', `${y}-${m}-${new Date(Number(y), Number(m), 0).getDate()}`) }; if (unit) qs.set('unit', unit); if (costCenter) qs.set('cost_center', costCenter); const response = await apiFetch<unknown>(`/api/v1/billing/accounting-entries/?${qs}`); setEntries(listResults(response as never) as Entry[]) } catch (e) { setError(apiErrorMessage(e, 'Não foi possível carregar o resultado financeiro.')) } finally { setLoading(false) } }, [period, unit, costCenter])
  useEffect(() => { void load() }, [load])
  const totals = useMemo(() => entries.reduce((a, e) => { const value = Number(e.amount ?? 0); if (e.kind === 'expense') a.expense += value; else a.revenue += value; return a }, { revenue: 0, expense: 0 }), [entries])
  const categories = useMemo(() => Object.entries(entries.reduce<Record<string, number>>((a, e) => { const key = e.category_name || (e.kind === 'expense' ? 'Despesas gerais' : 'Receitas'); a[key] = (a[key] || 0) + Number(e.amount ?? 0); return a }, {})).sort((a, b) => b[1] - a[1]), [entries])
  return <PageShell variant="operational"><div><h1 className="text-2xl font-semibold text-neu-ink">DRE e fluxo de caixa</h1><p className="mt-1 text-sm text-neu-inkSoft">Resultado por competência, unidade e centro de custo.</p></div>
    <section className="flex flex-wrap items-end gap-3 rounded-xl border border-white bg-neu-panel p-4 shadow-neu-panel"><label className="text-sm text-neu-inkSoft">Competência<input aria-label="Competência" type="month" className="neu-input mt-1 block" value={period} onChange={e => setPeriod(e.target.value)} /></label><label className="text-sm text-neu-inkSoft">Unidade<input aria-label="Unidade" className="neu-input mt-1 block" placeholder="Todas" value={unit} onChange={e => setUnit(e.target.value)} /></label><label className="text-sm text-neu-inkSoft">Centro de custo<input aria-label="Centro de custo" className="neu-input mt-1 block" placeholder="Todos" value={costCenter} onChange={e => setCostCenter(e.target.value)} /></label><button className="neu-button-secondary" onClick={() => void load()}>Atualizar</button></section>
    {error && <SectionState title="Resultado indisponível" detail={error} tone="critical" />}
    <div className="grid gap-3 sm:grid-cols-4"><Kpi label="Receitas" value={money(totals.revenue)} tone="success" /><Kpi label="Despesas" value={money(totals.expense)} tone="critical" /><Kpi label="Resultado" value={money(totals.revenue - totals.expense)} tone={totals.revenue >= totals.expense ? 'success' : 'critical'} /><Kpi label="Lançamentos" value={String(entries.length)} /></div>
    <div className="grid gap-4 lg:grid-cols-2"><section className="rounded-xl border border-white bg-neu-panel p-4 shadow-neu-panel"><h2 className="font-semibold text-neu-ink">Composição por categoria</h2>{loading ? <p className="mt-4 text-sm text-neu-inkMuted">Carregando…</p> : categories.length === 0 ? <SectionState title="Nenhum lançamento" detail="Registre receitas e despesas para visualizar o DRE." /> : <ul className="mt-3 divide-y divide-neu-app">{categories.map(([name, value]) => <li key={name} className="flex justify-between py-3 text-sm"><span>{name}</span><strong>{money(value)}</strong></li>)}</ul>}</section>
      <section className="rounded-xl border border-white bg-neu-panel p-4 shadow-neu-panel"><h2 className="font-semibold text-neu-ink">Lançamentos recentes</h2>{!loading && entries.length === 0 ? <SectionState title="Sem lançamentos no período" detail="Nenhuma receita ou despesa foi registrada neste período." /> : <div className="mt-3 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-neu-app text-left text-xs uppercase tracking-wide text-neu-inkMuted"><th className="px-2 py-2">Descrição</th><th className="px-2 py-2">Tipo</th><th className="px-2 py-2 text-right">Valor</th></tr></thead><tbody>{entries.slice(0, 20).map(e => <tr key={e.id} className="border-b border-neu-app/60"><td className="px-2 py-2">{e.description || e.category_name || 'Lançamento'}</td><td className="px-2 py-2">{e.kind === 'expense' ? 'Despesa' : 'Receita'}</td><td className={`px-2 py-2 text-right font-medium ${e.kind === 'expense' ? 'text-rose-700' : 'text-emerald-700'}`}>{money(Number(e.amount ?? 0))}</td></tr>)}</tbody></table></div>}</section></div>
  </PageShell>
}
function Kpi({ label, value, tone }: { label: string; value: string; tone?: string }) { return <div className="rounded-xl border border-white bg-neu-panel p-4 shadow-neu-panel"><p className="text-xs uppercase tracking-wide text-neu-inkMuted">{label}</p><p className={`mt-1 text-xl font-semibold ${tone === 'critical' ? 'text-rose-600' : tone === 'success' ? 'text-emerald-600' : 'text-neu-ink'}`}>{value}</p></div> }
