# Generated by Django 5.2 on 2026-03-31 08:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIPromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('system_prompt', models.TextField()),
                ('user_prompt_template', models.TextField(help_text='Use {description}, {guide_type}, {candidates} as placeholders.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', '-version'],
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('llm_call', 'LLM Call'), ('zero_result', 'Zero Result (retrieval returned 0 candidates)'), ('validation_dropout', 'Validation Dropout (all suggestions invalid)'), ('degraded', 'Degraded (AI unavailable)'), ('cache_hit', 'Cache Hit')], default='llm_call', max_length=30)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('model', models.CharField(default='claude-haiku-4-5-20251001', max_length=100)),
                ('input_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai.aiprompttemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TUSSAISuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tuss_code', models.CharField(db_index=True, max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('rank', models.PositiveSmallIntegerField(help_text='1 = most relevant')),
                ('input_text', models.CharField(max_length=500)),
                ('guide_type', models.CharField(blank=True, max_length=50)),
                ('accepted', models.BooleanField(blank=True, help_text='None = no feedback yet', null=True)),
                ('feedback_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usage_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='ai.aiusagelog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aiusagelog',
            index=models.Index(fields=['event_type', 'created_at'], name='ai_aiusagel_event_t_c3212f_idx'),
        ),
        migrations.AddIndex(
            model_name='aiusagelog',
            index=models.Index(fields=['created_at'], name='ai_aiusagel_created_7d1979_idx'),
        ),
        migrations.AddIndex(
            model_name='tussaisuggestion',
            index=models.Index(fields=['tuss_code', 'created_at'], name='ai_tussaisu_tuss_co_10429b_idx'),
        ),
        migrations.AddIndex(
            model_name='tussaisuggestion',
            index=models.Index(fields=['accepted', 'created_at'], name='ai_tussaisu_accepte_855568_idx'),
        ),
    ]
