# Generated by Django 5.2 on 2026-03-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiprompttemplate",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="aiprompttemplate",
            unique_together={("name", "version")},
        ),
    ]
