# Generated by Django 5.2 on 2026-05-04 23:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0008_scribe_purge_beat_schedule"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="aiscribesession",
            new_name="ai_aiscribe_encount_f856b2_idx",
            old_name="ai_scribe_encounter_status_idx",
        ),
        migrations.RenameIndex(
            model_name="aiscribesession",
            new_name="ai_aiscribe_encount_81edc1_idx",
            old_name="ai_scribe_encounter_created_idx",
        ),
    ]
