# Generated by Django 5.2 on 2026-03-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tissbatch',
            name='retorno_xml_file',
            field=models.CharField(blank=True, help_text='Path to the raw retorno XML from the insurer — stored for audit trail.', max_length=500, verbose_name='Retorno XML (path)'),
        ),
    ]
