# Generated by Django 5.2 on 2026-03-30 01:15

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0003_encounter_soapnote_vitalsigns_clinicaldocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_ans_code', models.CharField(max_length=20)),
                ('provider_name', models.CharField(max_length=200)),
                ('card_number', encrypted_model_fields.fields.EncryptedCharField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Convênio do Paciente',
                'verbose_name_plural': 'Convênios dos Pacientes',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='emr_appoint_profess_df1efd_idx',
            old_name='emr_appoint_profess_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='emr_appoint_patient_cf8e5f_idx',
            old_name='emr_appoint_patient_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='emr_appoint_status_8a281c_idx',
            old_name='emr_appoint_status_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='emr_appoint_start_t_02b84b_idx',
            old_name='emr_appoint_start_end_idx',
        ),
        migrations.RenameIndex(
            model_name='encounter',
            new_name='emr_encount_patient_ac4b30_idx',
            old_name='emr_enc_pat_date_idx',
        ),
        migrations.RenameIndex(
            model_name='encounter',
            new_name='emr_encount_profess_75ac45_idx',
            old_name='emr_enc_pro_date_idx',
        ),
        migrations.RenameIndex(
            model_name='encounter',
            new_name='emr_encount_status_1f09bb_idx',
            old_name='emr_enc_sta_date_idx',
        ),
        migrations.RenameIndex(
            model_name='patient',
            new_name='emr_patient_full_na_cf5707_idx',
            old_name='emr_patient_full_name_idx',
        ),
        migrations.RenameIndex(
            model_name='patient',
            new_name='emr_patient_medical_a5b9a0_idx',
            old_name='emr_patient_mrn_idx',
        ),
        migrations.RenameIndex(
            model_name='patient',
            new_name='emr_patient_is_acti_ef4c69_idx',
            old_name='emr_patient_active_name_idx',
        ),
        migrations.AlterField(
            model_name='allergy',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='professional',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scheduleconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['whatsapp'], name='emr_patient_whatsap_a60e44_idx'),
        ),
        migrations.AddField(
            model_name='patientinsurance',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_cards', to='emr.patient'),
        ),
    ]
