# Generated by Django 5.2 on 2026-04-06

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_totpdevice"),
        (
            "emr",
            "0009_rename_emr_prescription_patient_status_emr_prescri_patient_d5a4e9_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AISafetyAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("drug_interaction", "Interação medicamentosa"),
                            ("allergy", "Alergia cruzada"),
                            ("dose", "Dose fora do intervalo"),
                            ("contraindication", "Contraindicação"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("caution", "Cautela"),
                            ("contraindication", "Contraindicação"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("recommendation", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("safe", "Seguro"),
                            ("flagged", "Alertado"),
                            ("acknowledged", "Reconhecido"),
                            ("error", "Erro"),
                        ],
                        default="flagged",
                        max_length=20,
                    ),
                ),
                ("override_reason", models.TextField(blank=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prescription_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safety_alerts",
                        to="emr.prescriptionitem",
                    ),
                ),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_safety_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Safety Alert",
                "verbose_name_plural": "AI Safety Alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="aisafetyalert",
            unique_together={("prescription_item", "alert_type")},
        ),
    ]
