# Generated by Django 5.2 on 2026-04-06

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0010_aisafetyalert"),
    ]

    operations = [
        migrations.CreateModel(
            name="AICIDSuggestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("query_text", models.TextField()),
                (
                    "suggestions",
                    models.JSONField(
                        default=list,
                        help_text="[{code, description, confidence}, ...]",
                    ),
                ),
                ("accepted_code", models.CharField(blank=True, max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cid10_suggestions",
                        to="emr.encounter",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI CID-10 Suggestion",
                "verbose_name_plural": "AI CID-10 Suggestions",
                "ordering": ["-created_at"],
            },
        ),
    ]
