# Generated by Django 5.2 on 2026-04-06

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0011_aicidsuggestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitlistEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("preferred_date_from", models.DateField()),
                ("preferred_date_to", models.DateField()),
                ("preferred_time_start", models.TimeField(blank=True, null=True)),
                ("preferred_time_end", models.TimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Aguardando"),
                            ("notified", "Notificado"),
                            ("booked", "Agendado"),
                            ("expired", "Expirado"),
                            ("cancelled", "Cancelado"),
                        ],
                        db_index=True,
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "offered_slot",
                    models.JSONField(
                        blank=True,
                        help_text='{"start": "ISO", "end": "ISO"}',
                        null=True,
                    ),
                ),
                ("expiry_task_id", models.CharField(blank=True, max_length=100)),
                ("priority", models.PositiveIntegerField(db_index=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_entries",
                        to="emr.patient",
                    ),
                ),
                (
                    "professional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_entries",
                        to="emr.professional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Waitlist Entry",
                "verbose_name_plural": "Waitlist Entries",
                "ordering": ["priority", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="waitlistentry",
            index=models.Index(
                fields=["professional", "status", "priority", "created_at"],
                name="emr_waitlis_profess_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="waitlistentry",
            index=models.Index(
                fields=["patient", "status"],
                name="emr_waitlis_patient_idx",
            ),
        ),
    ]
