# Generated by Django 5.2 on 2026-04-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0012_waitlistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
