# Generated by Django 5.2 on 2026-04-27 20:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0013_appointment_arrived_started"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="waitlistentry",
            new_name="emr_waitlis_profess_558edd_idx",
            old_name="emr_waitlis_profess_idx",
        ),
        migrations.RenameIndex(
            model_name="waitlistentry",
            new_name="emr_waitlis_patient_3f9bf4_idx",
            old_name="emr_waitlis_patient_idx",
        ),
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together={("professional", "start_time")},
        ),
    ]
