"""LGPD: encrypt sensitive patient PII and clinical free-text at rest.

Mirrors the established encryption pattern (ai.0007 for the AI scribe
transcription): for every newly-encrypted column we first change the field type
(schema), then re-save existing rows so the library writes the ciphertext (data).

Encrypted here:
  * Patient: full_name, social_name, phone, email, address, notes
  * MedicalHistory.notes
  * Encounter.chief_complaint
  * SOAPNote: subjective, objective, assessment, plan
  * ClinicalDocument.content

Because encrypted columns hold opaque, non-deterministic ciphertext they can no
longer be DB-indexed/ordered/searched. The two Patient indexes that referenced
full_name are dropped, the default ordering moves to medical_record_number, and
a replacement (is_active, medical_record_number) index is added. Name search is
handled in Python (see emr/filters.py). whatsapp is intentionally left plaintext
(indexed routing/dedup key for the WhatsApp subsystem).

The schema/index operations below are exactly as generated by makemigrations;
the trailing RunPython performs the one-time re-encryption of existing rows and
is read-safe before it runs (a decrypt failure on legacy plaintext falls back to
the plaintext value).
"""

import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models

import apps.core.fields

# (model_name, [field, ...]) to re-save so existing plaintext gets encrypted.
_REENCRYPT = [
    ("Patient", ["full_name", "social_name", "phone", "email", "address", "notes"]),
    ("MedicalHistory", ["notes"]),
    ("Encounter", ["chief_complaint"]),
    ("SOAPNote", ["subjective", "objective", "assessment", "plan"]),
    ("ClinicalDocument", ["content"]),
]


def encrypt_existing_pii(apps, schema_editor):
    # Use the real models (not historical) so the EncryptedField descriptors run.
    from apps.emr import models as emr_models

    for model_name, fields in _REENCRYPT:
        model = getattr(emr_models, model_name)
        for obj in model.objects.all():
            obj.save(update_fields=fields)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0015_encounter_signed_at_signed_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patient",
            options={"ordering": ["medical_record_number"]},
        ),
        migrations.RemoveIndex(
            model_name="patient",
            name="emr_patient_full_na_cf5707_idx",
        ),
        migrations.RemoveIndex(
            model_name="patient",
            name="emr_patient_is_acti_ef4c69_idx",
        ),
        migrations.AlterField(
            model_name="clinicaldocument",
            name="content",
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name="encounter",
            name="chief_complaint",
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="medicalhistory",
            name="notes",
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="address",
            field=apps.core.fields.EncryptedJSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="patient",
            name="email",
            field=encrypted_model_fields.fields.EncryptedEmailField(blank=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="full_name",
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name="patient",
            name="notes",
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="social_name",
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="soapnote",
            name="assessment",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, help_text="Diagnóstico, CID-10, impressão clínica"
            ),
        ),
        migrations.AlterField(
            model_name="soapnote",
            name="objective",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, help_text="Exame físico, sinais vitais, achados"
            ),
        ),
        migrations.AlterField(
            model_name="soapnote",
            name="plan",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, help_text="Conduta, prescrição, retorno"
            ),
        ),
        migrations.AlterField(
            model_name="soapnote",
            name="subjective",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, help_text="Queixa do paciente, história atual"
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["is_active", "medical_record_number"], name="emr_patient_is_acti_dc529e_idx"
            ),
        ),
        migrations.RunPython(encrypt_existing_pii, noop),
    ]
