# Generated by Django 5.2 on 2026-06-01 12:15

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_user_preferred_language'),
        ('emr', '0016_encrypt_patient_pii'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncounterProcedure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantidade')),
                ('unit_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor unitário (R$)')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='emr.encounter')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='emr.professional')),
                ('tuss_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounter_procedures', to='core.tusscode')),
            ],
            options={
                'verbose_name': 'Procedimento da Consulta',
                'verbose_name_plural': 'Procedimentos da Consulta',
                'ordering': ['created_at'],
            },
        ),
    ]
