# Generated by Django 5.2 on 2026-06-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0017_encounterprocedure"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="aisafetyalert",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="aisafetyalert",
            name="source",
            field=models.CharField(
                choices=[("llm", "LLM (explicação)"), ("engine", "Motor determinístico")],
                default="llm",
                help_text="Which checker produced this row: 'llm' explainer or 'engine' verdict.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="dose_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Structured dose per single administration (for dose engine, PR B).",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="dose_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mg", "mg"),
                    ("mcg", "mcg"),
                    ("mEq", "mEq"),
                    ("unit", "unit"),
                    ("mL", "mL"),
                    ("g", "g"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="frequency_per_day",
            field=models.SmallIntegerField(
                blank=True,
                help_text="Number of doses per day (for max-daily checks in PR B).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="route",
            field=models.CharField(
                blank=True,
                choices=[
                    ("IV", "Intravenosa"),
                    ("IM", "Intramuscular"),
                    ("SC", "Subcutânea"),
                    ("PO", "Oral"),
                ],
                max_length=4,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aisafetyalert",
            unique_together={("prescription_item", "alert_type", "source")},
        ),
    ]
