# Generated by Django 5.2 on 2026-06-01 19:36

from django.db import migrations, models


def _noop(apps, schema_editor):
    """Forward: nothing — the AddField default backfills source='llm'."""


def _drop_engine_rows_on_reverse(apps, schema_editor):
    """
    REVERSE-only data safety.

    Forward is a no-op. On REVERSE (downgrade), this runs BEFORE the `source`
    column is dropped and BEFORE unique_together is restored to
    (prescription_item, alert_type). Once PR B's deterministic engine has written
    source="engine" rows, a (prescription_item, alert_type) pair can hold TWO rows
    (one source="llm", one source="engine"). Dropping `source` + restoring the
    2-field unique_together would then crash with an IntegrityError on those
    duplicates. We delete the source="engine" rows first so the legacy LLM row
    survives as the single row per (prescription_item, alert_type).
    """
    AISafetyAlert = apps.get_model("emr", "AISafetyAlert")
    AISafetyAlert.objects.filter(source="engine").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0017_encounterprocedure"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="aisafetyalert",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="aisafetyalert",
            name="source",
            field=models.CharField(
                choices=[("llm", "LLM (explicação)"), ("engine", "Motor determinístico")],
                default="llm",
                help_text="Which checker produced this row: 'llm' explainer or 'engine' verdict.",
                max_length=10,
            ),
        ),
        # Reverse-only cleanup: on downgrade, drop engine-sourced rows BEFORE the
        # source column is dropped / 2-field unique_together is restored, so the
        # reverse can't hit a duplicate-key IntegrityError. Forward = no-op.
        migrations.RunPython(_noop, _drop_engine_rows_on_reverse),
        migrations.AddField(
            model_name="prescriptionitem",
            name="dose_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Structured dose per single administration (for dose engine, PR B). 4 decimal places so sub-milligram/mcg microdoses don't truncate to 0.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="dose_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mg", "mg"),
                    ("mcg", "mcg"),
                    ("mEq", "mEq"),
                    ("unit", "unit"),
                    ("g", "g"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="frequency_per_day",
            field=models.SmallIntegerField(
                blank=True,
                help_text="Number of doses per day (for max-daily checks in PR B).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="route",
            field=models.CharField(
                blank=True,
                choices=[
                    ("IV", "Intravenosa"),
                    ("IM", "Intramuscular"),
                    ("SC", "Subcutânea"),
                    ("PO", "Oral"),
                ],
                max_length=4,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aisafetyalert",
            unique_together={("prescription_item", "alert_type", "source")},
        ),
    ]
