# Generated by Django 5.2 on 2026-06-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0018_alter_aisafetyalert_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriptionitem",
            name="dose_role",
            field=models.CharField(
                blank=True,
                choices=[("maintenance", "Manutenção"), ("loading", "Ataque/Loading")],
                default="",
                max_length=12,
                help_text=(
                    "Optional dose role for the dose engine: 'loading' selects an explicit loading "
                    "rule; blank/'maintenance' uses the maintenance band (safe default)."
                ),
            ),
        ),
    ]
