# Generated by Django 5.2 on 2026-06-04 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0019_prescriptionitem_dose_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vitalsigns',
            options={'ordering': ['-recorded_at']},
        ),
        migrations.AddField(
            model_name='patient',
            name='use_spo2_scale_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='consciousness',
            field=models.CharField(blank=True, choices=[('A', 'Alerta'), ('C', 'Confusão (nova)'), ('V', 'Resposta à voz'), ('P', 'Resposta à dor'), ('U', 'Não responsivo')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='on_supplemental_oxygen',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='respiratory_rate',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='emr.encounter'),
        ),
    ]
