# Generated by Django 5.2 on 2026-06-04 04:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0020_alter_vitalsigns_options_patient_use_spo2_scale_2_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeteriorationAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("score", models.PositiveSmallIntegerField()),
                (
                    "band",
                    models.CharField(
                        choices=[
                            ("low", "Baixo"),
                            ("low_medium", "Baixo-médio (escore 3 em parâmetro único)"),
                            ("medium", "Médio"),
                            ("high", "Alto"),
                        ],
                        max_length=12,
                    ),
                ),
                ("breakdown", models.JSONField(default=dict)),
                ("any_param_three", models.BooleanField(default=False)),
                (
                    "spo2_scale",
                    models.PositiveSmallIntegerField(help_text="Escala SpO2 aplicada (1 ou 2)."),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("advise", "Avisa"), ("escalation", "Escalonamento (emergência)")],
                        max_length=12,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("engine", "Motor determinístico"), ("llm", "LLM (explicação)")],
                        default="engine",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Aberto"),
                            ("acknowledged", "Reconhecido"),
                            ("resolved", "Resolvido"),
                        ],
                        default="open",
                        max_length=14,
                    ),
                ),
                ("engine_version", models.CharField(max_length=40)),
                ("message", models.TextField(verbose_name="Mensagem (pt-BR)")),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_deterioration_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deterioration_alerts",
                        to="emr.encounter",
                    ),
                ),
                (
                    "vital_signs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deterioration_alerts",
                        to="emr.vitalsigns",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta de Deterioração (NEWS2)",
                "verbose_name_plural": "Alertas de Deterioração (NEWS2)",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "band"], name="emr_deterio_status_af01cb_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "open")),
                        fields=("encounter",),
                        name="uniq_open_deterioration_alert_per_encounter",
                    )
                ],
            },
        ),
    ]
