# Generated by Django 5.2 on 2026-06-04 19:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0021_deteriorationalert"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NoShowRisk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("score", models.DecimalField(decimal_places=4, max_digits=5)),
                (
                    "band",
                    models.CharField(
                        choices=[("low", "Baixo"), ("medium", "Médio"), ("high", "Alto")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("breakdown", models.JSONField(default=list)),
                (
                    "suggested_action",
                    models.CharField(
                        choices=[("none", "Nenhuma"), ("confirm_active", "Confirmar ativamente")],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Aberto"),
                            ("acknowledged", "Reconhecido"),
                            ("resolved", "Resolvido"),
                        ],
                        default="open",
                        max_length=14,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("true_positive", "Acerto (faltou, previsto)"),
                            ("false_positive", "Falso-positivo (compareceu, previsto falta)"),
                            ("false_negative", "Falso-negativo (faltou, não previsto)"),
                            ("true_negative", "Acerto (compareceu, previsto baixo)"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("engine_version", models.CharField(max_length=40)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_no_show_risks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="no_show_risk",
                        to="emr.appointment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Risco de Falta (motor)",
                "verbose_name_plural": "Riscos de Falta (motor)",
                "ordering": ["-score", "-created_at"],
                "indexes": [
                    models.Index(fields=["band", "outcome"], name="emr_noshowr_band_c40c49_idx")
                ],
            },
        ),
    ]
