# Generated by Django 5.2 on 2026-07-21 15:26

import uuid

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0026_escalationconfig_one_active_per_tenant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LabTest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("specimen_type", models.CharField(blank=True, max_length=80)),
                ("unit", models.CharField(blank=True, max_length=32)),
                ("reference_range", models.CharField(blank=True, max_length=160)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LabOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ordered", "Solicitado"),
                            ("collected", "Coletado"),
                            ("in_progress", "Em análise"),
                            ("completed", "Concluído"),
                            ("cancelled", "Cancelado"),
                        ],
                        db_index=True,
                        default="ordered",
                        max_length=16,
                    ),
                ),
                (
                    "clinical_indication",
                    encrypted_model_fields.fields.EncryptedTextField(blank=True),
                ),
                ("notes", encrypted_model_fields.fields.EncryptedTextField(blank=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("collected_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_orders",
                        to="emr.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lab_orders",
                        to="emr.patient",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_lab_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="LabOrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("test_name", models.CharField(max_length=160)),
                ("unit", models.CharField(blank=True, max_length=32)),
                ("reference_range", models.CharField(blank=True, max_length=160)),
                ("result_value", encrypted_model_fields.fields.EncryptedTextField(blank=True)),
                (
                    "abnormal_flag",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("low", "Baixo"),
                            ("high", "Alto"),
                            ("critical", "Crítico"),
                            ("undetermined", "Indeterminado"),
                        ],
                        default="undetermined",
                        max_length=14,
                    ),
                ),
                ("result_notes", encrypted_model_fields.fields.EncryptedTextField(blank=True)),
                ("resulted_at", models.DateTimeField(blank=True, null=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="emr.laborder",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="validated_lab_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="emr.labtest",
                    ),
                ),
            ],
            options={
                "ordering": ["test_name"],
            },
        ),
        migrations.AddIndex(
            model_name="laborder",
            index=models.Index(fields=["patient", "-requested_at"], name="emr_lab_pat_date_idx"),
        ),
        migrations.AddIndex(
            model_name="laborder",
            index=models.Index(fields=["status", "-requested_at"], name="emr_lab_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="laborderitem",
            constraint=models.UniqueConstraint(
                fields=("order", "test"), name="emr_lab_order_test_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="laborderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("validated_at__isnull", True), ("validated_by__isnull", True)),
                    models.Q(
                        ("resulted_at__isnull", False),
                        ("validated_at__isnull", False),
                        ("validated_by__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="emr_lab_validation_consistent",
            ),
        ),
    ]
