# Generated by Django 5.2 on 2026-07-21 16:00

import uuid

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models

import apps.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0028_expand_laboratory_domain"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="laborder",
            constraint=models.UniqueConstraint(
                condition=~models.Q(accession_number=""),
                fields=("accession_number",),
                name="emr_lab_accession_unique",
            ),
        ),
        migrations.CreateModel(
            name="LabIntegrationMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source", models.CharField(max_length=80)),
                ("message_id", models.CharField(max_length=120)),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Entrada"), ("outbound", "Saída")], max_length=8
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("canonical", "JSON canônico"),
                            ("hl7_v2", "HL7 v2"),
                            ("astm", "ASTM normalizado"),
                        ],
                        max_length=12,
                    ),
                ),
                ("payload_hash", models.CharField(max_length=64)),
                ("raw_payload", encrypted_model_fields.fields.EncryptedTextField(blank=True)),
                (
                    "canonical_payload",
                    apps.core.fields.EncryptedJSONField(blank=True, default=dict),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("applied", "Aplicado"),
                            ("rejected", "Rejeitado"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("error", encrypted_model_fields.fields.EncryptedTextField(blank=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lis_applied",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lab_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lis_messages",
                        to="emr.laborder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "message_id", "direction"),
                        name="emr_lis_message_idempotent",
                    )
                ],
            },
        ),
    ]
