# Generated by Django 5.2 on 2026-07-22

import encrypted_model_fields.fields
from django.db import migrations, models

import apps.core.fields


class Migration(migrations.Migration):
    dependencies = [("emr", "0029_lis_integration_boundary")]

    operations = [
        migrations.AddField(model_name="patient", name="cns", field=encrypted_model_fields.fields.EncryptedCharField(blank=True)),
        migrations.AddField(model_name="patient", name="identity_document", field=encrypted_model_fields.fields.EncryptedCharField(blank=True)),
        migrations.AddField(model_name="patient", name="identity_issuer", field=encrypted_model_fields.fields.EncryptedCharField(blank=True)),
        migrations.AddField(model_name="patient", name="identity_state", field=models.CharField(blank=True, max_length=2)),
        migrations.AddField(model_name="patient", name="birth_city", field=encrypted_model_fields.fields.EncryptedCharField(blank=True)),
        migrations.AddField(model_name="patient", name="birth_state", field=models.CharField(blank=True, max_length=2)),
        migrations.AddField(model_name="patient", name="nationality", field=models.CharField(blank=True, max_length=80)),
        migrations.AddField(
            model_name="patient", name="race_color",
            field=models.CharField(blank=True, choices=[("white", "Branca"), ("black", "Preta"), ("brown", "Parda"), ("yellow", "Amarela"), ("indigenous", "Indígena"), ("not_informed", "Não informada")], max_length=20),
        ),
        migrations.AddField(
            model_name="patient", name="marital_status",
            field=models.CharField(blank=True, choices=[("single", "Solteiro(a)"), ("married", "Casado(a)"), ("stable_union", "União estável"), ("separated", "Separado(a)"), ("divorced", "Divorciado(a)"), ("widowed", "Viúvo(a)"), ("not_informed", "Não informado")], max_length=20),
        ),
        migrations.AddField(model_name="patient", name="mother_name", field=encrypted_model_fields.fields.EncryptedCharField(blank=True)),
        migrations.AddField(model_name="patient", name="father_name", field=encrypted_model_fields.fields.EncryptedCharField(blank=True)),
        migrations.AddField(model_name="patient", name="occupation", field=encrypted_model_fields.fields.EncryptedCharField(blank=True)),
        migrations.AddField(model_name="patient", name="education_level", field=models.CharField(blank=True, max_length=80)),
        migrations.AddField(model_name="patient", name="preferred_language", field=models.CharField(blank=True, default="pt-BR", max_length=20)),
        migrations.AddField(model_name="patient", name="accessibility_needs", field=apps.core.fields.EncryptedJSONField(blank=True, default=dict)),
    ]
