# Generated by Django 5.2 on 2026-07-22 13:53

import uuid

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0030_expand_patient_demographics"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DuplicatePatientCandidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("score", models.DecimalField(decimal_places=4, max_digits=5)),
                ("reasons", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Pendente"),
                            ("confirmed", "Duplicidade confirmada"),
                            ("dismissed", "Descartada"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_notes",
                    encrypted_model_fields.fields.EncryptedTextField(blank=True, default=""),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_candidates_as_a",
                        to="emr.patient",
                    ),
                ),
                (
                    "patient_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_candidates_as_b",
                        to="emr.patient",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-score", "-created_at"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("patient_a", "patient_b"), name="emr_unique_duplicate_patient_pair"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("patient_a", models.F("patient_b")), _negated=True),
                        name="emr_duplicate_patients_must_differ",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PatientIdentifier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("system", models.CharField(max_length=120)),
                ("issuer", models.CharField(blank=True, default="", max_length=120)),
                ("value", encrypted_model_fields.fields.EncryptedCharField()),
                ("value_digest", models.CharField(editable=False, max_length=64)),
                (
                    "use",
                    models.CharField(
                        choices=[
                            ("usual", "Usual"),
                            ("official", "Oficial"),
                            ("secondary", "Secundário"),
                            ("old", "Antigo"),
                        ],
                        default="usual",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Ativo"),
                            ("inactive", "Inativo"),
                            ("entered-in-error", "Registrado por engano"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identifiers",
                        to="emr.patient",
                    ),
                ),
            ],
            options={
                "ordering": ("system", "issuer", "created_at"),
                "indexes": [
                    models.Index(
                        fields=["system", "issuer", "value_digest"],
                        name="emr_patient_system_654913_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("system", "issuer", "value_digest"),
                        name="emr_unique_patient_identifier",
                    )
                ],
            },
        ),
    ]
