# Generated by Django 5.2 on 2026-07-24 14:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0033_enterprise_diagnostics"),
        ("organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentResource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_links",
                        to="emr.appointment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurso do agendamento",
                "verbose_name_plural": "Recursos dos agendamentos",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("room", "Sala"),
                            ("equipment", "Equipamento"),
                            ("other", "Outro"),
                        ],
                        db_index=True,
                        default="room",
                        max_length=20,
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointments",
                    models.ManyToManyField(
                        related_name="resources",
                        through="emr.AppointmentResource",
                        to="emr.appointment",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resources",
                        to="organization.facility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurso",
                "verbose_name_plural": "Recursos",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="appointmentresource",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointment_links",
                to="emr.resource",
            ),
        ),
        migrations.CreateModel(
            name="ScheduleException",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("vacation", "Férias"),
                            ("holiday", "Feriado"),
                            ("block", "Bloqueio"),
                        ],
                        db_index=True,
                        default="block",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(db_index=True)),
                ("end_date", models.DateField(db_index=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedule_exceptions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "professional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_exceptions",
                        to="emr.professional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exceção de agenda",
                "verbose_name_plural": "Exceções de agenda",
                "ordering": ["start_date", "start_time"],
            },
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["facility", "active"], name="emr_resourc_facilit_093e81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(fields=["kind", "active"], name="emr_resourc_kind_19b947_idx"),
        ),
        migrations.AddIndex(
            model_name="appointmentresource",
            index=models.Index(
                fields=["resource", "appointment"], name="emr_appoint_resourc_98060a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="appointmentresource",
            constraint=models.UniqueConstraint(
                fields=("appointment", "resource"), name="emr_unique_appointment_resource"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduleexception",
            index=models.Index(
                fields=["professional", "start_date", "end_date"],
                name="emr_schedul_profess_4a9a1c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleexception",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="emr_schedule_exception_date_order",
            ),
        ),
    ]
