# Generated by Django 5.2 on 2026-07-24 14:11

import uuid

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0033_enterprise_diagnostics"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EncounterAddendum",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("encounter", "Encounter"),
                            ("clinical_document", "ClinicalDocument"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_id", models.CharField(max_length=64)),
                ("sequence", models.PositiveIntegerField(editable=False)),
                (
                    "reason",
                    encrypted_model_fields.fields.EncryptedTextField(
                        help_text="Motivo da correção/complemento (LGPD)"
                    ),
                ),
                (
                    "body",
                    encrypted_model_fields.fields.EncryptedTextField(
                        help_text="Conteúdo do adendo (LGPD)"
                    ),
                ),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("signature_hash", models.CharField(blank=True, max_length=128)),
                ("is_icp_brasil", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="encounter_addenda",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "previous_addendum",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="next_addenda",
                        to="emr.encounteraddendum",
                    ),
                ),
                (
                    "signed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signed_addenda",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["target_type", "target_id", "sequence"],
                "indexes": [
                    models.Index(
                        fields=["target_type", "target_id"], name="emr_encount_target__06b25b_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("target_type", "target_id", "sequence"),
                        name="emr_addendum_unique_sequence_per_target",
                    )
                ],
            },
        ),
    ]
