# Generated by Django 5.2 on 2026-07-24 14:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0033_enterprise_diagnostics"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalFormTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("specialty", models.CharField(db_index=True, max_length=100)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "schema",
                    models.JSONField(help_text="Lista de campos: key/label/type/required/options."),
                ),
                ("active", models.BooleanField(default=True)),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name", "specialty", "-version"],
                "unique_together": {("name", "specialty", "version")},
            },
        ),
        migrations.CreateModel(
            name="ClinicalFormResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("answers", apps.core.fields.EncryptedJSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="form_responses",
                        to="emr.encounter",
                    ),
                ),
                (
                    "filled_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="form_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="form_responses",
                        to="emr.patient",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responses",
                        to="emr.clinicalformtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["encounter", "created_at"], name="emr_clinica_encount_e95f36_idx"
                    ),
                    models.Index(
                        fields=["patient", "created_at"], name="emr_clinica_patient_1572e7_idx"
                    ),
                ],
            },
        ),
    ]
