# Generated by Django 5.2 on 2026-07-24 15:53

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_cid10_rich"),
        ("emr", "0036_merge_20260724_1204"),
        ("pharmacy", "0029_nfereceipt_external_id_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="allergy",
            name="allergen_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="allergies",
                to="pharmacy.allergenclass",
                verbose_name="Classe de alérgeno",
            ),
        ),
        migrations.AddField(
            model_name="allergy",
            name="allergen_unmatched",
            field=models.BooleanField(
                default=False,
                help_text="True quando substance não foi mapeada para nenhuma AllergenClass.",
            ),
        ),
        migrations.AddField(
            model_name="allergy",
            name="criticality",
            field=models.CharField(
                blank=True, choices=[("low", "Baixa"), ("high", "Alta")], default="", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="allergy",
            name="reaction_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rash", "Erupção cutânea"),
                    ("urticaria", "Urticária"),
                    ("angioedema", "Angioedema"),
                    ("anaphylaxis", "Anafilaxia"),
                    ("bronchospasm", "Broncoespasmo"),
                    ("gi", "Gastrointestinal"),
                    ("other", "Outra"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="allergy",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("unconfirmed", "Não confirmada"),
                    ("confirmed", "Confirmada"),
                    ("refuted", "Refutada"),
                ],
                default="unconfirmed",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Immunization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("immunobiological", models.CharField(max_length=200)),
                ("dose_number", models.CharField(blank=True, default="", max_length=50)),
                ("lot", models.CharField(blank=True, default="", max_length=100)),
                ("manufacturer", models.CharField(blank=True, default="", max_length=200)),
                ("date", models.DateField()),
                (
                    "pni_calendar_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Referência ao calendário PNI que esta dose cumpre.",
                        max_length=120,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="immunizations",
                        to="emr.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imunização",
                "verbose_name_plural": "Imunizações",
                "ordering": ["-date", "immunobiological"],
                "indexes": [
                    models.Index(fields=["patient", "date"], name="emr_immuniz_patient_5feddc_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="ProblemListItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("condition", models.CharField(max_length=300)),
                (
                    "legacy_cid_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Código CID-10 bruto não reconciliado com core.CID10Code.",
                        max_length=10,
                    ),
                ),
                (
                    "cid_unmatched",
                    models.BooleanField(
                        default=False,
                        help_text="True quando legacy_cid_text não corresponde a nenhum CID10Code governado.",
                    ),
                ),
                (
                    "clinical_status",
                    models.CharField(
                        choices=[
                            ("active", "Ativo"),
                            ("inactive", "Inativo"),
                            ("resolved", "Resolvido"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("provisional", "Provisório"),
                            ("confirmed", "Confirmado"),
                            ("refuted", "Refutado"),
                        ],
                        default="provisional",
                        max_length=20,
                    ),
                ),
                ("onset_date", models.DateField(blank=True, null=True)),
                (
                    "abatement_date",
                    models.DateField(
                        blank=True,
                        help_text="Data de resolução/remissão do problema (FHIR abatement).",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cid10",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.cid10code",
                        verbose_name="CID-10",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="problems",
                        to="emr.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_list",
                        to="emr.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item da lista de problemas",
                "verbose_name_plural": "Lista de problemas",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "clinical_status"], name="emr_problem_patient_6af475_idx"
                    )
                ],
            },
        ),
    ]
