# Generated by Django 5.2 on 2026-07-24 17:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0038_backfill_allergen_class'),
        ('governance', '0002_integration_inbox'),
        ('pharmacy', '0030_drug_anvisa_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationReconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('moment', models.CharField(choices=[('admission', 'Admissão'), ('discharge', 'Alta'), ('transfer', 'Transferência')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('completed', 'Concluída')], db_index=True, default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medication_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medication_reconciliations', to='emr.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medication_reconciliations', to='emr.patient')),
            ],
            options={
                'verbose_name': 'Reconciliação medicamentosa',
                'verbose_name_plural': 'Reconciliações medicamentosas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationReconciliationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=300)),
                ('home_dosage', models.CharField(blank=True, help_text='Posologia de uso contínuo em casa.', max_length=200)),
                ('action', models.CharField(choices=[('continue', 'Manter'), ('stop', 'Suspender'), ('modify', 'Modificar'), ('start', 'Iniciar')], db_index=True, max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prescription_item', models.ForeignKey(blank=True, help_text='Ordem resultante (quando a decisão instancia/altera uma prescrição).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_items', to='emr.prescriptionitem')),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='emr.medicationreconciliation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(help_text='Identificador lógico estável.', max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('pending_approval', 'Aguardando aprovação'), ('approved', 'Aprovado'), ('archived', 'Arquivado')], db_index=True, default='draft', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='governance.approvalrequest')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_sets_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order set',
                'verbose_name_plural': 'Order sets',
                'ordering': ['key', '-version'],
            },
        ),
        migrations.CreateModel(
            name='OrderSetApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applied_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_set_applications', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_set_applications', to='emr.encounter')),
                ('order_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='emr.orderset')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderSetItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_type', models.CharField(choices=[('medication', 'Medicamento'), ('lab', 'Laboratório'), ('imaging', 'Imagem')], db_index=True, max_length=20)),
                ('label', models.CharField(max_length=300)),
                ('dosage_instructions', models.TextField(blank=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pharmacy.drug')),
                ('order_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='emr.orderset')),
            ],
            options={
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppliedOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_type', models.CharField(choices=[('medication', 'Medicamento'), ('lab', 'Laboratório'), ('imaging', 'Imagem')], max_length=20)),
                ('label', models.CharField(max_length=300)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('fulfilled', 'Efetivada'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pharmacy.drug')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_orders', to='emr.encounter')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='emr.ordersetapplication')),
                ('source_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='emr.ordersetitem')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='medicationreconciliation',
            index=models.Index(fields=['encounter', 'moment'], name='emr_medicat_encount_ed2a1c_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationreconciliation',
            index=models.Index(fields=['patient', 'status'], name='emr_medicat_patient_29f891_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderset',
            constraint=models.UniqueConstraint(fields=('key', 'version'), name='emr_orderset_key_version'),
        ),
    ]
