# Generated by Django 5.2 on 2026-07-26 01:02

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_loinccode_ucumunit"),
        ("emr", "0040_professional_cbo_cnes_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="labtest",
            name="delta_threshold_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Variação percentual que dispara um alerta de delta. Vazio = inerte.",
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Limiar de delta-check (%)",
            ),
        ),
        migrations.AddField(
            model_name="labtest",
            name="loinc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.loinccode",
                verbose_name="LOINC (catálogo)",
            ),
        ),
        migrations.CreateModel(
            name="LabDeltaAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("previous_value", models.DecimalField(decimal_places=6, max_digits=18)),
                ("current_value", models.DecimalField(decimal_places=6, max_digits=18)),
                ("delta_absolute", models.DecimalField(decimal_places=6, max_digits=18)),
                ("delta_pct", models.DecimalField(decimal_places=4, max_digits=12)),
                ("threshold_pct", models.DecimalField(decimal_places=2, max_digits=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order_item",
                    models.OneToOneField(
                        help_text="Resultado atual que disparou o alerta.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delta_alert",
                        to="emr.laborderitem",
                    ),
                ),
                (
                    "previous_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Resultado anterior comparado (o mais recente antes deste).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delta_alerts_as_previous",
                        to="emr.laborderitem",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delta_alerts",
                        to="emr.labtest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["test", "-created_at"], name="emr_delta_test_date_idx")
                ],
            },
        ),
    ]
