# Generated by Django 5.2 on 2026-07-26 17:49

import uuid

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_nandadiagnosis_nicintervention_nocoutcome"),
        ("emr", "0041_labtest_delta_threshold_pct_labtest_loinc_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NursingCareplan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "legacy_noc_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Código NOC bruto não reconciliado com core.NocOutcome.",
                        max_length=32,
                    ),
                ),
                (
                    "noc_unmatched",
                    models.BooleanField(
                        default=False,
                        help_text="True quando legacy_noc_text não corresponde a nenhum NocOutcome governado.",
                    ),
                ),
                (
                    "expected_outcome",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Descrição do resultado esperado (complementa o rótulo NOC).",
                        verbose_name="Resultado esperado",
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Meta / alvo do indicador NOC (ex.: 'escala de dor ≤ 2 em 48h').",
                        max_length=200,
                        verbose_name="Meta",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authored_nursing_careplans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "noc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.nocoutcome",
                        verbose_name="Resultado NOC",
                    ),
                ),
            ],
            options={
                "verbose_name": "Planejamento de Enfermagem",
                "verbose_name_plural": "Planejamentos de Enfermagem",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NursingCareplanIntervention",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "legacy_nic_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Código NIC bruto não reconciliado com core.NicIntervention.",
                        max_length=32,
                    ),
                ),
                (
                    "nic_unmatched",
                    models.BooleanField(
                        default=False,
                        help_text="True quando legacy_nic_text não corresponde a nenhum NicIntervention governado.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Detalhamento / atividades específicas da intervenção neste paciente.",
                        verbose_name="Observações",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "careplan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interventions",
                        to="emr.nursingcareplan",
                    ),
                ),
                (
                    "nic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.nicintervention",
                        verbose_name="Intervenção NIC",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intervenção de Enfermagem (NIC)",
                "verbose_name_plural": "Intervenções de Enfermagem (NIC)",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="NursingDiagnosis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "legacy_nanda_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Código NANDA-I bruto não reconciliado com core.NandaDiagnosis.",
                        max_length=32,
                    ),
                ),
                (
                    "nanda_unmatched",
                    models.BooleanField(
                        default=False,
                        help_text="True quando legacy_nanda_text não corresponde a nenhum NandaDiagnosis governado.",
                    ),
                ),
                (
                    "related_factors",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Fatores relacionados / de risco identificados neste paciente.",
                        verbose_name="Fatores relacionados",
                    ),
                ),
                (
                    "defining_characteristics",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Características definidoras observadas neste paciente.",
                        verbose_name="Características definidoras",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Ativo"), ("resolved", "Resolvido")],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("high", "Alta"), ("medium", "Média"), ("low", "Baixa")],
                        db_index=True,
                        default="medium",
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authored_nursing_diagnoses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nursing_diagnoses",
                        to="emr.encounter",
                    ),
                ),
                (
                    "nanda",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.nandadiagnosis",
                        verbose_name="Diagnóstico NANDA-I",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nursing_diagnoses",
                        to="emr.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diagnóstico de Enfermagem",
                "verbose_name_plural": "Diagnósticos de Enfermagem",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="nursingcareplan",
            name="diagnosis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="careplans",
                to="emr.nursingdiagnosis",
            ),
        ),
        migrations.CreateModel(
            name="NursingEvolution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "text",
                    encrypted_model_fields.fields.EncryptedTextField(
                        help_text="Texto da evolução de enfermagem.", verbose_name="Evolução"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authored_nursing_evolutions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nursing_evolutions",
                        to="emr.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nursing_evolutions",
                        to="emr.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evolução de Enfermagem",
                "verbose_name_plural": "Evoluções de Enfermagem",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NursingPrescriptionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="O que executar (ex.: 'Verificar sinais vitais').",
                        max_length=300,
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "frequency_hours",
                    models.PositiveSmallIntegerField(
                        help_text="Intervalo em horas entre execuções (ex.: 6 = de 6/6h). Base do aprazamento.",
                        verbose_name="Frequência (horas)",
                    ),
                ),
                (
                    "start_at",
                    models.DateTimeField(
                        help_text="Momento da primeira execução; âncora da grade de aprazamento.",
                        verbose_name="Início",
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authored_nursing_prescription_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "intervention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescription_items",
                        to="emr.nursingcareplanintervention",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prescrição de Enfermagem (item)",
                "verbose_name_plural": "Prescrições de Enfermagem (itens)",
                "ordering": ["start_at"],
            },
        ),
        migrations.AddIndex(
            model_name="nursingdiagnosis",
            index=models.Index(fields=["patient", "status"], name="emr_nursingdx_pat_status_idx"),
        ),
        migrations.AddIndex(
            model_name="nursingdiagnosis",
            index=models.Index(fields=["encounter"], name="emr_nursingdx_enc_idx"),
        ),
        migrations.AddIndex(
            model_name="nursingevolution",
            index=models.Index(fields=["patient", "created_at"], name="emr_nursingevo_pat_idx"),
        ),
        migrations.AddIndex(
            model_name="nursingevolution",
            index=models.Index(fields=["encounter"], name="emr_nursingevo_enc_idx"),
        ),
        migrations.AddIndex(
            model_name="nursingprescriptionitem",
            index=models.Index(fields=["active", "start_at"], name="emr_nursingrx_active_idx"),
        ),
    ]
