# Generated by Django 5.2 on 2026-07-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0042_nursingcareplan_nursingcareplanintervention_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicationadministration",
            name="bcma_override_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="medicationadministration",
            name="bcma_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="medicationadministration",
            name="medication_barcode_scanned",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="medicationadministration",
            name="patient_barcode_scanned",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="patient",
            name="wristband_barcode",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
