# Generated by Django 5.2 on 2026-07-26 23:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_bedtype"),
        ("emr", "0043_medicationadministration_bcma_override_reason_and_more"),
        ("organization", "0002_facility_cnes_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="InpatientUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "code",
                    models.CharField(
                        help_text="Código da unidade (único por estabelecimento).",
                        max_length=50,
                        verbose_name="Código",
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True, verbose_name="Ativa")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_bed_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.bedtype",
                        verbose_name="Tipo de leito padrão",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inpatient_units",
                        to="organization.facility",
                        verbose_name="Estabelecimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidade de Internação",
                "verbose_name_plural": "Unidades de Internação",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome ou número do quarto (único por unidade).",
                        max_length=50,
                        verbose_name="Nome/número",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("any", "Indiferente"),
                            ("male", "Masculino"),
                            ("female", "Feminino"),
                        ],
                        db_index=True,
                        default="any",
                        max_length=8,
                        verbose_name="Gênero",
                    ),
                ),
                (
                    "isolation",
                    models.BooleanField(
                        default=False,
                        help_text="Quarto destinado a isolamento.",
                        verbose_name="Isolamento",
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="emr.inpatientunit",
                        verbose_name="Unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quarto",
                "verbose_name_plural": "Quartos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Bed",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="Código/identificador do leito (único por unidade).",
                        max_length=50,
                        verbose_name="Identificador",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("livre", "Livre"),
                            ("ocupado", "Ocupado"),
                            ("higienizacao", "Em higienização"),
                            ("bloqueado", "Bloqueado"),
                            ("reservado", "Reservado"),
                            ("interditado", "Interditado"),
                        ],
                        db_index=True,
                        default="livre",
                        max_length=16,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "legacy_bed_type_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Código de tipo de leito bruto não reconciliado com core.BedType.",
                        max_length=32,
                    ),
                ),
                (
                    "bed_type_unmatched",
                    models.BooleanField(
                        default=False,
                        help_text="True quando legacy_bed_type_text não corresponde a nenhum BedType governado.",
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bed_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.bedtype",
                        verbose_name="Tipo de leito",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="beds",
                        to="emr.inpatientunit",
                        verbose_name="Unidade",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beds",
                        to="emr.room",
                        verbose_name="Quarto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leito",
                "verbose_name_plural": "Leitos",
                "ordering": ["identifier"],
            },
        ),
        migrations.AddIndex(
            model_name="inpatientunit",
            index=models.Index(fields=["facility", "active"], name="emr_inpunit_fac_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="inpatientunit",
            constraint=models.UniqueConstraint(
                fields=("facility", "code"), name="uniq_inpatient_unit_code_per_facility"
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["unit", "active"], name="emr_room_unit_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.UniqueConstraint(
                fields=("unit", "name"), name="uniq_room_name_per_unit"
            ),
        ),
        migrations.AddIndex(
            model_name="bed",
            index=models.Index(fields=["unit", "status"], name="emr_bed_unit_status_idx"),
        ),
        migrations.AddIndex(
            model_name="bed",
            index=models.Index(fields=["room"], name="emr_bed_room_idx"),
        ),
        migrations.AddConstraint(
            model_name="bed",
            constraint=models.UniqueConstraint(
                fields=("unit", "identifier"), name="uniq_bed_identifier_per_unit"
            ),
        ),
    ]
