# Generated by Django 5.2 on 2026-07-27 00:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0044_inpatientunit_room_bed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='encounter_type',
            field=models.CharField(choices=[('ambulatorial', 'Ambulatorial'), ('internacao', 'Internação'), ('emergencia', 'Emergência'), ('observacao', 'Observação')], db_index=True, default='ambulatorial', help_text='Contexto do encontro (ambulatorial por padrão — não quebra fluxos existentes).', max_length=20),
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admission_source', models.CharField(choices=[('emergencia', 'Emergência'), ('ambulatorio', 'Ambulatório'), ('transferencia_externa', 'Transferência externa'), ('centro_cirurgico', 'Centro cirúrgico'), ('outro', 'Outro')], default='outro', max_length=32, verbose_name='Origem da internação')),
                ('admission_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/hora da internação')),
                ('expected_discharge_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Alta prevista')),
                ('actual_discharge_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Alta efetiva')),
                ('disposition', models.CharField(blank=True, choices=[('alta_melhorada', 'Alta melhorada'), ('alta_a_pedido', 'Alta a pedido'), ('transferencia_externa', 'Transferência externa'), ('obito', 'Óbito'), ('evasao', 'Evasão'), ('outro', 'Outro')], max_length=32, null=True, verbose_name='Desfecho')),
                ('status', models.CharField(choices=[('admitted', 'Internado'), ('discharged', 'Alta'), ('cancelled', 'Cancelada')], db_index=True, default='admitted', max_length=16, verbose_name='Situação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admitting_professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions_admitted', to='emr.professional', verbose_name='Profissional internador')),
                ('attending_professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions_attending', to='emr.professional', verbose_name='Profissional responsável')),
                ('current_bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='emr.bed', verbose_name='Leito atual')),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='emr.encounter', verbose_name='Encontro de internação')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='emr.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Internação',
                'verbose_name_plural': 'Internações',
                'ordering': ['-admission_datetime'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('admit', 'Admissão'), ('transfer', 'Transferência'), ('discharge', 'Alta'), ('cancel', 'Cancelamento')], db_index=True, max_length=16, verbose_name='Tipo de evento')),
                ('reason', models.TextField(blank=True, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_events', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='emr.admission', verbose_name='Internação')),
                ('from_bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admission_events_from', to='emr.bed', verbose_name='Leito de origem')),
                ('to_bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admission_events_to', to='emr.bed', verbose_name='Leito de destino')),
            ],
            options={
                'verbose_name': 'Evento ADT',
                'verbose_name_plural': 'Eventos ADT',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['patient', 'status'], name='emr_adm_patient_status_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['status', 'admission_datetime'], name='emr_adm_status_dt_idx'),
        ),
        migrations.AddConstraint(
            model_name='admission',
            constraint=models.UniqueConstraint(condition=models.Q(('current_bed__isnull', False), ('status', 'admitted')), fields=('current_bed',), name='uniq_active_admission_per_bed'),
        ),
        migrations.AddIndex(
            model_name='admissionevent',
            index=models.Index(fields=['admission', 'created_at'], name='emr_admevt_adm_dt_idx'),
        ),
    ]
