# Generated by Django 5.2 on 2026-07-27 15:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_bedtype"),
        ("emr", "0045_encounter_encounter_type_admission_admissionevent_and_more"),
        ("organization", "0002_facility_cnes_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperatingRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Código da sala (único por estabelecimento).",
                        max_length=50,
                        verbose_name="Código",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "room_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("geral", "Geral"),
                            ("hibrida", "Híbrida"),
                            ("ambulatorial", "Ambulatorial"),
                        ],
                        default="",
                        max_length=16,
                        verbose_name="Tipo de sala",
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True, verbose_name="Ativa")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operating_rooms",
                        to="organization.facility",
                        verbose_name="Estabelecimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sala Cirúrgica",
                "verbose_name_plural": "Salas Cirúrgicas",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="SurgicalCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "scheduled_start",
                    models.DateTimeField(blank=True, null=True, verbose_name="Início agendado"),
                ),
                (
                    "scheduled_end",
                    models.DateTimeField(blank=True, null=True, verbose_name="Fim agendado"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("eletiva", "Eletiva"),
                            ("urgencia", "Urgência"),
                            ("emergencia", "Emergência"),
                        ],
                        default="eletiva",
                        max_length=16,
                        verbose_name="Prioridade",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("agendada", "Agendada"),
                            ("confirmada", "Confirmada"),
                            ("em_sala", "Em sala"),
                            ("em_andamento", "Em andamento"),
                            ("finalizada", "Finalizada"),
                            ("cancelada", "Cancelada"),
                        ],
                        db_index=True,
                        default="agendada",
                        max_length=16,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "anesthesia_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("geral", "Geral"),
                            ("raqui", "Raquianestesia"),
                            ("peridural", "Peridural"),
                            ("local", "Local"),
                            ("sedacao", "Sedação"),
                        ],
                        max_length=16,
                        null=True,
                        verbose_name="Tipo de anestesia",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="surgical_cases",
                        to="emr.admission",
                        verbose_name="Internação",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="surgical_cases_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="surgical_cases",
                        to="emr.encounter",
                        verbose_name="Encontro cirúrgico",
                    ),
                ),
                (
                    "operating_room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="surgical_cases",
                        to="emr.operatingroom",
                        verbose_name="Sala cirúrgica",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="surgical_cases",
                        to="emr.patient",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "surgeon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="surgical_cases",
                        to="emr.professional",
                        verbose_name="Cirurgião",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caso Cirúrgico",
                "verbose_name_plural": "Casos Cirúrgicos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SurgicalProcedure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1, verbose_name="Quantidade")),
                (
                    "laterality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("esquerda", "Esquerda"),
                            ("direita", "Direita"),
                            ("bilateral", "Bilateral"),
                            ("na", "Não se aplica"),
                        ],
                        default="",
                        max_length=16,
                        verbose_name="Lateralidade",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedures",
                        to="emr.surgicalcase",
                        verbose_name="Caso cirúrgico",
                    ),
                ),
                (
                    "tuss_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="surgical_procedures",
                        to="core.tusscode",
                        verbose_name="Procedimento (TUSS)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Procedimento Cirúrgico",
                "verbose_name_plural": "Procedimentos Cirúrgicos",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="operatingroom",
            index=models.Index(fields=["facility", "active"], name="emr_or_fac_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="operatingroom",
            constraint=models.UniqueConstraint(
                fields=("facility", "code"), name="uniq_operating_room_code_per_facility"
            ),
        ),
        migrations.AddIndex(
            model_name="surgicalcase",
            index=models.Index(fields=["patient", "status"], name="emr_surgcase_pat_status_idx"),
        ),
        migrations.AddIndex(
            model_name="surgicalcase",
            index=models.Index(
                fields=["status", "scheduled_start"], name="emr_surgcase_status_dt_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="surgicalcase",
            index=models.Index(
                fields=["operating_room", "scheduled_start"], name="emr_surgcase_or_dt_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="surgicalprocedure",
            index=models.Index(fields=["case"], name="emr_surgproc_case_idx"),
        ),
    ]
