# Generated by Django 5.2 on 2026-07-27 16:26

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0046_operatingroom_surgicalcase_surgicalprocedure_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SurgicalChecklist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("sign_in", "Sign in (antes da anestesia)"),
                            ("time_out", "Time out (antes da incisão)"),
                            ("sign_out", "Sign out (antes de sair da sala)"),
                        ],
                        db_index=True,
                        max_length=12,
                        verbose_name="Fase",
                    ),
                ),
                (
                    "items",
                    models.JSONField(blank=True, default=dict, verbose_name="Itens confirmados"),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Confirmado em"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checklists",
                        to="emr.surgicalcase",
                        verbose_name="Caso cirúrgico",
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="surgical_checklists",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Confirmado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Checklist de Cirurgia Segura",
                "verbose_name_plural": "Checklists de Cirurgia Segura",
                "ordering": ["confirmed_at", "created_at"],
                "indexes": [
                    models.Index(fields=["case", "phase"], name="emr_surgcl_case_phase_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("case", "phase"), name="uniq_surg_checklist_case_phase"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SurgicalTeamMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("cirurgiao", "Cirurgião"),
                            ("primeiro_auxiliar", "Primeiro auxiliar"),
                            ("anestesista", "Anestesista"),
                            ("instrumentador", "Instrumentador"),
                            ("circulante", "Circulante"),
                            ("outro", "Outro"),
                        ],
                        max_length=24,
                        verbose_name="Função",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team",
                        to="emr.surgicalcase",
                        verbose_name="Caso cirúrgico",
                    ),
                ),
                (
                    "professional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="surgical_team_memberships",
                        to="emr.professional",
                        verbose_name="Profissional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membro da Equipe Cirúrgica",
                "verbose_name_plural": "Equipe Cirúrgica",
                "ordering": ["role", "created_at"],
                "indexes": [models.Index(fields=["case"], name="emr_surgteam_case_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("case", "professional", "role"),
                        name="uniq_surg_team_case_prof_role",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SurgicalTime",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("sala_entrada", "Entrada na sala"),
                            ("anestesia_inicio", "Início da anestesia"),
                            ("anestesia_fim", "Fim da anestesia"),
                            ("incisao", "Incisão"),
                            ("fechamento", "Fechamento"),
                            ("sala_saida", "Saída da sala"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Evento",
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Registrado em"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="times",
                        to="emr.surgicalcase",
                        verbose_name="Caso cirúrgico",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="surgical_times",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tempo Cirúrgico",
                "verbose_name_plural": "Tempos Cirúrgicos",
                "ordering": ["recorded_at", "created_at"],
                "indexes": [
                    models.Index(fields=["case", "recorded_at"], name="emr_surgtime_case_dt_idx")
                ],
            },
        ),
    ]
