# Generated by Django 5.2 on 2026-07-27 18:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0047_surgicalchecklist_surgicalteammember_surgicaltime'),
        ('pharmacy', '0031_controlledsubstanceledger_controlledledgerclosing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurgicalMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('opme', 'OPME'), ('material', 'Material'), ('medicamento', 'Medicamento'), ('outro', 'Outro')], db_index=True, max_length=12, verbose_name='Tipo')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Descrição')),
                ('quantity_planned', models.PositiveIntegerField(default=1, verbose_name='Quantidade planejada')),
                ('quantity_consumed', models.PositiveIntegerField(default=0, verbose_name='Quantidade consumida')),
                ('laterality', models.CharField(blank=True, choices=[('esquerda', 'Esquerda'), ('direita', 'Direita'), ('bilateral', 'Bilateral'), ('na', 'Não se aplica')], default='', max_length=16, verbose_name='Lateralidade')),
                ('lot', models.CharField(blank=True, max_length=100, verbose_name='Lote (OPME)')),
                ('serial', models.CharField(blank=True, max_length=100, verbose_name='Número de série (OPME)')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Fabricante')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='emr.surgicalcase', verbose_name='Caso cirúrgico')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgical_materials_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='surgical_materials', to='pharmacy.stockitem', verbose_name='Lote de estoque')),
            ],
            options={
                'verbose_name': 'Material / OPME Cirúrgico',
                'verbose_name_plural': 'Materiais / OPME Cirúrgicos',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['case'], name='emr_surgmat_case_idx'), models.Index(fields=['case', 'kind'], name='emr_surgmat_case_kind_idx')],
            },
        ),
    ]
