# Generated by Django 5.2 on 2026-07-28 19:47

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_manchesterflowchart_manchesterdiscriminator"),
        ("emr", "0048_surgicalmaterial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyEncounter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "arrival_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, verbose_name="Chegada"
                    ),
                ),
                (
                    "mode_of_arrival",
                    models.CharField(
                        choices=[
                            ("ambulante", "Ambulante"),
                            ("cadeira_rodas", "Cadeira de rodas"),
                            ("maca", "Maca"),
                            ("ambulancia", "Ambulância"),
                            ("viatura_pm", "Viatura (PM/SAMU)"),
                            ("outro", "Outro"),
                        ],
                        default="ambulante",
                        max_length=16,
                        verbose_name="Meio de chegada",
                    ),
                ),
                (
                    "chief_complaint",
                    models.TextField(blank=True, default="", verbose_name="Queixa principal"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aguardando_classificacao", "Aguardando classificação"),
                            ("classificado", "Classificado"),
                            ("em_atendimento", "Em atendimento"),
                            ("encerrado", "Encerrado"),
                        ],
                        db_index=True,
                        default="aguardando_classificacao",
                        max_length=32,
                        verbose_name="Situação",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emergency_encounters_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aberto por",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emergency_encounters",
                        to="emr.encounter",
                        verbose_name="Encontro clínico (emergência)",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="emergency_encounters",
                        to="emr.patient",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Boletim de Emergência",
                "verbose_name_plural": "Boletins de Emergência",
                "ordering": ["-arrival_at"],
            },
        ),
        migrations.CreateModel(
            name="RiskClassification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "acuity_level",
                    models.CharField(
                        choices=[
                            ("vermelho", "Vermelho (emergência)"),
                            ("laranja", "Laranja (muito urgente)"),
                            ("amarelo", "Amarelo (urgente)"),
                            ("verde", "Verde (pouco urgente)"),
                            ("azul", "Azul (não urgente)"),
                        ],
                        db_index=True,
                        help_text="Cópia estável do nível do discriminador no momento da classificação.",
                        max_length=10,
                        verbose_name="Nível de acuidade",
                    ),
                ),
                (
                    "target_minutes",
                    models.PositiveIntegerField(
                        help_text="Tempo-alvo de atendimento do nível Manchester (cópia estável).",
                        verbose_name="Tempo-alvo (min)",
                    ),
                ),
                (
                    "classified_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Classificado em",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="", verbose_name="Observações")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "boletim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classifications",
                        to="emr.emergencyencounter",
                        verbose_name="Boletim",
                    ),
                ),
                (
                    "classified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risk_classifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Classificado por",
                    ),
                ),
                (
                    "discriminator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.manchesterdiscriminator",
                        verbose_name="Discriminador",
                    ),
                ),
                (
                    "flowchart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.manchesterflowchart",
                        verbose_name="Fluxograma",
                    ),
                ),
                (
                    "vitals",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risk_classifications",
                        to="emr.vitalsigns",
                        verbose_name="Sinais vitais",
                    ),
                ),
            ],
            options={
                "verbose_name": "Classificação de Risco",
                "verbose_name_plural": "Classificações de Risco",
                "ordering": ["-classified_at", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="emergencyencounter",
            index=models.Index(fields=["status", "arrival_at"], name="emr_emerg_status_arr_idx"),
        ),
        migrations.AddIndex(
            model_name="emergencyencounter",
            index=models.Index(fields=["patient", "status"], name="emr_emerg_patient_status_idx"),
        ),
        migrations.AddIndex(
            model_name="riskclassification",
            index=models.Index(fields=["boletim", "classified_at"], name="emr_riskcls_bol_dt_idx"),
        ),
    ]
