# Generated by Django 5.2 on 2026-07-28 21:00

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0050_emergencyencounter_admission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='cns',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default=''),
        ),
    ]
