# Generated by Django 5.2 on 2026-07-28 22:58

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_bloodcomponentcatalog"),
        ("emr", "0052_encounterprocedure_sigtap"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="abo",
            field=models.CharField(
                blank=True, choices=[("A", "A"), ("B", "B"), ("AB", "AB"), ("O", "O")], max_length=2
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="antibody_screen",
            field=models.CharField(
                blank=True,
                choices=[
                    ("negativo", "Negativo"),
                    ("positivo", "Positivo"),
                    ("nao_realizado", "Não realizado"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="rh_factor",
            field=models.CharField(
                blank=True,
                choices=[("positivo", "Positivo"), ("negativo", "Negativo")],
                max_length=8,
            ),
        ),
        migrations.CreateModel(
            name="BloodBag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        db_index=True,
                        help_text="Número de identificação da doação (DIN) — único.",
                        max_length=64,
                        unique=True,
                        verbose_name="Identificador/DIN",
                    ),
                ),
                (
                    "abo",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("AB", "AB"), ("O", "O")],
                        db_index=True,
                        max_length=2,
                        verbose_name="Grupo ABO",
                    ),
                ),
                (
                    "rh_factor",
                    models.CharField(
                        choices=[("positivo", "Positivo"), ("negativo", "Negativo")],
                        db_index=True,
                        max_length=8,
                        verbose_name="Fator Rh",
                    ),
                ),
                ("volume_ml", models.PositiveIntegerField(verbose_name="Volume (mL)")),
                ("collection_date", models.DateField(verbose_name="Data de coleta")),
                ("expiry_date", models.DateField(db_index=True, verbose_name="Data de validade")),
                (
                    "serology_status",
                    models.CharField(
                        choices=[
                            ("quarentena", "Em quarentena"),
                            ("liberada", "Liberada"),
                            ("descartada", "Descartada"),
                        ],
                        db_index=True,
                        default="quarentena",
                        help_text="Bolsa fica em quarentena até a sorologia liberar (workflow em H2).",
                        max_length=16,
                        verbose_name="Situação sorológica",
                    ),
                ),
                (
                    "stock_status",
                    models.CharField(
                        choices=[
                            ("disponivel", "Disponível"),
                            ("reservada", "Reservada"),
                            ("transfundida", "Transfundida"),
                            ("descartada", "Descartada"),
                            ("vencida", "Vencida"),
                        ],
                        db_index=True,
                        default="disponivel",
                        max_length=16,
                        verbose_name="Situação de estoque",
                    ),
                ),
                ("irradiada", models.BooleanField(default=False, verbose_name="Irradiada")),
                (
                    "leucodepletada",
                    models.BooleanField(default=False, verbose_name="Leucodepletada"),
                ),
                ("aferese", models.BooleanField(default=False, verbose_name="Aférese")),
                (
                    "lot",
                    models.CharField(blank=True, default="", max_length=64, verbose_name="Lote"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.bloodcomponentcatalog",
                        verbose_name="Hemocomponente",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blood_bags_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bolsa de Sangue",
                "verbose_name_plural": "Bolsas de Sangue",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["component", "abo", "rh_factor"], name="emr_bag_comp_type_idx"
                    ),
                    models.Index(
                        fields=["serology_status", "stock_status"], name="emr_bag_serol_stock_idx"
                    ),
                    models.Index(fields=["expiry_date"], name="emr_bag_expiry_idx"),
                ],
            },
        ),
    ]
