# Generated by Django 5.2 on 2026-07-28 23:26

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0053_patient_abo_patient_antibody_screen_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BloodDonor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "full_name",
                    models.CharField(db_index=True, max_length=255, verbose_name="Nome completo"),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=14, verbose_name="CPF"
                    ),
                ),
                (
                    "abo",
                    models.CharField(
                        blank=True,
                        choices=[("A", "A"), ("B", "B"), ("AB", "AB"), ("O", "O")],
                        max_length=2,
                        verbose_name="Grupo ABO",
                    ),
                ),
                (
                    "rh_factor",
                    models.CharField(
                        blank=True,
                        choices=[("positivo", "Positivo"), ("negativo", "Negativo")],
                        max_length=8,
                        verbose_name="Fator Rh",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="Data de nascimento"),
                ),
                (
                    "last_donation",
                    models.DateField(blank=True, null=True, verbose_name="Última doação"),
                ),
                ("apto", models.BooleanField(default=True, verbose_name="Apto a doar")),
                ("notes", models.TextField(blank=True, default="", verbose_name="Observações")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Doador de Sangue",
                "verbose_name_plural": "Doadores de Sangue",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="BloodBagSerology",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "hiv",
                    models.CharField(
                        choices=[
                            ("nao_reagente", "Não reagente"),
                            ("reagente", "Reagente"),
                            ("indeterminado", "Indeterminado"),
                        ],
                        default="nao_reagente",
                        max_length=16,
                        verbose_name="HIV",
                    ),
                ),
                (
                    "hbsag",
                    models.CharField(
                        choices=[
                            ("nao_reagente", "Não reagente"),
                            ("reagente", "Reagente"),
                            ("indeterminado", "Indeterminado"),
                        ],
                        default="nao_reagente",
                        max_length=16,
                        verbose_name="HBsAg",
                    ),
                ),
                (
                    "anti_hbc",
                    models.CharField(
                        choices=[
                            ("nao_reagente", "Não reagente"),
                            ("reagente", "Reagente"),
                            ("indeterminado", "Indeterminado"),
                        ],
                        default="nao_reagente",
                        max_length=16,
                        verbose_name="Anti-HBc",
                    ),
                ),
                (
                    "anti_hcv",
                    models.CharField(
                        choices=[
                            ("nao_reagente", "Não reagente"),
                            ("reagente", "Reagente"),
                            ("indeterminado", "Indeterminado"),
                        ],
                        default="nao_reagente",
                        max_length=16,
                        verbose_name="Anti-HCV",
                    ),
                ),
                (
                    "sifilis",
                    models.CharField(
                        choices=[
                            ("nao_reagente", "Não reagente"),
                            ("reagente", "Reagente"),
                            ("indeterminado", "Indeterminado"),
                        ],
                        default="nao_reagente",
                        max_length=16,
                        verbose_name="Sífilis",
                    ),
                ),
                (
                    "chagas",
                    models.CharField(
                        choices=[
                            ("nao_reagente", "Não reagente"),
                            ("reagente", "Reagente"),
                            ("indeterminado", "Indeterminado"),
                        ],
                        default="nao_reagente",
                        max_length=16,
                        verbose_name="Doença de Chagas",
                    ),
                ),
                (
                    "htlv",
                    models.CharField(
                        choices=[
                            ("nao_reagente", "Não reagente"),
                            ("reagente", "Reagente"),
                            ("indeterminado", "Indeterminado"),
                        ],
                        default="nao_reagente",
                        max_length=16,
                        verbose_name="HTLV I/II",
                    ),
                ),
                ("tested_at", models.DateTimeField(auto_now_add=True, verbose_name="Testado em")),
                ("notes", models.TextField(blank=True, default="", verbose_name="Observações")),
                (
                    "bag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="serologies",
                        to="emr.bloodbag",
                        verbose_name="Bolsa",
                    ),
                ),
                (
                    "tested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blood_serologies_tested",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Testado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sorologia de Bolsa",
                "verbose_name_plural": "Sorologias de Bolsas",
                "ordering": ["-tested_at"],
                "indexes": [
                    models.Index(fields=["bag", "-tested_at"], name="emr_serol_bag_tested_idx")
                ],
            },
        ),
    ]
