# Generated by Django 5.2 on 2026-07-28 23:28

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_bloodcomponentcatalog"),
        ("emr", "0054_blooddonor_bloodbagserology"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransfusionRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(
                        help_text="Número de unidades solicitadas.",
                        verbose_name="Quantidade (unidades)",
                    ),
                ),
                ("indicacao", models.TextField(verbose_name="Indicação clínica")),
                (
                    "cid",
                    models.CharField(blank=True, default="", max_length=10, verbose_name="CID"),
                ),
                (
                    "urgencia",
                    models.CharField(
                        choices=[
                            ("rotina", "Rotina"),
                            ("urgencia", "Urgência"),
                            ("emergencia", "Emergência"),
                        ],
                        db_index=True,
                        default="rotina",
                        max_length=16,
                        verbose_name="Urgência",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("solicitada", "Solicitada"),
                            ("reservada", "Reservada"),
                            ("liberada", "Liberada"),
                            ("transfundida", "Transfundida"),
                            ("cancelada", "Cancelada"),
                        ],
                        db_index=True,
                        default="solicitada",
                        max_length=16,
                        verbose_name="Situação",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfusion_requests",
                        to="emr.admission",
                        verbose_name="Internação",
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.bloodcomponentcatalog",
                        verbose_name="Hemocomponente",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfusion_requests_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "emergency_encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfusion_requests",
                        to="emr.emergencyencounter",
                        verbose_name="Boletim de emergência",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfusion_requests",
                        to="emr.encounter",
                        verbose_name="Atendimento",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfusion_requests",
                        to="emr.patient",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfusion_requests",
                        to="emr.professional",
                        verbose_name="Solicitante",
                    ),
                ),
                (
                    "surgical_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfusion_requests",
                        to="emr.surgicalcase",
                        verbose_name="Caso cirúrgico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Requisição Transfusional",
                "verbose_name_plural": "Requisições Transfusionais",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CrossMatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "abo_compativel",
                    models.BooleanField(default=False, verbose_name="ABO compatível"),
                ),
                ("rh_compativel", models.BooleanField(default=False, verbose_name="Rh compatível")),
                (
                    "crossmatch_resultado",
                    models.CharField(
                        choices=[("compativel", "Compatível"), ("incompativel", "Incompatível")],
                        default="incompativel",
                        max_length=16,
                        verbose_name="Resultado da prova cruzada",
                    ),
                ),
                ("tested_at", models.DateTimeField(auto_now_add=True, verbose_name="Testado em")),
                ("notes", models.TextField(blank=True, default="", verbose_name="Observações")),
                (
                    "bag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="crossmatches",
                        to="emr.bloodbag",
                        verbose_name="Bolsa",
                    ),
                ),
                (
                    "tested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crossmatches_tested",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Testado por",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crossmatches",
                        to="emr.transfusionrequest",
                        verbose_name="Requisição",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prova de Compatibilidade",
                "verbose_name_plural": "Provas de Compatibilidade",
                "ordering": ["-tested_at"],
            },
        ),
        migrations.AddIndex(
            model_name="transfusionrequest",
            index=models.Index(fields=["patient", "status"], name="emr_treq_patient_status_idx"),
        ),
        migrations.AddIndex(
            model_name="transfusionrequest",
            index=models.Index(fields=["status", "urgencia"], name="emr_treq_status_urg_idx"),
        ),
        migrations.AddIndex(
            model_name="crossmatch",
            index=models.Index(fields=["request", "bag"], name="emr_xm_request_bag_idx"),
        ),
    ]
