# Generated by Django 5.2 on 2026-07-29 01:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0055_transfusionrequest_crossmatch_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransfusionAdministration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Início"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Término"),
                ),
                (
                    "volume_ml",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Volume infundido (mL)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("em_andamento", "Em andamento"),
                            ("concluida", "Concluída"),
                            ("interrompida", "Interrompida"),
                        ],
                        db_index=True,
                        default="em_andamento",
                        max_length=16,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "patient_barcode_scanned",
                    models.CharField(blank=True, max_length=64, verbose_name="Pulseira lida"),
                ),
                (
                    "bag_barcode_scanned",
                    models.CharField(blank=True, max_length=64, verbose_name="DIN lido"),
                ),
                (
                    "checagem_verified",
                    models.BooleanField(default=False, verbose_name="Checagem verificada"),
                ),
                (
                    "checagem_override_reason",
                    models.TextField(blank=True, verbose_name="Justificativa da exceção"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "administered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfusion_administrations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Administrado por",
                    ),
                ),
                (
                    "bag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="administrations",
                        to="emr.bloodbag",
                        verbose_name="Bolsa",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfusion_administrations",
                        to="emr.patient",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="administrations",
                        to="emr.transfusionrequest",
                        verbose_name="Requisição",
                    ),
                ),
                (
                    "witness",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="witnessed_transfusion_administrations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Testemunha (2ª checagem)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Administração Transfusional",
                "verbose_name_plural": "Administrações Transfusionais",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransfusionReaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("febril_nao_hemolitica", "Febril não hemolítica"),
                            ("alergica", "Alérgica"),
                            ("hemolitica_aguda", "Hemolítica aguda"),
                            ("trali", "TRALI (lesão pulmonar aguda)"),
                            ("taco", "TACO (sobrecarga circulatória)"),
                            ("contaminacao_bacteriana", "Contaminação bacteriana"),
                            ("outra", "Outra"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "gravidade",
                    models.CharField(
                        choices=[
                            ("leve", "Leve"),
                            ("moderada", "Moderada"),
                            ("grave", "Grave"),
                            ("obito", "Óbito"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="Gravidade",
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                ("conduta", models.TextField(blank=True, default="", verbose_name="Conduta")),
                (
                    "notificado_hemovigilancia",
                    models.BooleanField(default=False, verbose_name="Notificado à hemovigilância"),
                ),
                ("occurred_at", models.DateTimeField(db_index=True, verbose_name="Ocorrido em")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "administration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reactions",
                        to="emr.transfusionadministration",
                        verbose_name="Administração",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfusion_reactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reactions",
                        to="emr.transfusionrequest",
                        verbose_name="Requisição",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reação Transfusional",
                "verbose_name_plural": "Reações Transfusionais",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.AddIndex(
            model_name="transfusionadministration",
            index=models.Index(fields=["request", "status"], name="emr_tadm_request_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="transfusionadministration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "em_andamento")),
                fields=("request",),
                name="emr_tadm_one_active_per_request",
            ),
        ),
        migrations.AddIndex(
            model_name="transfusionreaction",
            index=models.Index(fields=["administration"], name="emr_treac_adm_idx"),
        ),
        migrations.AddIndex(
            model_name="transfusionreaction",
            index=models.Index(fields=["tipo", "gravidade"], name="emr_treac_tipo_grav_idx"),
        ),
    ]
