# Generated by Django 5.2 on 2026-07-29 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_simpromaterial"),
        ("emr", "0056_transfusionadministration_transfusionreaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="surgicalmaterial",
            name="simpro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="surgical_materials",
                to="core.simpromaterial",
                verbose_name="Material Simpro (catálogo)",
            ),
        ),
    ]
