# Generated by Django 5.2 on 2026-07-29 09:45

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0057_surgicalmaterial_simpro"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnestheticRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "technique",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("geral", "Geral"),
                            ("raqui", "Raquianestesia"),
                            ("peridural", "Peridural"),
                            ("local", "Local"),
                            ("sedacao", "Sedação"),
                        ],
                        default="",
                        max_length=16,
                        verbose_name="Técnica anestésica",
                    ),
                ),
                (
                    "asa_classification",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("I", "ASA I — paciente saudável"),
                            ("II", "ASA II — doença sistêmica leve"),
                            ("III", "ASA III — doença sistêmica grave"),
                            ("IV", "ASA IV — doença sistêmica grave, ameaça constante à vida"),
                            ("V", "ASA V — moribundo, não sobrevive sem cirurgia"),
                            ("VI", "ASA VI — morte encefálica (doador de órgãos)"),
                            ("IE", "ASA I-E — emergência"),
                            ("IIE", "ASA II-E — emergência"),
                            ("IIIE", "ASA III-E — emergência"),
                            ("IVE", "ASA IV-E — emergência"),
                            ("VE", "ASA V-E — emergência"),
                        ],
                        default="",
                        max_length=8,
                        verbose_name="Classificação ASA",
                    ),
                ),
                (
                    "anesthesia_start",
                    models.DateTimeField(blank=True, null=True, verbose_name="Início da anestesia"),
                ),
                (
                    "anesthesia_end",
                    models.DateTimeField(blank=True, null=True, verbose_name="Fim da anestesia"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "anesthesiologist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anesthetic_records",
                        to="emr.professional",
                        verbose_name="Anestesista responsável",
                    ),
                ),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anesthetic_record",
                        to="emr.surgicalcase",
                        verbose_name="Caso cirúrgico",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anesthetic_records_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ficha Anestésica",
                "verbose_name_plural": "Fichas Anestésicas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnestheticEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Horário"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("droga", "Droga / medicamento"),
                            ("vital", "Sinal vital"),
                            ("evento", "Evento / intercorrência"),
                            ("ventilacao", "Ventilação"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="Tipo",
                    ),
                ),
                ("description", models.CharField(max_length=300, verbose_name="Descrição")),
                ("dose", models.CharField(blank=True, max_length=100, verbose_name="Dose")),
                ("value", models.CharField(blank=True, max_length=200, verbose_name="Valor")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anesthetic_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="emr.anestheticrecord",
                        verbose_name="Ficha anestésica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento Anestésico",
                "verbose_name_plural": "Eventos Anestésicos",
                "ordering": ["timestamp", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="anestheticrecord",
            index=models.Index(fields=["case"], name="emr_anestrec_case_idx"),
        ),
        migrations.AddIndex(
            model_name="anestheticevent",
            index=models.Index(fields=["record", "timestamp"], name="emr_anestevt_rec_dt_idx"),
        ),
    ]
