# Generated by Django 5.2 on 2026-07-29 11:19

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0058_anestheticrecord_anestheticevent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PacuRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "admitted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Entrada na SRPA"),
                ),
                (
                    "aldrete_admission",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Escore de Aldrete na admissão à SRPA (0–10).",
                        null=True,
                        verbose_name="Aldrete na entrada",
                    ),
                ),
                (
                    "aldrete_discharge",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Escore de Aldrete na alta da SRPA (0–10; ≥ 9 é o critério clássico de alta).",
                        null=True,
                        verbose_name="Aldrete na alta",
                    ),
                ),
                (
                    "discharged_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Alta da SRPA"),
                ),
                (
                    "discharge_destination",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("enfermaria", "Enfermaria"),
                            ("uti", "UTI"),
                            ("alta", "Alta (casa)"),
                            ("obito", "Óbito"),
                        ],
                        default="",
                        max_length=16,
                        verbose_name="Destino na alta",
                    ),
                ),
                (
                    "discharge_criteria_met",
                    models.BooleanField(
                        default=False,
                        help_text="Critérios de alta da SRPA atingidos (decisão clínica).",
                        verbose_name="Critérios de alta atingidos",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pacu_admissions",
                        to="emr.professional",
                        verbose_name="Recebido por",
                    ),
                ),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pacu_record",
                        to="emr.surgicalcase",
                        verbose_name="Caso cirúrgico",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pacu_records_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de SRPA (Recuperação Pós-Anestésica)",
                "verbose_name_plural": "Registros de SRPA (Recuperação Pós-Anestésica)",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PacuAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "assessed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Avaliado em"
                    ),
                ),
                (
                    "aldrete_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Escore de Aldrete agregado (0–10).",
                        null=True,
                        verbose_name="Escore de Aldrete",
                    ),
                ),
                (
                    "consciousness",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Componente Aldrete (0–2).",
                        null=True,
                        verbose_name="Consciência",
                    ),
                ),
                (
                    "respiration",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Componente Aldrete (0–2).",
                        null=True,
                        verbose_name="Respiração",
                    ),
                ),
                (
                    "circulation",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Componente Aldrete (0–2).",
                        null=True,
                        verbose_name="Circulação",
                    ),
                ),
                (
                    "activity",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Componente Aldrete (0–2).",
                        null=True,
                        verbose_name="Atividade",
                    ),
                ),
                (
                    "oxygen",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Componente Aldrete (0–2).",
                        null=True,
                        verbose_name="Saturação de O₂",
                    ),
                ),
                (
                    "pain_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Escala de dor (0–10).",
                        null=True,
                        verbose_name="Escore de dor",
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=300, verbose_name="Observações")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pacu_assessments",
                        to="emr.professional",
                        verbose_name="Registrado por",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="emr.pacurecord",
                        verbose_name="Registro de SRPA",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação de SRPA",
                "verbose_name_plural": "Avaliações de SRPA",
                "ordering": ["assessed_at", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="pacurecord",
            index=models.Index(fields=["case"], name="emr_pacurec_case_idx"),
        ),
        migrations.AddIndex(
            model_name="pacuassessment",
            index=models.Index(fields=["record", "assessed_at"], name="emr_pacuassess_rec_dt_idx"),
        ),
    ]
