# Generated by Django 5.2 on 2026-07-29 13:31

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0059_pacurecord_pacuassessment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="operatingroom",
            name="turnover_minutes",
            field=models.PositiveSmallIntegerField(
                default=30,
                help_text="Intervalo mínimo de higienização/preparo entre cirurgias, em minutos.",
                verbose_name="Turnover (min)",
            ),
        ),
        migrations.CreateModel(
            name="RoomTurnover",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Momento em que a sala foi liberada / início do turnover.",
                        verbose_name="Início do turnover",
                    ),
                ),
                (
                    "cleaning_done_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Limpeza concluída em"
                    ),
                ),
                (
                    "ready_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Sala pronta em"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aguardando", "Aguardando limpeza"),
                            ("em_limpeza", "Em limpeza"),
                            ("pronta", "Pronta"),
                        ],
                        db_index=True,
                        default="aguardando",
                        max_length=12,
                        verbose_name="Situação",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case_in",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="turnover_in",
                        to="emr.surgicalcase",
                        verbose_name="Próxima cirurgia",
                    ),
                ),
                (
                    "case_out",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="turnover_out",
                        to="emr.surgicalcase",
                        verbose_name="Cirurgia que saiu",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="room_turnovers_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "operating_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="turnovers",
                        to="emr.operatingroom",
                        verbose_name="Sala cirúrgica",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="room_turnovers",
                        to="emr.professional",
                        verbose_name="Higienizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Turnover de Sala",
                "verbose_name_plural": "Turnovers de Sala",
                "ordering": ["-started_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["operating_room", "started_at"], name="emr_turnover_or_dt_idx"
                    )
                ],
            },
        ),
    ]
