# Generated by Django 5.2 on 2026-07-29 13:57

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0060_operatingroom_turnover_minutes_roomturnover"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MicrobiologyResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "culture_result",
                    models.CharField(
                        choices=[
                            ("positiva", "Positiva"),
                            ("negativa", "Negativa"),
                            ("contaminada", "Contaminada"),
                            ("pendente", "Pendente"),
                        ],
                        db_index=True,
                        default="pendente",
                        max_length=12,
                    ),
                ),
                ("specimen", models.CharField(blank=True, max_length=120)),
                ("collected_at", models.DateTimeField(blank=True, null=True)),
                ("gram_stain", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="microbiology_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="microbiology_result",
                        to="emr.laborderitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IsolatedOrganism",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("organism_name", models.CharField(max_length=160)),
                ("colony_count", models.CharField(blank=True, max_length=60)),
                ("is_significant", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organisms",
                        to="emr.microbiologyresult",
                    ),
                ),
            ],
            options={
                "ordering": ["organism_name"],
            },
        ),
        migrations.CreateModel(
            name="AntibiogramEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("antibiotic", models.CharField(max_length=120)),
                ("method", models.CharField(blank=True, max_length=60)),
                ("mic_value", models.CharField(blank=True, max_length=40)),
                (
                    "interpretation",
                    models.CharField(
                        choices=[
                            ("S", "Sensível"),
                            ("I", "Intermediário"),
                            ("R", "Resistente"),
                            ("SDD", "Sensível dose-dependente"),
                        ],
                        max_length=3,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organism",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="antibiogram",
                        to="emr.isolatedorganism",
                    ),
                ),
            ],
            options={
                "ordering": ["antibiotic"],
                "indexes": [
                    models.Index(
                        fields=["antibiotic", "interpretation"], name="emr_antibiogram_surveil_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organism", "antibiotic"), name="emr_antibiogram_org_drug_unique"
                    )
                ],
            },
        ),
    ]
