# Generated by Django 5.2 on 2026-07-29 14:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0061_microbiologyresult_isolatedorganism_antibiogramentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PathologyReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("report_number", models.CharField(blank=True, max_length=40)),
                ("clinical_history", models.TextField(blank=True)),
                ("specimen_description", models.TextField(blank=True)),
                ("macroscopy", models.TextField(blank=True)),
                ("microscopy", models.TextField(blank=True)),
                ("immunohistochemistry", models.TextField(blank=True)),
                ("diagnosis", models.TextField(blank=True)),
                ("cid_o_topography", models.CharField(blank=True, max_length=16)),
                ("cid_o_morphology", models.CharField(blank=True, max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("preliminar", "Preliminar"),
                            ("final", "Final"),
                        ],
                        db_index=True,
                        default="pendente",
                        max_length=12,
                    ),
                ),
                ("reported_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pathology_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pathology_report",
                        to="emr.laborderitem",
                    ),
                ),
                (
                    "pathologist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pathology_reports",
                        to="emr.professional",
                    ),
                ),
                (
                    "surgical_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pathology_reports",
                        to="emr.surgicalcase",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PathologySpecimen",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("label", models.CharField(max_length=60)),
                ("description", models.TextField(blank=True)),
                ("site", models.CharField(blank=True, max_length=160)),
                ("blocks_count", models.PositiveSmallIntegerField(default=0)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specimens",
                        to="emr.pathologyreport",
                    ),
                ),
            ],
            options={
                "ordering": ["label"],
                "indexes": [models.Index(fields=["report"], name="emr_pathspecimen_report_idx")],
            },
        ),
    ]
