# Generated by Django 5.2 on 2026-07-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0062_pathologyreport_pathologyspecimen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admissionevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("admit", "Admissão"),
                    ("transfer", "Transferência"),
                    ("discharge", "Alta"),
                    ("cancel", "Cancelamento"),
                    ("plan_discharge", "Alta planejada"),
                ],
                db_index=True,
                max_length=16,
                verbose_name="Tipo de evento",
            ),
        ),
    ]
