# Generated by Django 5.2 on 2026-07-29 18:33

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0063_planned_discharge_event"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BedStatusEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("livre", "Livre"),
                            ("ocupado", "Ocupado"),
                            ("higienizacao", "Em higienização"),
                            ("bloqueado", "Bloqueado"),
                            ("reservado", "Reservado"),
                            ("interditado", "Interditado"),
                        ],
                        max_length=16,
                        verbose_name="Situação anterior",
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("livre", "Livre"),
                            ("ocupado", "Ocupado"),
                            ("higienizacao", "Em higienização"),
                            ("bloqueado", "Bloqueado"),
                            ("reservado", "Reservado"),
                            ("interditado", "Interditado"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="Nova situação",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="Motivo")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bed_status_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsável",
                    ),
                ),
                (
                    "bed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="status_events",
                        to="emr.bed",
                        verbose_name="Leito",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de leito",
                "verbose_name_plural": "Eventos de leito",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(fields=["bed", "created_at"], name="emr_bedevt_bed_dt_idx")
                ],
            },
        ),
    ]
