# Generated by Django 5.2 on 2026-07-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0064_bed_status_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="admission",
            name="isolation_precaution",
            field=models.CharField(
                choices=[
                    ("nenhuma", "Nenhuma"),
                    ("contato", "Contato"),
                    ("goticula", "Gotícula"),
                    ("aerossol", "Aerossol"),
                    ("protetor", "Protetor (reverso)"),
                ],
                db_index=True,
                default="nenhuma",
                max_length=16,
                verbose_name="Precaução de isolamento",
            ),
        ),
    ]
