# Generated by Django 5.2 on 2026-07-31 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_cido_ref_len"),
        ("emr", "0065_admission_isolation_precaution"),
    ]

    operations = [
        migrations.AddField(
            model_name="pathologyreport",
            name="cid_o_morphology_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.cidomorphology",
                verbose_name="CID-O morfologia (governado)",
            ),
        ),
        migrations.AddField(
            model_name="pathologyreport",
            name="cid_o_morphology_unmatched",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pathologyreport",
            name="cid_o_topography_cid10",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.cid10code",
                verbose_name="CID-O topografia (governado)",
            ),
        ),
        migrations.AddField(
            model_name="pathologyreport",
            name="cid_o_topography_unmatched",
            field=models.BooleanField(default=False),
        ),
    ]
