# Generated by Django 5.2 on 2026-08-04 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_anvisa_presentation"),
        ("emr", "0066_pathology_cido_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="surgicalprocedure",
            name="sigtap",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="surgical_procedures",
                to="core.sigtapprocedure",
                verbose_name="Procedimento (SIGTAP/SUS)",
            ),
        ),
    ]
