# Generated by Django 5.2 on 2026-08-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0067_surgical_procedure_sigtap"),
    ]

    operations = [
        migrations.AddField(
            model_name="admission",
            name="carater_atendimento",
            field=models.CharField(
                blank=True,
                choices=[("1", "Eletivo"), ("2", "Urgência/Emergência")],
                default="",
                help_text="dm_caraterAtendimento — eletivo ou urgência/emergência, para a guia TISS.",
                max_length=1,
                verbose_name="Caráter do atendimento (TISS)",
            ),
        ),
        migrations.AddField(
            model_name="admission",
            name="disposition_ans_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("11", "Alta melhorado"),
                    ("12", "Alta a pedido"),
                    ("14", "Alta por evasão"),
                    ("15", "Alta com previsão de retorno para acompanhamento do paciente"),
                    ("16", "Alta por outros motivos"),
                    ("18", "Alta da puérpera e do recém-nascido"),
                    ("19", "Alta da puérpera"),
                    ("21", "Transferência para internação domiciliar"),
                    ("22", "Permanência por características próprias da doença"),
                    ("23", "Permanência por intercorrência"),
                    ("24", "Permanência por impossibilidade social"),
                    ("25", "Transferência para outro estabelecimento"),
                    ("26", "Permanência por outros motivos"),
                    ("27", "Óbito com declaração de óbito fornecida pelo médico assistente"),
                    ("28", "Óbito com declaração de óbito fornecida pelo IML"),
                    ("31", "Óbito com declaração de óbito fornecida pelo SVO"),
                    ("32", "Encerramento administrativo"),
                    ("41", "Código 41 (rótulo a confirmar no manual ANS)"),
                    ("42", "Código 42 (rótulo a confirmar no manual ANS)"),
                    ("43", "Código 43 (rótulo a confirmar no manual ANS)"),
                    ("51", "Código 51 (rótulo a confirmar no manual ANS)"),
                    ("61", "Código 61 (rótulo a confirmar no manual ANS)"),
                    ("62", "Código 62 (rótulo a confirmar no manual ANS)"),
                    ("63", "Código 63 (rótulo a confirmar no manual ANS)"),
                    ("64", "Código 64 (rótulo a confirmar no manual ANS)"),
                    ("65", "Código 65 (rótulo a confirmar no manual ANS)"),
                    ("66", "Código 66 (rótulo a confirmar no manual ANS)"),
                    ("67", "Código 67 (rótulo a confirmar no manual ANS)"),
                ],
                default="",
                help_text="dm_motivoSaida — motivo de encerramento ANS, para a guia TISS de internação.",
                max_length=2,
                verbose_name="Motivo de encerramento (TISS)",
            ),
        ),
        migrations.AddField(
            model_name="admission",
            name="regime_internacao",
            field=models.CharField(
                blank=True,
                choices=[("1", "Hospitalar"), ("2", "Hospital-dia"), ("3", "Domiciliar")],
                default="",
                help_text="dm_regimeInternacao — hospitalar/hospital-dia/domiciliar, para a guia TISS.",
                max_length=1,
                verbose_name="Regime de internação (TISS)",
            ),
        ),
        migrations.AddField(
            model_name="admission",
            name="tipo_internacao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Clínico"),
                    ("2", "Cirúrgico"),
                    ("3", "Obstétrico"),
                    ("4", "Pediátrico"),
                    ("5", "Psiquiátrico"),
                ],
                default="",
                help_text="dm_tipoInternacao — especialidade da internação, para a guia TISS.",
                max_length=1,
                verbose_name="Tipo de internação (TISS)",
            ),
        ),
    ]
