# Generated by Django 5.2 on 2026-09-26 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0068_admission_tiss_taxonomies"),
    ]

    operations = [
        migrations.AddField(
            model_name="aisafetyalert",
            name="explica",
            field=models.ForeignKey(
                blank=True,
                help_text="Só para alert_type='dose_explicacao': o alerta do MOTOR (source='engine', alert_type='dose') que esta linha explica. O LLM nunca decide sozinho.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="explanations",
                to="emr.aisafetyalert",
            ),
        ),
        migrations.AlterField(
            model_name="aisafetyalert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("drug_interaction", "Interação medicamentosa"),
                    ("allergy", "Alergia cruzada"),
                    ("dose", "Dose fora do intervalo"),
                    ("contraindication", "Contraindicação"),
                    ("dose_explicacao", "Explicação de dose (LLM, não decide)"),
                ],
                max_length=30,
            ),
        ),
    ]
