# Generated by Django 5.2 on 2026-07-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConcessionService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=40, verbose_name="Código")),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "modality",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Modalidade/categoria"
                    ),
                ),
                (
                    "tuss_code",
                    models.CharField(blank=True, max_length=20, verbose_name="TUSS (opcional)"),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["code"],
                "constraints": [
                    models.UniqueConstraint(fields=("code",), name="concession_service_code_unique")
                ],
            },
        ),
    ]
