# Generated by Django 5.2 on 2026-07-25 23:10

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concession", "0001_initial"),
        ("organization", "0001_initial"),
        ("pharmacy", "0031_controlledsubstanceledger_controlledledgerclosing_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PickList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("picking", "Em separação"),
                            ("picked", "Separada"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConcessionContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome do contrato")),
                (
                    "client_name",
                    models.CharField(blank=True, max_length=200, verbose_name="Cliente"),
                ),
                (
                    "monthly_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Valor fixo mensal do contrato (opcional).",
                        max_digits=12,
                        null=True,
                        verbose_name="Valor mensal",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Início da vigência")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Fim da vigência"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Ativo"),
                            ("EXPIRED", "Expirado"),
                            ("TERMINATED", "Rescindido"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="concession_contracts",
                        to="organization.legalentity",
                        verbose_name="Cliente (entidade legal)",
                    ),
                ),
                (
                    "units",
                    models.ManyToManyField(
                        blank=True,
                        related_name="concession_contracts",
                        to="organization.facility",
                        verbose_name="Unidades",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrato de concessão",
                "verbose_name_plural": "Contratos de concessão",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Dispatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("manifest_code", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("in_transit", "Em trânsito"),
                            ("delivered", "Entregue"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "destination_facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="concession_dispatches",
                        to="organization.facility",
                    ),
                ),
                (
                    "destination_warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="concession_inbound_dispatches",
                        to="pharmacy.warehouse",
                    ),
                ),
                (
                    "source_warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="concession_dispatches",
                        to="pharmacy.warehouse",
                    ),
                ),
                (
                    "pick_list",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispatch",
                        to="concession.picklist",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DispatchItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "received_qty",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
                ),
                (
                    "dispatch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="concession.dispatch",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="pharmacy.material",
                    ),
                ),
                (
                    "source_stock_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="pharmacy.stockitem",
                    ),
                ),
            ],
            options={
                "ordering": ["material__name"],
            },
        ),
        migrations.CreateModel(
            name="DispatchDiscrepancy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("missing", "Faltante"),
                            ("damaged", "Avariado"),
                            ("extra", "Excedente"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispatch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discrepancies",
                        to="concession.dispatch",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="pharmacy.material",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dispatch_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discrepancies",
                        to="concession.dispatchitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "asset_tag",
                    models.CharField(max_length=40, unique=True, verbose_name="Patrimônio/tag"),
                ),
                ("name", models.CharField(blank=True, max_length=200, verbose_name="Nome")),
                ("model", models.CharField(max_length=120, verbose_name="Modelo")),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=120, verbose_name="Número de série"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Ativo"),
                            ("IN_MAINTENANCE", "Em manutenção"),
                            ("BACKUP", "Reserva"),
                            ("WRITTEN_OFF", "Baixado"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "ownership",
                    models.CharField(
                        choices=[
                            ("OPERATOR", "Operadora"),
                            ("CLIENT", "Cliente"),
                            ("DOCTOR", "Médico"),
                        ],
                        default="OPERATOR",
                        max_length=20,
                    ),
                ),
                (
                    "purchase_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Custo de aquisição",
                    ),
                ),
                (
                    "useful_life_months",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Vida útil (meses)"
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(blank=True, null=True, verbose_name="Data de aquisição"),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vazio = no armazém (não implantado).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="concession_assets",
                        to="organization.facility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipamento (comodato)",
                "verbose_name_plural": "Equipamentos (comodato)",
                "ordering": ["asset_tag"],
            },
        ),
        migrations.CreateModel(
            name="AssetService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enabling_assets",
                        to="concession.concessionservice",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enabled_services",
                        to="concession.equipmentasset",
                    ),
                ),
            ],
            options={
                "ordering": ["asset", "service"],
            },
        ),
        migrations.CreateModel(
            name="AssetMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("DEPLOYMENT", "Implantação"),
                            ("RETRIEVAL", "Recolhimento"),
                            ("TRANSFER", "Transferência"),
                            ("SWAP", "Troca"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="concession_movements_from",
                        to="organization.facility",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="concession_movements_to",
                        to="organization.facility",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="concession.equipmentasset",
                    ),
                ),
                (
                    "swapped_with",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="swap_movements",
                        to="concession.equipmentasset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimentação de equipamento",
                "verbose_name_plural": "Movimentações de equipamento",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição do problema")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Aberto"),
                            ("IN_PROGRESS", "Em andamento"),
                            ("COMPLETED", "Concluído"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Custo do reparo",
                    ),
                ),
                ("evidence_url", models.URLField(blank=True, verbose_name="Evidência (foto)")),
                ("resolution", models.TextField(blank=True, verbose_name="Resolução")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_tickets",
                        to="concession.equipmentasset",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="concession_maintenance_tickets",
                        to="organization.facility",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chamado de manutenção",
                "verbose_name_plural": "Chamados de manutenção",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProofOfDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("received_by", models.CharField(max_length=200)),
                ("signature_ref", models.CharField(blank=True, max_length=300)),
                (
                    "geo_lat",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "geo_lng",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                ("delivered_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "captured_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dispatch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proof_of_delivery",
                        to="concession.dispatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comprovante de entrega",
                "verbose_name_plural": "Comprovantes de entrega",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RequisitionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="pharmacy.material",
                    ),
                ),
            ],
            options={
                "ordering": ["material__name"],
            },
        ),
        migrations.CreateModel(
            name="PickItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "picked_qty",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=12),
                ),
                ("is_picked", models.BooleanField(db_index=True, default=False)),
                ("picked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="pharmacy.material",
                    ),
                ),
                (
                    "source_stock_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="pharmacy.stockitem",
                    ),
                ),
                (
                    "pick_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="concession.picklist",
                    ),
                ),
                (
                    "requisition_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pick_item",
                        to="concession.requisitionitem",
                    ),
                ),
            ],
            options={
                "ordering": ["material__name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("1"),
                        help_text="Quantidade do insumo consumida por exame.",
                        max_digits=12,
                        verbose_name="Quantidade por exame",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="concession_recipes",
                        to="pharmacy.material",
                        verbose_name="Insumo",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to="concession.concessionservice",
                        verbose_name="Serviço",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receita de serviço (insumo)",
                "verbose_name_plural": "Receitas de serviço (insumos)",
                "ordering": ["service__code", "material__name"],
            },
        ),
        migrations.CreateModel(
            name="SupplyRequisition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("submitted", "Enviada"),
                            ("approved", "Aprovada"),
                            ("fulfilled", "Atendida"),
                            ("cancelled", "Cancelada"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supply_requisitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requesting_facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supply_requisitions",
                        to="organization.facility",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="requisitionitem",
            name="requisition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="concession.supplyrequisition",
            ),
        ),
        migrations.AddField(
            model_name="picklist",
            name="requisition",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pick_list",
                to="concession.supplyrequisition",
            ),
        ),
        migrations.CreateModel(
            name="ContractServicePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Preço"),
                ),
                (
                    "is_billable",
                    models.BooleanField(
                        default=True,
                        help_text="Se falso, a receita é 0 mas o volume ainda conta.",
                        verbose_name="Faturável",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="concession.concessioncontract",
                        verbose_name="Contrato",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contract_prices",
                        to="concession.concessionservice",
                        verbose_name="Serviço",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concession_service_prices",
                        to="organization.facility",
                        verbose_name="Unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Preço de serviço do contrato",
                "verbose_name_plural": "Preços de serviço do contrato",
                "ordering": ["service__code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("contract", "service"),
                        name="concession_price_contract_service_unique",
                    ),
                    models.UniqueConstraint(
                        fields=("unit", "service"), name="concession_price_unit_service_unique"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="dispatchitem",
            index=models.Index(fields=["dispatch"], name="concession__dispatc_5d1b07_idx"),
        ),
        migrations.AddIndex(
            model_name="dispatchdiscrepancy",
            index=models.Index(fields=["dispatch", "type"], name="concession__dispatc_95b25c_idx"),
        ),
        migrations.AddConstraint(
            model_name="assetservice",
            constraint=models.UniqueConstraint(
                fields=("asset", "service"), name="concession_asset_service_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="assetmovement",
            index=models.Index(fields=["asset"], name="concession__asset_i_b3ad51_idx"),
        ),
        migrations.AddIndex(
            model_name="assetmovement",
            index=models.Index(fields=["movement_type"], name="concession__movemen_2d3281_idx"),
        ),
        migrations.AddIndex(
            model_name="maintenanceticket",
            index=models.Index(fields=["asset"], name="concession__asset_i_d7cf63_idx"),
        ),
        migrations.AddIndex(
            model_name="maintenanceticket",
            index=models.Index(fields=["status"], name="concession__status_ec231a_idx"),
        ),
        migrations.AddIndex(
            model_name="dispatch",
            index=models.Index(
                fields=["destination_facility", "status"], name="concession__destina_628e23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispatch",
            index=models.Index(fields=["manifest_code"], name="concession__manifes_db00fb_idx"),
        ),
        migrations.AddIndex(
            model_name="pickitem",
            index=models.Index(
                fields=["pick_list", "is_picked"], name="concession__pick_li_1d1152_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="servicerecipe",
            constraint=models.UniqueConstraint(
                fields=("service", "material"), name="concession_recipe_service_material_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="supplyrequisition",
            index=models.Index(
                fields=["requesting_facility", "status"], name="concession__request_4015f3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="requisitionitem",
            constraint=models.UniqueConstraint(
                fields=("requisition", "material"), name="uniq_requisition_material"
            ),
        ),
        migrations.AddConstraint(
            model_name="requisitionitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", Decimal("0"))),
                name="requisition_item_qty_positive",
            ),
        ),
    ]
