# Generated by Django 5.2 on 2026-07-25 23:29

from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concession", "0002_picklist_concessioncontract_dispatch_dispatchitem_and_more"),
        ("imaging", "0004_enterprise_ris_workflow"),
        ("organization", "0001_initial"),
        ("pharmacy", "0031_controlledsubstanceledger_controlledledgerclosing_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialUnitCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Custo unitário do insumo para a economia da concessão.",
                        max_digits=12,
                        verbose_name="Custo unitário",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "material",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concession_unit_cost",
                        to="pharmacy.material",
                        verbose_name="Insumo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Custo unitário de insumo (concessão)",
                "verbose_name_plural": "Custos unitários de insumo (concessão)",
                "ordering": ["material__name"],
            },
        ),
        migrations.CreateModel(
            name="ExamConsumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "external_ref",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=128,
                        verbose_name="Referência externa do exame",
                    ),
                ),
                (
                    "performed_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Realizado em",
                    ),
                ),
                (
                    "cost_snapshot",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Σ quantidade_da_receita × custo_unitário no momento do exame.",
                        max_digits=12,
                        verbose_name="Custo consumido (congelado)",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Chave de idempotência"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dicom_study",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="concession_exam_consumptions",
                        to="imaging.dicomstudy",
                        verbose_name="Estudo DICOM (opcional)",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exam_consumptions",
                        to="concession.concessionservice",
                        verbose_name="Serviço/exame",
                    ),
                ),
                (
                    "source_warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="concession_exam_consumptions",
                        to="pharmacy.warehouse",
                        verbose_name="Estoque de origem",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="concession_exam_consumptions",
                        to="organization.facility",
                        verbose_name="Unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consumo por exame",
                "verbose_name_plural": "Consumos por exame",
                "ordering": ["-performed_at"],
                "indexes": [
                    models.Index(fields=["unit", "service"], name="concession__unit_id_4a309d_idx"),
                    models.Index(fields=["performed_at"], name="concession__perform_fd9506_idx"),
                ],
            },
        ),
    ]
