# Generated by Django 5.2 on 2026-07-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concession", "0003_materialunitcost_examconsumption"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatch",
            name="freight_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Custo de frete deste despacho; entra na perna de frete do P&L.",
                max_digits=12,
                null=True,
                verbose_name="Custo de frete",
            ),
        ),
    ]
