# Generated by Django 5.2 on 2026-05-20 17:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.patient_portal.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("emr", "0015_encounter_signed_at_signed_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientPortalAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Convidado"),
                            ("active", "Ativo"),
                            ("revoked", "Revogado"),
                        ],
                        db_index=True,
                        default="invited",
                        max_length=20,
                    ),
                ),
                (
                    "invite_token",
                    models.CharField(
                        db_index=True,
                        default=apps.patient_portal.models._generate_invite_token,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("invite_expires_at", models.DateTimeField()),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portal_invites_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_access",
                        to="emr.patient",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_portal_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "patient portal access",
                "ordering": ["-invited_at"],
                "indexes": [
                    models.Index(fields=["status", "-invited_at"], name="portal_status_idx")
                ],
            },
        ),
    ]
