# Generated by Django 5.2 on 2026-05-20 19:02

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MobileDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("ios", "iOS"),
                            ("android", "Android"),
                            ("web", "Web (browser push)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("device_id", models.CharField(db_index=True, max_length=128)),
                ("push_token", models.CharField(max_length=512)),
                ("app_version", models.CharField(blank=True, max_length=32)),
                ("os_version", models.CharField(blank=True, max_length=32)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobile_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-enrolled_at"],
            },
        ),
        migrations.CreateModel(
            name="PushDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Enviado"),
                            ("failed", "Falhou"),
                            ("no_provider", "Sem provider"),
                        ],
                        db_index=True,
                        default="no_provider",
                        max_length=20,
                    ),
                ),
                ("provider_message_id", models.CharField(blank=True, max_length=200)),
                ("provider_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_deliveries",
                        to="mobile.mobiledevice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="mobiledevice",
            index=models.Index(fields=["user", "is_active"], name="mobile_user_active_idx"),
        ),
        migrations.AddIndex(
            model_name="mobiledevice",
            index=models.Index(fields=["platform", "is_active"], name="mobile_plat_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="mobiledevice",
            constraint=models.UniqueConstraint(
                fields=("user", "device_id"), name="mobile_user_device_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="pushdelivery",
            index=models.Index(fields=["user", "-created_at"], name="push_user_idx"),
        ),
        migrations.AddIndex(
            model_name="pushdelivery",
            index=models.Index(fields=["status", "-created_at"], name="push_status_idx"),
        ),
    ]
