# Generated by Django 5.2 on 2026-04-03 01:43

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_stockitem_quantity_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('sent', 'Enviado ao fornecedor'), ('partial', 'Parcialmente recebido'), ('received', 'Recebido'), ('cancelled', 'Cancelado')], db_index=True, default='draft', max_length=20)),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Data prevista de entrega')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pedido de Compra',
                'verbose_name_plural': 'Pedidos de Compra',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_ordered', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Qtd pedida')),
                ('quantity_received', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Qtd recebida')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço unitário')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='Contato')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['name'],
            },
        ),
        migrations.RenameIndex(
            model_name='dispensation',
            new_name='pharmacy_di_patient_f540b4_idx',
            old_name='pharmacy_dispensation_patient',
        ),
        migrations.RenameIndex(
            model_name='dispensation',
            new_name='pharmacy_di_prescri_ef2584_idx',
            old_name='pharmacy_dispensation_rx',
        ),
        migrations.RenameIndex(
            model_name='drug',
            new_name='pharmacy_dr_name_d26b57_idx',
            old_name='pharmacy_drug_name_active',
        ),
        migrations.RenameIndex(
            model_name='drug',
            new_name='pharmacy_dr_generic_ce7297_idx',
            old_name='pharmacy_drug_generic_name',
        ),
        migrations.RenameIndex(
            model_name='drug',
            new_name='pharmacy_dr_control_a6fefb_idx',
            old_name='pharmacy_drug_controlled',
        ),
        migrations.RenameIndex(
            model_name='stockitem',
            new_name='pharmacy_st_drug_id_5d53b8_idx',
            old_name='pharmacy_stockitem_drug_expiry',
        ),
        migrations.RenameIndex(
            model_name='stockitem',
            new_name='pharmacy_st_materia_55c897_idx',
            old_name='pharmacy_stockitem_mat_expiry',
        ),
        migrations.RenameIndex(
            model_name='stockitem',
            new_name='pharmacy_st_expiry__bf9d31_idx',
            old_name='pharmacy_stockitem_expiry',
        ),
        migrations.AlterField(
            model_name='dispensationlot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('entry', 'Entrada'), ('purchase_order_receiving', 'Recebimento de Pedido de Compra'), ('dispense', 'Dispensação'), ('adjustment', 'Ajuste de inventário'), ('return', 'Devolução'), ('expired_write_off', 'Baixa por vencimento'), ('transfer', 'Transferência')], db_index=True, max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together={('drug', 'lot_number', 'expiry_date'), ('material', 'lot_number', 'expiry_date')},
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='drug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_items', to='pharmacy.drug'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_items', to='pharmacy.material'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='pharmacy.supplier'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('drug__isnull', False), ('material__isnull', False), _connector='OR'), name='po_item_must_have_drug_or_material'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('drug__isnull', False), ('material__isnull', False), _negated=True), name='po_item_not_both'),
        ),
    ]
