# Generated by Django 5.2 on 2026-06-01 19:36

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharmacy", "0005_stockitem_nulls_distinct_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicationFormulary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "strength_value",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Canonical strength magnitude, e.g. 10.000 for '10 mg'.",
                        max_digits=10,
                    ),
                ),
                (
                    "strength_unit",
                    models.CharField(
                        choices=[
                            ("mg", "mg"),
                            ("mcg", "mcg"),
                            ("mEq", "mEq"),
                            ("unit", "unit"),
                            ("g", "g"),
                        ],
                        help_text="Canonical mass unit (shared DOSE_UNIT_CHOICES): 'mg', 'mcg', 'mEq', 'unit', 'g'.",
                        max_length=10,
                    ),
                ),
                (
                    "volume_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="For injectables expressed per volume: the volume magnitude (e.g. 1.000).",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "volume_unit",
                    models.CharField(
                        blank=True,
                        choices=[("mL", "mL")],
                        help_text="Volume unit for injectables, e.g. 'mL' (strength is per this volume).",
                        max_length=10,
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        choices=[
                            ("IV", "Intravenosa"),
                            ("IM", "Intramuscular"),
                            ("SC", "Subcutânea"),
                            ("PO", "Oral"),
                        ],
                        help_text="Canonical administration route for this formulary entry.",
                        max_length=4,
                    ),
                ),
                ("is_injectable", models.BooleanField(default=False)),
                (
                    "is_high_alert",
                    models.BooleanField(
                        default=False,
                        help_text="ISMP high-alert medication (heightened risk of significant patient harm).",
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "drug",
                    models.OneToOneField(
                        help_text="Drug this formulary entry curates. One row per drug = dose-checkable.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="formulary",
                        to="pharmacy.drug",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medication Formulary Entry",
                "verbose_name_plural": "Medication Formulary",
                "ordering": ["drug__name"],
            },
        ),
        migrations.CreateModel(
            name="DoseRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "basis",
                    models.CharField(
                        choices=[("per_kg", "Por kg de peso"), ("fixed", "Dose fixa")],
                        help_text="per_kg = dose scales with body weight; fixed = weight-independent.",
                        max_length=10,
                    ),
                ),
                (
                    "age_min_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Lower age bound in DAYS, inclusive. Null = unbounded. Days (not years) so neonatal/infant bands don't all collapse to 0y (18y ≈ 6570 days).",
                        null=True,
                    ),
                ),
                (
                    "age_max_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Upper age bound in DAYS, inclusive. Null = unbounded. (18y ≈ 6570 days.)",
                        null=True,
                    ),
                ),
                (
                    "weight_min_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Lower weight bound (kg) for this band. Null = unbounded.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "weight_max_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Upper weight bound (kg) for this band. Null = unbounded.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "dose_unit",
                    models.CharField(
                        choices=[
                            ("mg", "mg"),
                            ("mcg", "mcg"),
                            ("mEq", "mEq"),
                            ("unit", "unit"),
                            ("g", "g"),
                        ],
                        help_text="ABSOLUTE MASS unit for every numeric field here (shared DOSE_UNIT_CHOICES): mg/mcg/mEq/unit/g. NEVER 'mg/kg' — per-kg fields are implicitly this unit per kg.",
                        max_length=10,
                    ),
                ),
                (
                    "min_per_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Per-kg lower bound (in dose_unit per kg). Required when basis='per_kg'.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "max_per_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Per-kg UPPER bound (in dose_unit per kg). Required when basis='per_kg'. This is the per-kg overdose ceiling — without it a per-kg overdose that stays under absolute_max_dose would pass silently.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "min_per_dose",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Absolute minimum single dose (dose_unit). Required when basis='fixed'.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "max_per_dose",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Absolute maximum single dose (dose_unit). Required when basis='fixed'.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "absolute_max_dose",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="MANDATORY universal hard ceiling for a single administration, in dose_unit. ALWAYS enforced regardless of basis. For basis='per_kg' it catches weight-entry typos that would otherwise push the per-kg math past a safe absolute dose; for basis='fixed' it is the absolute cap.",
                        max_digits=12,
                    ),
                ),
                (
                    "max_per_day",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Absolute maximum cumulative dose per day, in dose_unit (for max-daily checks in PR B). Null = none.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        blank=True,
                        help_text="Optional route this rule applies to; blank = any route on the formulary entry.",
                        max_length=4,
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Clinical citation / source for this rule (e.g. reference, dataset).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "formulary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dose_rules",
                        to="pharmacy.medicationformulary",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dose Rule",
                "verbose_name_plural": "Dose Rules",
                "ordering": ["formulary__drug__name", "age_min_days"],
            },
        ),
    ]
