# Generated by Django 5.2 on 2026-06-01 19:36

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharmacy", "0005_stockitem_nulls_distinct_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicationFormulary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "strength_value",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Canonical strength magnitude, e.g. 10.000 for '10 mg'.",
                        max_digits=10,
                    ),
                ),
                (
                    "strength_unit",
                    models.CharField(
                        help_text="Strength unit, e.g. 'mg', 'mcg', 'mEq', 'unit', 'g'.",
                        max_length=10,
                    ),
                ),
                (
                    "volume_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="For injectables expressed per volume: the volume magnitude (e.g. 1.000).",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "volume_unit",
                    models.CharField(
                        blank=True,
                        help_text="Volume unit for injectables, e.g. 'mL' (strength is per this volume).",
                        max_length=10,
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        choices=[
                            ("IV", "Intravenosa"),
                            ("IM", "Intramuscular"),
                            ("SC", "Subcutânea"),
                            ("PO", "Oral"),
                        ],
                        help_text="Canonical administration route for this formulary entry.",
                        max_length=4,
                    ),
                ),
                ("is_injectable", models.BooleanField(default=False)),
                (
                    "is_high_alert",
                    models.BooleanField(
                        default=False,
                        help_text="ISMP high-alert medication (heightened risk of significant patient harm).",
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "drug",
                    models.OneToOneField(
                        help_text="Drug this formulary entry curates. One row per drug = dose-checkable.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="formulary",
                        to="pharmacy.drug",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medication Formulary Entry",
                "verbose_name_plural": "Medication Formulary",
                "ordering": ["drug__name"],
            },
        ),
        migrations.CreateModel(
            name="DoseRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "basis",
                    models.CharField(
                        choices=[("per_kg", "Por kg de peso"), ("fixed", "Dose fixa")],
                        help_text="per_kg = dose scales with body weight; fixed = weight-independent.",
                        max_length=10,
                    ),
                ),
                (
                    "age_min_years",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="Lower age bound (years), inclusive. Null = unbounded.",
                        null=True,
                    ),
                ),
                (
                    "age_max_years",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="Upper age bound (years), inclusive. Null = unbounded.",
                        null=True,
                    ),
                ),
                (
                    "weight_min_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Lower weight bound (kg) for this band. Null = unbounded.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "weight_max_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Upper weight bound (kg) for this band. Null = unbounded.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "dose_unit",
                    models.CharField(
                        help_text="Unit the dose figures are expressed in (e.g. 'mg', 'mg/kg').",
                        max_length=20,
                    ),
                ),
                (
                    "min_per_dose",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Minimum recommended single dose. Null = no lower bound.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "max_per_dose",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="MANDATORY absolute ceiling for a single administration, in dose_unit. For basis='per_kg' this is still an ABSOLUTE cap (not per-kg) that catches weight-entry typos which would otherwise push a per-kg calc past a safe dose.",
                        max_digits=12,
                    ),
                ),
                (
                    "max_per_day",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Maximum cumulative dose per day (for max-daily checks in PR B). Null = none.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        blank=True,
                        help_text="Optional route this rule applies to; blank = any route on the formulary entry.",
                        max_length=4,
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Clinical citation / source for this rule (e.g. reference, dataset).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "formulary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dose_rules",
                        to="pharmacy.medicationformulary",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dose Rule",
                "verbose_name_plural": "Dose Rules",
                "ordering": ["formulary__drug__name", "age_min_years"],
            },
        ),
    ]
