# Generated by Django 5.2 on 2026-06-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharmacy", "0006_medicationformulary_doserule"),
    ]

    operations = [
        migrations.AddField(
            model_name="doserule",
            name="freq_min_per_day",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                help_text=(
                    "Lower bound (inclusive) on doses/day this rule applies to. Null = unbounded. "
                    "Set together with freq_max_per_day to scope a rule to one regimen frequency."
                ),
            ),
        ),
        migrations.AddField(
            model_name="doserule",
            name="freq_max_per_day",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                help_text="Upper bound (inclusive) on doses/day this rule applies to. Null = unbounded.",
            ),
        ),
        migrations.AddField(
            model_name="doserule",
            name="dose_role",
            field=models.CharField(
                choices=[("maintenance", "Manutenção"), ("loading", "Ataque/Loading")],
                default="maintenance",
                max_length=12,
                help_text=(
                    "maintenance (default) or loading. A loading rule is selected ONLY when the "
                    "prescribed item is explicitly marked loading; otherwise the maintenance band applies."
                ),
            ),
        ),
        migrations.AddField(
            model_name="doserule",
            name="enforcement",
            field=models.CharField(
                choices=[("block", "Bloquear"), ("advise", "Alertar (não bloqueante)")],
                default="block",
                max_length=10,
                help_text=(
                    "block (default) → OUT_OF_RANGE raises a blocking 409; advise → OUT_OF_RANGE is a "
                    "non-blocking caution (opioids/sedatives with no hard ceiling). WEIGHT_GATE / "
                    "UNIT_MISMATCH always block regardless of this field."
                ),
            ),
        ),
    ]
