# Generated by Django 5.2 — stockout-prediction wedge S1.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharmacy", "0007_doserule_dose_engine_v2"),
    ]

    operations = [
        migrations.AddField(
            model_name="drug",
            name="lead_time_days",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                help_text="Prazo de reposição do fornecedor (dias). NULL → predição inerte.",
            ),
        ),
        migrations.AddField(
            model_name="drug",
            name="safety_stock",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                help_text="Estoque de segurança (unidades-buffer). NULL → não considerado.",
            ),
        ),
        migrations.AddField(
            model_name="drug",
            name="reorder_point",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                help_text="Ponto de reposição explícito (unidades). NULL → não considerado.",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="lead_time_days",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                help_text="Prazo de reposição do fornecedor (dias). NULL → predição inerte.",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="safety_stock",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                help_text="Estoque de segurança (unidades-buffer). NULL → não considerado.",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="reorder_point",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                help_text="Ponto de reposição explícito (unidades). NULL → não considerado.",
            ),
        ),
    ]
