# Generated by Django 5.2 on 2026-06-03 19:13

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharmacy", "0008_stockout_config_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("stockout_risk", "Risco de ruptura"),
                            ("expiry_waste", "Desperdício por validade"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("advise", "Avisa")], default="advise", max_length=10
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("engine", "Motor determinístico"), ("llm", "LLM (explicação)")],
                        default="engine",
                        help_text="Qual checker produziu a linha: verdict 'engine' ou (futuro) 'llm'.",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Aberto"),
                            ("acknowledged", "Reconhecido"),
                            ("resolved", "Resolvido"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "predicted_date",
                    models.DateField(
                        blank=True,
                        help_text="Ruptura ou vencimento previsto.",
                        null=True,
                        verbose_name="Data prevista",
                    ),
                ),
                (
                    "days_to_stockout",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=10,
                        null=True,
                        verbose_name="Dias até ruptura",
                    ),
                ),
                (
                    "predicted_waste_qty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="Desperdício previsto",
                    ),
                ),
                ("engine_version", models.CharField(default="s2", max_length=10)),
                ("message", models.TextField(verbose_name="Mensagem (pt-BR)")),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_stock_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_alerts",
                        to="pharmacy.drug",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_alerts",
                        to="pharmacy.material",
                    ),
                ),
                (
                    "stock_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lote específico para expiry_waste; NULL para stockout_risk.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_alerts",
                        to="pharmacy.stockitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta de Estoque (motor)",
                "verbose_name_plural": "Alertas de Estoque (motor)",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "kind"], name="pharmacy_st_status_a58a0f_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("drug__isnull", False), ("material__isnull", True)),
                            models.Q(("drug__isnull", True), ("material__isnull", False)),
                            _connector="OR",
                        ),
                        name="stock_alert_drug_xor_material",
                    ),
                    models.UniqueConstraint(
                        fields=("drug", "material", "kind", "source", "stock_item"),
                        name="uniq_stock_alert",
                        nulls_distinct=False,
                    ),
                ],
            },
        ),
    ]
