# Generated by Django 5.2 on 2026-06-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharmacy", "0010_stockalert_suggested_reorder_qty"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockalert",
            name="graded_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Quando o job de flywheel gradou esta predição. NULL → ainda não gradado.",
                null=True,
                verbose_name="Gradado em",
            ),
        ),
        migrations.AddField(
            model_name="stockalert",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente (ainda não vencida)"),
                    ("true_positive", "Acerto (estoque zerou)"),
                    ("intercepted", "Interceptado (reposição chegou)"),
                    ("false_positive", "Falso-positivo (não zerou, sem reposição)"),
                ],
                db_index=True,
                default="pending",
                help_text="Rótulo do flywheel: o que aconteceu vs. o previsto. Gradado pelo job noturno.",
                max_length=20,
                verbose_name="Resultado (flywheel)",
            ),
        ),
    ]
