# Generated by Django 5.2 on 2026-06-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharmacy", "0012_grade_stockout_beat_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="drug",
            name="active_ingredients",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
