# Generated by Django 5.2 on 2026-06-04 17:30

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharmacy", "0013_drug_active_ingredients"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllergenClass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("members", models.JSONField(blank=True, default=list)),
                ("description", models.TextField(blank=True)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Classe de reatividade cruzada",
                "verbose_name_plural": "Classes de reatividade cruzada",
                "ordering": ["name"],
            },
        ),
    ]
