# Generated by Django 5.2 on 2026-06-04 17:49

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharmacy", "0014_allergenclass"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrugInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("ingredient_a", models.CharField(max_length=200)),
                ("ingredient_b", models.CharField(max_length=200)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("advise", "Avisa"),
                            ("contraindicated", "Contraindicada (bloqueia)"),
                        ],
                        default="advise",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Interação medicamentosa",
                "verbose_name_plural": "Interações medicamentosas",
                "ordering": ["ingredient_a", "ingredient_b"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ingredient_a", "ingredient_b"), name="uniq_drug_interaction_pair"
                    )
                ],
            },
        ),
    ]
