# Generated by Django 5.2 on 2026-06-04 22:20

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0023_no_show_beat_schedule"),
        ("pharmacy", "0015_druginteraction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="drug",
            name="min_refill_interval_days",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ControlledAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "signal_kind",
                    models.CharField(
                        choices=[
                            ("refill_too_soon", "Refill cedo demais"),
                            ("multiple_prescribers", "Múltiplos prescritores"),
                            ("quantity_escalation", "Escalada de quantidade"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("advise", "Avisa")], default="advise", max_length=10
                    ),
                ),
                ("detail", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Aberto"),
                            ("acknowledged", "Reconhecido"),
                            ("resolved", "Resolvido"),
                        ],
                        default="open",
                        max_length=14,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("true_positive", "Confirmado (diversão real)"),
                            ("false_positive", "Falso-positivo"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("engine_version", models.CharField(max_length=40)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_controlled_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dispensation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controlled_alerts",
                        to="pharmacy.dispensation",
                    ),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controlled_alerts",
                        to="pharmacy.drug",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controlled_alerts",
                        to="emr.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta de Controlado (motor)",
                "verbose_name_plural": "Alertas de Controlado (motor)",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "signal_kind"], name="pharmacy_co_status_4a7c10_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dispensation", "signal_kind"), name="uniq_controlled_alert"
                    )
                ],
            },
        ),
    ]
