# Generated by Django 5.2 on 2026-07-22 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0025_nfe_ingestion_channels'),
        ('pharmacy', '0025_nfecatalogmapping'),
    ]

    operations = [
    ]
