# Generated by Django 5.2 on 2026-07-24 17:24

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharmacy", "0030_drug_anvisa_product"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ControlledSubstanceLedger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("controlled_class", models.CharField(max_length=5)),
                ("presentation", models.CharField(blank=True, max_length=220)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("opening_balance", models.DecimalField(decimal_places=3, max_digits=14)),
                ("total_entries", models.DecimalField(decimal_places=3, max_digits=14)),
                ("total_exits", models.DecimalField(decimal_places=3, max_digits=14)),
                ("closing_balance", models.DecimalField(decimal_places=3, max_digits=14)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "built_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="controlled_ledgers_built",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="controlled_ledgers",
                        to="pharmacy.drug",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_start", "drug__name"],
            },
        ),
        migrations.CreateModel(
            name="ControlledLedgerClosing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("checked_balance", models.DecimalField(decimal_places=3, max_digits=14)),
                ("signature_hash", models.CharField(blank=True, max_length=128)),
                ("closed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "signed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="controlled_ledger_closings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ledger",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="closing",
                        to="pharmacy.controlledsubstanceledger",
                    ),
                ),
            ],
            options={
                "ordering": ["-closed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="controlledsubstanceledger",
            index=models.Index(
                fields=["controlled_class", "period_start"], name="pharmacy_co_control_c98586_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="controlledsubstanceledger",
            constraint=models.UniqueConstraint(
                fields=("drug", "period_start", "period_end"),
                name="uniq_controlled_ledger_drug_period",
            ),
        ),
    ]
