# Generated by Django 5.2 on 2026-09-26 13:13
#
# Ordem 028 — hand-edited after `makemigrations`: the auto-generated operations
# are RemoveField('validated') then the AddField's, in that order. That would
# drop the old boolean before we can read it. Reordered so `status_validacao`
# exists (defaulting EVERY row, including old validated=True ones, to
# nao_validado — that default IS the "no historical validation has a CRF on
# file, so none of them count as validado anymore" rule) and a RunPython step
# reports how many rows that demoted, per schema, BEFORE the old column is
# dropped. See apps.pharmacy.models.DoseRule.StatusValidacao / .validated.

from django.db import migrations, models


def report_demoted_rules(apps, schema_editor):
    """Count-only: `status_validacao` already defaulted every row (including
    old validated=True ones) to nao_validado in the AddField above — nothing
    to WRITE here. This only reads the (about to be dropped) `validated`
    column to print how many rows just lost their old sign-off, per schema,
    so an operator can see the blast radius per tenant during migrate_schemas.
    """
    DoseRule = apps.get_model("pharmacy", "DoseRule")
    demoted = DoseRule.objects.filter(validated=True).count()
    schema_name = getattr(schema_editor.connection, "schema_name", "?")
    print(
        f"[0033_dose_rule_status_validacao] schema={schema_name}: "
        f"{demoted} regra(s) validada(s) voltaram a nao_validado "
        "(nenhuma validação antiga tem CRF registrado)."
    )


class Migration(migrations.Migration):
    dependencies = [
        ("pharmacy", "0032_stockmovement_surgical_case"),
    ]

    operations = [
        migrations.AddField(
            model_name="doserule",
            name="fonte_ref",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Registro ANVISA + data da bula, OU referência/DOI da literatura.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="doserule",
            name="fonte_tipo",
            field=models.CharField(
                blank=True,
                choices=[("bula_anvisa", "Bula ANVISA"), ("literatura", "Literatura")],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="doserule",
            name="fonte_trecho",
            field=models.TextField(
                blank=True, default="", help_text="A posologia citada, tal como consta na fonte."
            ),
        ),
        migrations.AddField(
            model_name="doserule",
            name="status_validacao",
            field=models.CharField(
                choices=[("nao_validado", "Não validado"), ("validado", "Validado")],
                db_index=True,
                default="nao_validado",
                help_text="nao_validado (default, importado/rascunho) ou validado (farmacêutico com CRF assinou). Substitui o antigo booleano `validated` (ordem 028) — veja a migration de dados 0033.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="doserule",
            name="validado_crf_numero",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="doserule",
            name="validado_crf_uf",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
        migrations.RunPython(report_demoted_rules, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="doserule",
            name="validated",
        ),
    ]
