# Generated by Django 5.2 on 2026-05-20 16:07

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DigitalSignature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("encounter", "Encounter"),
                            ("prescription", "Prescription"),
                            ("custom", "Custom"),
                        ],
                        max_length=32,
                    ),
                ),
                ("document_id", models.CharField(max_length=64)),
                ("signature", models.BinaryField()),
                ("signature_algorithm", models.CharField(default="SHA256withRSA", max_length=64)),
                ("document_hash_hex", models.CharField(max_length=128)),
                ("cert_subject", models.CharField(max_length=500)),
                ("cert_issuer", models.CharField(blank=True, default="", max_length=500)),
                ("cert_serial_hex", models.CharField(max_length=64)),
                ("cert_not_valid_before", models.DateTimeField(blank=True, null=True)),
                ("cert_not_valid_after", models.DateTimeField()),
                ("is_icp_brasil", models.BooleanField(default=False)),
                ("signed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "signer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="digital_signatures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-signed_at"],
                "indexes": [
                    models.Index(fields=["document_type", "document_id"], name="sig_doc_idx"),
                    models.Index(fields=["signer", "-signed_at"], name="sig_signer_idx"),
                ],
            },
        ),
    ]
