# Generated by Django 5.2 on 2026-05-20 17:28

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("emr", "0015_encounter_signed_at_signed_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DicomStudy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "study_instance_uid",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                ("accession_number", models.CharField(blank=True, db_index=True, max_length=64)),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("CR", "Computed Radiography"),
                            ("CT", "Computed Tomography"),
                            ("DX", "Digital Radiography"),
                            ("MG", "Mammography"),
                            ("MR", "Magnetic Resonance"),
                            ("NM", "Nuclear Medicine"),
                            ("OT", "Other"),
                            ("PT", "Positron Emission Tomography (PET)"),
                            ("RF", "Radio Fluoroscopy"),
                            ("US", "Ultrasound"),
                            ("XA", "X-Ray Angiography"),
                        ],
                        db_index=True,
                        max_length=4,
                    ),
                ),
                ("body_part_examined", models.CharField(blank=True, max_length=64)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("study_date", models.DateTimeField()),
                ("number_of_series", models.PositiveIntegerField(default=0)),
                ("number_of_instances", models.PositiveIntegerField(default=0)),
                ("orthanc_study_id", models.CharField(blank=True, db_index=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dicom_studies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional — the encounter that requested the study, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dicom_studies",
                        to="emr.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dicom_studies",
                        to="emr.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-study_date"],
                "indexes": [
                    models.Index(fields=["patient", "-study_date"], name="img_pat_date_idx"),
                    models.Index(fields=["modality", "-study_date"], name="img_mod_date_idx"),
                ],
            },
        ),
    ]
