# Generated by Django 5.2 on 2026-07-21 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0028_expand_laboratory_domain"),
        ("imaging", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dicomstudy",
            name="related_lab_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional contextual link to a laboratory item for the same patient. The study remains a RIS/PACS resource, never a laboratory category.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="imaging_studies",
                to="emr.laborderitem",
            ),
        ),
        migrations.AddField(
            model_name="dicomstudy",
            name="report_document",
            field=models.OneToOneField(
                blank=True,
                help_text="Optional signed imaging report; content remains on the EMR document endpoint.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dicom_study",
                to="emr.clinicaldocument",
            ),
        ),
    ]
