# Generated by Django 5.2 on 2026-07-26 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imaging", "0004_enterprise_ris_workflow"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dicomstudy",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                help_text="Unidade onde o estudo foi realizado (multi-unidade / concessão).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dicom_studies",
                to="organization.facility",
            ),
        ),
    ]
