# Generated by Django 5.2 on 2026-05-20 17:40

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("emr", "0015_encounter_signed_at_signed_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TelemedicineSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "room_uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Agendada"),
                            ("in_progress", "Em atendimento"),
                            ("completed", "Concluída"),
                            ("cancelled", "Cancelada"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("scheduled_for", models.DateTimeField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("recording_url", models.URLField(blank=True, max_length=500)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="telemedicine_session",
                        to="emr.appointment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="telemedicine_sessions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="telemedicine_sessions",
                        to="emr.patient",
                    ),
                ),
                (
                    "professional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="telemedicine_sessions",
                        to="emr.professional",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_for"],
                "indexes": [
                    models.Index(fields=["patient", "-scheduled_for"], name="tele_pat_sched_idx"),
                    models.Index(
                        fields=["professional", "-scheduled_for"], name="tele_prof_sched_idx"
                    ),
                    models.Index(fields=["status", "-scheduled_for"], name="tele_status_idx"),
                ],
            },
        ),
    ]
