"""
S2 — Serializers da produção ambulatorial SUS (BPA + competência).
=================================================================
DRF serializers for :class:`SusCompetencia`, :class:`BpaConsolidado` (manual
BPA-C entry) and :class:`BpaIndividualizado` (read-only — generated by the
ambulatorial bridge). Gated ``sus.read`` / ``sus.write`` in ``views_sus``.
"""

from __future__ import annotations

from decimal import Decimal

from rest_framework import serializers

from apps.billing.sus_models import BpaConsolidado, BpaIndividualizado, SusCompetencia


class SusCompetenciaSerializer(serializers.ModelSerializer):
    class Meta:
        model = SusCompetencia
        fields = [
            "id",
            "establishment",
            "competencia",
            "status",
            "created_by",
            "created_at",
            "updated_at",
        ]
        # status is lifecycle-driven (fechar()/gerar-producao), never set directly;
        # created_by is stamped from the request user.
        read_only_fields = ["id", "status", "created_by", "created_at", "updated_at"]


class BpaConsolidadoSerializer(serializers.ModelSerializer):
    class Meta:
        model = BpaConsolidado
        fields = [
            "id",
            "competencia",
            "sigtap",
            "cbo",
            "idade",
            "quantidade",
            "valor",
            "created_at",
        ]
        # valor is computed from SIGTAP × quantidade at creation — never client-set.
        read_only_fields = ["id", "valor", "created_at"]

    def create(self, validated_data):
        sigtap = validated_data["sigtap"]
        quantidade = validated_data.get("quantidade", 1)
        sa = sigtap.valor_sa if sigtap.valor_sa is not None else Decimal("0")
        sp = sigtap.valor_sp if sigtap.valor_sp is not None else Decimal("0")
        validated_data["valor"] = (sa + sp) * quantidade
        return super().create(validated_data)


class BpaIndividualizadoSerializer(serializers.ModelSerializer):
    class Meta:
        model = BpaIndividualizado
        fields = [
            "id",
            "competencia",
            "sigtap",
            "cbo",
            "patient",
            "cns",
            "cid",
            "professional",
            "quantidade",
            "valor",
            "encounter_procedure",
            "created_at",
        ]
        read_only_fields = fields
