"""
Billing — Produção ambulatorial SUS (Sprint S2)
===============================================
Per-tenant SUS production models, kept in a dedicated module (imported at the end
of ``apps/billing/models.py``) so the SUS domain integrates as an additive leaf —
exactly like ``revenue_models`` — without churning the TISS billing file. The SUS
namespace (``sus.*`` RBAC) is deliberately SEPARATE from the TISS ``billing.*``
world: convênios (TISS) and SUS (BPA/APAC) are two independent faturamento tracks.

Models
------
* :class:`SusCompetencia` — the monthly faturamento window (competência "AAAA-MM")
  for one CNES establishment (``organization.Facility``). Lifecycle
  ``aberta → fechada → exportada`` (exportada/remessa is S3). Production is only
  generated while ``aberta``.
* :class:`BpaConsolidado` (BPA-C) — a consolidated, **patient-less** production
  line (procedure × CBO × faixa etária × quantidade). Entered manually.
* :class:`BpaIndividualizado` (BPA-I) — an **individualised** production line
  (com paciente/CNS + executor + CID). Generated by the ambulatorial bridge
  (:func:`apps.billing.services.sus_production.gerar_producao_ambulatorial`) from
  SUS-coded ``emr.EncounterProcedure``s, optionally linking back to the origin
  procedure for traceability.

Cross-schema FK note
--------------------
``core.SIGTAPProcedure`` and ``core.CBOCode`` live in the PUBLIC/SHARED schema.
PostgreSQL does not enforce FK integrity across schemas (tenant → public), so —
exactly like ``emr.EncounterProcedure.tuss_code`` / ``emr.Professional.cbo`` — the
``sigtap`` / ``cbo`` FKs use ``on_delete=DO_NOTHING`` and rely on the
``protect_sigtap_procedure_deletion`` / ``protect_cbo_code_deletion`` pre_delete
signals (apps/core/signals.py) to block deleting a catalog row any tenant
references from a BPA line.

CNS snapshot decision (BPA-I)
-----------------------------
``BpaIndividualizado.cns`` stores a **plain snapshot** of the patient's CNS taken
at generation time. ``Patient.cns`` is an ``EncryptedCharField`` (opaque
ciphertext, not queryable); the BPA remessa needs the raw 15-digit CNS and the
production line must be a stable, point-in-time record even if the patient's
registration later changes — so we snapshot rather than dereference the encrypted
field on export. ``patient`` is kept as an FK for traceability.
"""

from __future__ import annotations

from decimal import Decimal

from django.core.exceptions import ValidationError
from django.db import models


class SusCompetencia(models.Model):
    """Janela mensal de faturamento SUS de um estabelecimento (CNES). Per-tenant."""

    class Status(models.TextChoices):
        ABERTA = "aberta", "Aberta"
        FECHADA = "fechada", "Fechada"
        EXPORTADA = "exportada", "Exportada"

    establishment = models.ForeignKey(
        "organization.Facility",
        on_delete=models.PROTECT,
        related_name="sus_competencias",
        verbose_name="Estabelecimento (CNES)",
    )
    competencia = models.CharField("Competência (AAAA-MM)", max_length=7, help_text="Ex.: 2026-07")
    status = models.CharField(
        "Situação",
        max_length=12,
        choices=Status.choices,
        default=Status.ABERTA,
        db_index=True,
    )
    created_by = models.ForeignKey(
        "core.User",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="sus_competencias_criadas",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Competência SUS"
        verbose_name_plural = "Competências SUS"
        ordering = ["-competencia"]
        constraints = [
            models.UniqueConstraint(
                fields=["establishment", "competencia"],
                name="uniq_sus_competencia_per_establishment",
            ),
        ]

    def __str__(self):
        return f"Competência SUS {self.competencia} — {self.establishment_id} ({self.status})"

    def fechar(self):
        """Transição ``aberta → fechada``. Rejeita se já fechada/exportada."""
        if self.status != self.Status.ABERTA:
            raise ValidationError(
                f"Competência {self.competencia} não está aberta (status={self.status})."
            )
        self.status = self.Status.FECHADA
        self.save(update_fields=["status", "updated_at"])


class BpaConsolidado(models.Model):
    """BPA-C — linha de produção consolidada (sem paciente). Per-tenant.

    Procedimento × CBO × faixa etária × quantidade, valorado via SIGTAP. Entrada
    manual (não gerado automaticamente pelo bridge).
    """

    competencia = models.ForeignKey(SusCompetencia, on_delete=models.CASCADE, related_name="bpa_c")
    # Cross-schema (public) — DO_NOTHING + pre_delete PROTECT signal.
    sigtap = models.ForeignKey(
        "core.SIGTAPProcedure",
        on_delete=models.DO_NOTHING,
        related_name="+",
        verbose_name="Procedimento SIGTAP",
    )
    cbo = models.ForeignKey(
        "core.CBOCode",
        on_delete=models.DO_NOTHING,
        related_name="+",
        verbose_name="Ocupação CBO",
    )
    idade = models.PositiveIntegerField("Idade (faixa etária consolidada)")
    quantidade = models.PositiveIntegerField("Quantidade", default=1)
    valor = models.DecimalField(
        "Valor (R$)",
        max_digits=12,
        decimal_places=2,
        default=Decimal("0"),
        help_text="(sigtap.valor_sa + sigtap.valor_sp) × quantidade, no momento do registro.",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "BPA Consolidado (BPA-C)"
        verbose_name_plural = "BPA Consolidados (BPA-C)"
        ordering = ["-created_at"]

    def __str__(self):
        return f"BPA-C {self.sigtap_id} × {self.quantidade} (comp {self.competencia_id})"


class BpaIndividualizado(models.Model):
    """BPA-I — linha de produção individualizada (com paciente/CNS). Per-tenant.

    Gerado pelo bridge ambulatorial a partir de ``emr.EncounterProcedure``s
    SUS-codificados; ``encounter_procedure`` liga de volta à origem clínica.
    """

    competencia = models.ForeignKey(SusCompetencia, on_delete=models.CASCADE, related_name="bpa_i")
    sigtap = models.ForeignKey(
        "core.SIGTAPProcedure",
        on_delete=models.DO_NOTHING,
        related_name="+",
        verbose_name="Procedimento SIGTAP",
    )
    cbo = models.ForeignKey(
        "core.CBOCode",
        on_delete=models.DO_NOTHING,
        null=True,
        blank=True,
        related_name="+",
        verbose_name="Ocupação CBO",
    )
    patient = models.ForeignKey(
        "emr.Patient",
        on_delete=models.PROTECT,
        related_name="bpa_i_lines",
        verbose_name="Paciente",
    )
    # Plain snapshot of the patient's CNS at generation time (Patient.cns is
    # EncryptedCharField — opaque; the remessa needs the raw 15-digit CNS and the
    # line must be a stable point-in-time record). See module docstring.
    cns = models.CharField("CNS do paciente (snapshot)", max_length=15, blank=True, default="")
    cid = models.CharField("CID-10", max_length=10, blank=True, default="")
    professional = models.ForeignKey(
        "emr.Professional",
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="bpa_i_lines",
        verbose_name="Executor",
    )
    quantidade = models.PositiveIntegerField("Quantidade", default=1)
    valor = models.DecimalField(
        "Valor (R$)",
        max_digits=12,
        decimal_places=2,
        default=Decimal("0"),
        help_text="(sigtap.valor_sa + sigtap.valor_sp) × quantidade.",
    )
    encounter_procedure = models.ForeignKey(
        "emr.EncounterProcedure",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="bpa_i_lines",
        verbose_name="Procedimento clínico de origem",
        help_text="Origem clínica (rastreabilidade). Usado para idempotência do bridge.",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "BPA Individualizado (BPA-I)"
        verbose_name_plural = "BPA Individualizados (BPA-I)"
        ordering = ["-created_at"]
        constraints = [
            # Idempotency backstop: at most one BPA-I per (competência, origin
            # procedure). The bridge also skips already-linked procedures, but the
            # DB constraint guarantees a concurrent double-run cannot duplicate.
            models.UniqueConstraint(
                fields=["competencia", "encounter_procedure"],
                condition=models.Q(encounter_procedure__isnull=False),
                name="uniq_bpa_i_per_competencia_encproc",
            ),
        ]

    def __str__(self):
        return f"BPA-I {self.sigtap_id} — {self.patient_id} (comp {self.competencia_id})"
