"""
Billing — Produção ambulatorial SUS (Sprint S2)
===============================================
Per-tenant SUS production models, kept in a dedicated module (imported at the end
of ``apps/billing/models.py``) so the SUS domain integrates as an additive leaf —
exactly like ``revenue_models`` — without churning the TISS billing file. The SUS
namespace (``sus.*`` RBAC) is deliberately SEPARATE from the TISS ``billing.*``
world: convênios (TISS) and SUS (BPA/APAC) are two independent faturamento tracks.

Models
------
* :class:`SusCompetencia` — the monthly faturamento window (competência "AAAA-MM")
  for one CNES establishment (``organization.Facility``). Lifecycle
  ``aberta → fechada → exportada`` (exportada/remessa is S3). Production is only
  generated while ``aberta``.
* :class:`BpaConsolidado` (BPA-C) — a consolidated, **patient-less** production
  line (procedure × CBO × faixa etária × quantidade). Entered manually.
* :class:`BpaIndividualizado` (BPA-I) — an **individualised** production line
  (com paciente/CNS + executor + CID). Generated by the ambulatorial bridge
  (:func:`apps.billing.services.sus_production.gerar_producao_ambulatorial`) from
  SUS-coded ``emr.EncounterProcedure``s, optionally linking back to the origin
  procedure for traceability.

Cross-schema FK note
--------------------
``core.SIGTAPProcedure`` and ``core.CBOCode`` live in the PUBLIC/SHARED schema.
PostgreSQL does not enforce FK integrity across schemas (tenant → public), so —
exactly like ``emr.EncounterProcedure.tuss_code`` / ``emr.Professional.cbo`` — the
``sigtap`` / ``cbo`` FKs use ``on_delete=DO_NOTHING`` and rely on the
``protect_sigtap_procedure_deletion`` / ``protect_cbo_code_deletion`` pre_delete
signals (apps/core/signals.py) to block deleting a catalog row any tenant
references from a BPA line.

CNS snapshot decision (BPA-I)
-----------------------------
``BpaIndividualizado.cns`` stores a **plain snapshot** of the patient's CNS taken
at generation time. ``Patient.cns`` is an ``EncryptedCharField`` (opaque
ciphertext, not queryable); the BPA remessa needs the raw 15-digit CNS and the
production line must be a stable, point-in-time record even if the patient's
registration later changes — so we snapshot rather than dereference the encrypted
field on export. ``patient`` is kept as an FK for traceability.
"""

from __future__ import annotations

from decimal import Decimal

from django.core.exceptions import ValidationError
from django.db import models


class SusCompetencia(models.Model):
    """Janela mensal de faturamento SUS de um estabelecimento (CNES). Per-tenant."""

    class Status(models.TextChoices):
        ABERTA = "aberta", "Aberta"
        FECHADA = "fechada", "Fechada"
        EXPORTADA = "exportada", "Exportada"

    establishment = models.ForeignKey(
        "organization.Facility",
        on_delete=models.PROTECT,
        related_name="sus_competencias",
        verbose_name="Estabelecimento (CNES)",
    )
    competencia = models.CharField("Competência (AAAA-MM)", max_length=7, help_text="Ex.: 2026-07")
    status = models.CharField(
        "Situação",
        max_length=12,
        choices=Status.choices,
        default=Status.ABERTA,
        db_index=True,
    )
    created_by = models.ForeignKey(
        "core.User",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="sus_competencias_criadas",
    )
    # S3 — Remessa DATASUS (BPA-Magnético / APAC posicional). On export the
    # generated fixed-width remessa text is STORED here (not regenerated on
    # download) so the exact exported bytes are an immutable, auditable record of
    # what was transmitted to the SUS — even if BPA/APAC rows later change. See
    # apps/billing/services/sus_remessa.py.
    remessa_bpa = models.TextField(
        "Remessa BPA-Magnético (texto posicional)",
        blank=True,
        default="",
        help_text="Conteúdo .txt da remessa BPA gerado no momento da exportação (imutável).",
    )
    remessa_apac = models.TextField(
        "Remessa APAC (texto posicional)",
        blank=True,
        default="",
        help_text="Conteúdo .txt da remessa APAC gerado no momento da exportação (imutável).",
    )
    remessa_aih = models.TextField(
        "Remessa AIH (SISAIH, texto posicional)",
        blank=True,
        default="",
        help_text="Conteúdo .txt da remessa AIH (SISAIH) gerado no momento da exportação (imutável).",
    )
    exportada_at = models.DateTimeField(
        "Exportada em",
        null=True,
        blank=True,
        help_text="Timestamp da exportação da remessa (transição fechada → exportada).",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Competência SUS"
        verbose_name_plural = "Competências SUS"
        ordering = ["-competencia"]
        constraints = [
            models.UniqueConstraint(
                fields=["establishment", "competencia"],
                name="uniq_sus_competencia_per_establishment",
            ),
        ]

    def __str__(self):
        return f"Competência SUS {self.competencia} — {self.establishment_id} ({self.status})"

    def fechar(self):
        """Transição ``aberta → fechada``. Rejeita se já fechada/exportada."""
        if self.status != self.Status.ABERTA:
            raise ValidationError(
                f"Competência {self.competencia} não está aberta (status={self.status})."
            )
        self.status = self.Status.FECHADA
        self.save(update_fields=["status", "updated_at"])


class BpaConsolidado(models.Model):
    """BPA-C — linha de produção consolidada (sem paciente). Per-tenant.

    Procedimento × CBO × faixa etária × quantidade, valorado via SIGTAP. Entrada
    manual (não gerado automaticamente pelo bridge).
    """

    competencia = models.ForeignKey(SusCompetencia, on_delete=models.CASCADE, related_name="bpa_c")
    # Cross-schema (public) — DO_NOTHING + pre_delete PROTECT signal.
    sigtap = models.ForeignKey(
        "core.SIGTAPProcedure",
        on_delete=models.DO_NOTHING,
        related_name="+",
        verbose_name="Procedimento SIGTAP",
    )
    cbo = models.ForeignKey(
        "core.CBOCode",
        on_delete=models.DO_NOTHING,
        related_name="+",
        verbose_name="Ocupação CBO",
    )
    idade = models.PositiveIntegerField("Idade (faixa etária consolidada)")
    quantidade = models.PositiveIntegerField("Quantidade", default=1)
    valor = models.DecimalField(
        "Valor (R$)",
        max_digits=12,
        decimal_places=2,
        default=Decimal("0"),
        help_text="(sigtap.valor_sa + sigtap.valor_sp) × quantidade, no momento do registro.",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "BPA Consolidado (BPA-C)"
        verbose_name_plural = "BPA Consolidados (BPA-C)"
        ordering = ["-created_at"]

    def __str__(self):
        return f"BPA-C {self.sigtap_id} × {self.quantidade} (comp {self.competencia_id})"


class BpaIndividualizado(models.Model):
    """BPA-I — linha de produção individualizada (com paciente/CNS). Per-tenant.

    Gerado pelo bridge ambulatorial a partir de ``emr.EncounterProcedure``s
    SUS-codificados; ``encounter_procedure`` liga de volta à origem clínica.
    """

    competencia = models.ForeignKey(SusCompetencia, on_delete=models.CASCADE, related_name="bpa_i")
    sigtap = models.ForeignKey(
        "core.SIGTAPProcedure",
        on_delete=models.DO_NOTHING,
        related_name="+",
        verbose_name="Procedimento SIGTAP",
    )
    cbo = models.ForeignKey(
        "core.CBOCode",
        on_delete=models.DO_NOTHING,
        null=True,
        blank=True,
        related_name="+",
        verbose_name="Ocupação CBO",
    )
    patient = models.ForeignKey(
        "emr.Patient",
        on_delete=models.PROTECT,
        related_name="bpa_i_lines",
        verbose_name="Paciente",
    )
    # Plain snapshot of the patient's CNS at generation time (Patient.cns is
    # EncryptedCharField — opaque; the remessa needs the raw 15-digit CNS and the
    # line must be a stable point-in-time record). See module docstring.
    cns = models.CharField("CNS do paciente (snapshot)", max_length=15, blank=True, default="")
    cid = models.CharField("CID-10", max_length=10, blank=True, default="")
    professional = models.ForeignKey(
        "emr.Professional",
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="bpa_i_lines",
        verbose_name="Executor",
    )
    quantidade = models.PositiveIntegerField("Quantidade", default=1)
    valor = models.DecimalField(
        "Valor (R$)",
        max_digits=12,
        decimal_places=2,
        default=Decimal("0"),
        help_text="(sigtap.valor_sa + sigtap.valor_sp) × quantidade.",
    )
    encounter_procedure = models.ForeignKey(
        "emr.EncounterProcedure",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="bpa_i_lines",
        verbose_name="Procedimento clínico de origem",
        help_text="Origem clínica (rastreabilidade). Usado para idempotência do bridge.",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "BPA Individualizado (BPA-I)"
        verbose_name_plural = "BPA Individualizados (BPA-I)"
        ordering = ["-created_at"]
        constraints = [
            # Idempotency backstop: at most one BPA-I per (competência, origin
            # procedure). The bridge also skips already-linked procedures, but the
            # DB constraint guarantees a concurrent double-run cannot duplicate.
            models.UniqueConstraint(
                fields=["competencia", "encounter_procedure"],
                condition=models.Q(encounter_procedure__isnull=False),
                name="uniq_bpa_i_per_competencia_encproc",
            ),
        ]

    def __str__(self):
        return f"BPA-I {self.sigtap_id} — {self.patient_id} (comp {self.competencia_id})"


class ApacAutorizacao(models.Model):
    """APAC — Autorização de Procedimento de Alta Complexidade (S3). Per-tenant.

    Unlike a BPA line (a raw production record), an APAC is an *autorização*: a
    numbered, date-bounded authorization for one high-complexity main procedure
    (``procedimento_principal``) plus zero or more secondary procedures
    (:class:`ApacProcedimentoSecundario`), tied to a patient/CNS and the
    requesting/executing professionals. Its ``valor`` is the authorized value
    carried by the authorization itself (not a pure SIGTAP × qtd derivation), so
    it is set explicitly rather than computed.

    The ``procedimento_principal`` FK is cross-schema (tenant → public
    ``core.SIGTAPProcedure``): PostgreSQL does not enforce FK integrity across
    schemas, so — exactly like the BPA lines — it uses ``on_delete=DO_NOTHING``
    and relies on the ``protect_sigtap_procedure_deletion`` pre_delete signal
    (apps/core/signals.py, extended in S3 to cover APAC) to block deleting a
    catalog row any APAC references.

    ``cns`` is a plain snapshot of the patient's CNS at authorization time (same
    rationale as ``BpaIndividualizado.cns`` — ``Patient.cns`` is an encrypted,
    non-queryable field and the authorization must be a stable point-in-time
    record). ``patient`` is kept as an FK for traceability.
    """

    competencia = models.ForeignKey(SusCompetencia, on_delete=models.CASCADE, related_name="apacs")
    numero_apac = models.CharField(
        "Número da APAC",
        max_length=13,
        unique=True,
        help_text="Número único da autorização APAC (emitido pelo gestor SUS).",
    )
    validade_inicio = models.DateField("Início da validade")
    validade_fim = models.DateField("Fim da validade")
    # Cross-schema (public) — DO_NOTHING + pre_delete PROTECT signal.
    procedimento_principal = models.ForeignKey(
        "core.SIGTAPProcedure",
        on_delete=models.DO_NOTHING,
        related_name="+",
        verbose_name="Procedimento principal (SIGTAP)",
    )
    cid_principal = models.CharField("CID-10 principal", max_length=10, blank=True, default="")
    patient = models.ForeignKey(
        "emr.Patient",
        on_delete=models.PROTECT,
        related_name="apac_autorizacoes",
        verbose_name="Paciente",
    )
    cns = models.CharField("CNS do paciente (snapshot)", max_length=15, blank=True, default="")
    professional_solicitante = models.ForeignKey(
        "emr.Professional",
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="apac_solicitadas",
        verbose_name="Profissional solicitante",
    )
    professional_executante = models.ForeignKey(
        "emr.Professional",
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="apac_executadas",
        verbose_name="Profissional executante",
    )
    valor = models.DecimalField(
        "Valor autorizado (R$)",
        max_digits=12,
        decimal_places=2,
        default=Decimal("0"),
        help_text="Valor autorizado da APAC (procedimento principal + secundários).",
    )
    created_by = models.ForeignKey(
        "core.User",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="apac_autorizacoes_criadas",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Autorização APAC"
        verbose_name_plural = "Autorizações APAC"
        ordering = ["-created_at"]

    def __str__(self):
        return f"APAC {self.numero_apac} — {self.procedimento_principal_id} (comp {self.competencia_id})"


class ApacProcedimentoSecundario(models.Model):
    """Procedimento secundário de uma APAC (S3). Per-tenant.

    ``sigtap`` FK is cross-schema (DO_NOTHING + protect signal, same as the APAC
    main procedure). ``valor`` mirrors the BPA-C convention: computed from
    ``(sigtap.valor_sa + sigtap.valor_sp) × quantidade`` at creation.
    """

    apac = models.ForeignKey(
        ApacAutorizacao, on_delete=models.CASCADE, related_name="procedimentos_secundarios"
    )
    sigtap = models.ForeignKey(
        "core.SIGTAPProcedure",
        on_delete=models.DO_NOTHING,
        related_name="+",
        verbose_name="Procedimento secundário (SIGTAP)",
    )
    quantidade = models.PositiveIntegerField("Quantidade", default=1)
    valor = models.DecimalField(
        "Valor (R$)",
        max_digits=12,
        decimal_places=2,
        default=Decimal("0"),
        help_text="(sigtap.valor_sa + sigtap.valor_sp) × quantidade, no momento do registro.",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Procedimento secundário APAC"
        verbose_name_plural = "Procedimentos secundários APAC"
        ordering = ["created_at"]

    def __str__(self):
        return f"APAC-sec {self.sigtap_id} × {self.quantidade} (apac {self.apac_id})"


class AihAutorizacao(models.Model):
    """AIH — Autorização de Internação Hospitalar (SISAIH). Per-tenant.

    Structurally mirrors :class:`ApacAutorizacao`, adapted to an *internação*
    (inpatient stay) instead of an ambulatorial high-complexity authorization: a
    numbered authorization (``numero_aih``) for one main hospital procedure
    (``procedimento_principal``) plus zero or more secondary procedures
    (:class:`AihProcedimentoSecundario`), tied to a patient/CNS and the
    requesting/responsible professionals, over an internação window
    (``data_internacao`` → ``data_saida``).

    Anchored to the clinical :class:`~apps.emr.adt_models.Admission` via the
    ``admission`` FK (``on_delete=SET_NULL`` — the authorization survives an
    admission being purged). A partial ``UniqueConstraint`` enforces at most one
    AIH per admission (idempotency backstop for the AI2 Admission→AIH bridge,
    same pattern as ``BpaIndividualizado``'s per-encounter-procedure guard).

    Like APAC, ``valor`` is the authorized value carried by the authorization
    itself (SH+SP, not a pure SIGTAP × qtd derivation), so it is set explicitly
    rather than computed in the header.

    The ``procedimento_principal`` FK is cross-schema (tenant → public
    ``core.SIGTAPProcedure``): PostgreSQL does not enforce FK integrity across
    schemas, so — exactly like the BPA/APAC lines — it uses
    ``on_delete=DO_NOTHING`` and relies on the
    ``protect_sigtap_procedure_deletion`` pre_delete signal (apps/core/signals.py,
    extended for AIH) to block deleting a catalog row any AIH references.

    ``cns`` is a plain snapshot of the patient's CNS at authorization time (same
    rationale as ``ApacAutorizacao.cns`` — ``Patient.cns`` is an encrypted,
    non-queryable field and the authorization must be a stable point-in-time
    record). ``patient`` is kept as an FK for traceability.
    """

    class CaraterInternacao(models.TextChoices):
        # Códigos SUS oficiais do caráter de internação (SISAIH).
        ELETIVO = "01", "Eletivo"
        URGENCIA = "02", "Urgência"

    class MotivoSaida(models.TextChoices):
        # Motivos de saída/permanência principais da AIH. Os códigos SUS oficiais
        # posicionais entram na remessa SISAIH (AI3); aqui usamos rótulos claros
        # para o header, mantendo a semântica do desfecho da internação.
        ALTA_MELHORADO = "alta_melhorado", "Alta por melhora"
        ALTA_CURADO = "alta_curado", "Alta por cura"
        TRANSFERENCIA = "transferencia", "Transferência"
        OBITO = "obito", "Óbito"
        PERMANENCIA = "permanencia", "Permanência"

    class Situacao(models.TextChoices):
        # Ciclo de vida da autorização perante o gestor SUS. Nasce SOLICITADA
        # (número provisório interno); vira AUTORIZADA quando o gestor devolve o
        # número oficial de 13 dígitos (reconciliação); REJEITADA quando glosada.
        SOLICITADA = "solicitada", "Solicitada"
        AUTORIZADA = "autorizada", "Autorizada"
        REJEITADA = "rejeitada", "Rejeitada"

    competencia = models.ForeignKey(SusCompetencia, on_delete=models.CASCADE, related_name="aihs")
    numero_aih = models.CharField(
        "Número da AIH",
        max_length=13,
        unique=True,
        help_text="Número corrente da AIH: provisório interno até a reconciliação "
        "substituí-lo pelo número oficial de 13 dígitos emitido pelo gestor SUS.",
    )
    situacao = models.CharField(
        "Situação",
        max_length=12,
        choices=Situacao.choices,
        default=Situacao.SOLICITADA,
        db_index=True,
        help_text="Ciclo perante o gestor: solicitada → autorizada/rejeitada.",
    )
    numero_provisorio = models.CharField(
        "Número provisório (histórico)",
        max_length=13,
        blank=True,
        default="",
        help_text="Número provisório interno original, preservado na reconciliação "
        "para rastreabilidade quando numero_aih passa a ser o oficial.",
    )
    data_autorizacao = models.DateField(
        "Data da autorização", null=True, blank=True, help_text="Data em que o gestor autorizou."
    )
    motivo_rejeicao = models.CharField("Motivo da rejeição", max_length=255, blank=True, default="")
    # A internação âncora. SET_NULL: a autorização sobrevive à remoção da
    # internação; a UniqueConstraint parcial garante uma AIH por internação.
    admission = models.ForeignKey(
        "emr.Admission",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="aihs",
        verbose_name="Internação",
    )
    # Cross-schema (public) — DO_NOTHING + pre_delete PROTECT signal.
    procedimento_principal = models.ForeignKey(
        "core.SIGTAPProcedure",
        on_delete=models.DO_NOTHING,
        related_name="+",
        verbose_name="Procedimento principal (SIGTAP)",
    )
    cid_principal = models.CharField("CID-10 principal", max_length=10, blank=True, default="")
    patient = models.ForeignKey(
        "emr.Patient",
        on_delete=models.PROTECT,
        related_name="aih_autorizacoes",
        verbose_name="Paciente",
    )
    cns = models.CharField("CNS do paciente (snapshot)", max_length=15, blank=True, default="")
    professional_solicitante = models.ForeignKey(
        "emr.Professional",
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="aih_solicitadas",
        verbose_name="Profissional solicitante",
    )
    professional_responsavel = models.ForeignKey(
        "emr.Professional",
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="aih_responsaveis",
        verbose_name="Profissional responsável",
    )
    data_internacao = models.DateField("Data da internação")
    data_saida = models.DateField("Data da saída", null=True, blank=True)
    carater_internacao = models.CharField(
        "Caráter da internação",
        max_length=2,
        choices=CaraterInternacao.choices,
        default=CaraterInternacao.ELETIVO,
    )
    motivo_saida = models.CharField(
        "Motivo de saída/permanência",
        max_length=20,
        choices=MotivoSaida.choices,
        blank=True,
        default="",
    )
    valor = models.DecimalField(
        "Valor autorizado (R$)",
        max_digits=12,
        decimal_places=2,
        default=Decimal("0"),
        help_text="Valor autorizado da AIH (SH+SP: serviços hospitalares + profissionais).",
    )
    created_by = models.ForeignKey(
        "core.User",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="aih_autorizacoes_criadas",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Autorização AIH"
        verbose_name_plural = "Autorizações AIH"
        ordering = ["-created_at"]
        constraints = [
            # Idempotency: at most one AIH per internação. NULL admission rows are
            # exempt (an AIH may be created before/without an admission link).
            models.UniqueConstraint(
                fields=["admission"],
                condition=models.Q(admission__isnull=False),
                name="uniq_aih_per_admission",
            ),
        ]

    def __str__(self):
        return (
            f"AIH {self.numero_aih} — {self.procedimento_principal_id} (comp {self.competencia_id})"
        )


class AihProcedimentoSecundario(models.Model):
    """Procedimento secundário de uma AIH (SISAIH). Per-tenant.

    ``sigtap`` FK is cross-schema (DO_NOTHING + protect signal, same as the AIH
    main procedure). ``valor`` is computed on ``save`` from
    ``(sigtap.valor_sh + sigtap.valor_sp) × quantidade`` — note AIH uses **SH+SP**
    (serviços hospitalares + serviços profissionais), differing from the APAC/BPA
    convention of SA+SP (serviço ambulatorial + profissionais), because inpatient
    procedures are valued on the hospital-services axis.
    """

    aih = models.ForeignKey(
        AihAutorizacao, on_delete=models.CASCADE, related_name="procedimentos_secundarios"
    )
    sigtap = models.ForeignKey(
        "core.SIGTAPProcedure",
        on_delete=models.DO_NOTHING,
        related_name="+",
        verbose_name="Procedimento secundário (SIGTAP)",
    )
    quantidade = models.PositiveIntegerField("Quantidade", default=1)
    valor = models.DecimalField(
        "Valor (R$)",
        max_digits=12,
        decimal_places=2,
        default=Decimal("0"),
        help_text="(sigtap.valor_sh + sigtap.valor_sp) × quantidade, computado no save.",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Procedimento secundário AIH"
        verbose_name_plural = "Procedimentos secundários AIH"
        ordering = ["created_at"]

    def save(self, *args, **kwargs):
        # AIH usa SH+SP (serviços hospitalares + profissionais), diferente do
        # SA+SP da APAC/BPA. Computado aqui para ser a fonte da verdade do valor.
        sigtap = self.sigtap
        sh = sigtap.valor_sh if sigtap.valor_sh is not None else Decimal("0")
        sp = sigtap.valor_sp if sigtap.valor_sp is not None else Decimal("0")
        self.valor = (sh + sp) * self.quantidade
        super().save(*args, **kwargs)

    def __str__(self):
        return f"AIH-sec {self.sigtap_id} × {self.quantidade} (aih {self.aih_id})"
